### ISSUE TITLE
Date localisation in email

### ISSUE THREAD

**Issue by WXQ8NPb5TrbDNqzywcxF** [liedekef/events-made-easy#10]
Hi,

I'm not sure if it's me or a bug,  but my it seem that even if the wordpress in in french,  when email is sent,  the month is still in english.
So, in email, when i'm sending : #_STARTDATE  instead of having "30 janvier 2023" in the email I have "30 January 2023"

Thanks

**Comment by liedekef** [comment]
Please describe the problem in more detail:
- is the rsvp person already existing in EME? If so, what are his language settings in EME?
- are you sending the email from the backend or frontend? What is the language setting there?

**Comment by liedekef** [comment]
Ok, I looked in the code a bit: #_STARTDATE uses (in the end) the wp  function wp_date to format and localize the date/time. This again uses the global $wp_locale (so your WP locale of choice of that moment), so it means your locale of the moment was English probably.

**Comment by WXQ8NPb5TrbDNqzywcxF** [comment]
Thanks a lot,  I think it's because I was logged with my wordpress account when I did the test, and that user is in english.  I tried from another browser and it work well.  Sorry about that.
