### ISSUE TITLE
Leaflet not showing correct // Placeholder #_MAP

### ISSUE THREAD

**Issue by FoxFoxCode** [liedekef/events-made-easy#103]
Hey Franky.

I noticed only now that probably after installing update 2.3.56 the leaflet as a map using placeholder #_MAP is no longer displayed or not correctly displayed ? In Chrome I've found out in the developer console that by disabling the CSS element:
".leaflet-container {overflow: hidden;}"
the leaflet is displayed again, but then does not integrate properly into the layout.
e.g. this site:
[https://kunstflug.agathazell.info/events/sc-uelzen-2023/](url)

Thanks a lot.
Regards.
Felix

**Comment by liedekef** [comment]
Please check your CSS: in your custom eme.css *and* the main eme.css you've put .eme-location-map in comment.
Even more: you've completely replaced the plugin eme.css with your own ...
