### ISSUE TITLE
Hidden Mandatory Fields

### ISSUE THREAD

**Issue by blanch80** [liedekef/events-made-easy#104]
Hi,

We've got a book form setup that will only show a field if a WordPress users role is evaluated in an if statement.

`[eme_if2 tag='#_USER_HAS_ROLE{#_ATT{role}}' value='1']
#_SEATS
<table class="eme-rsvp-form">
<tbody>
<tr>
<th scope="row">First Name*:</th>
<td>#REQ_FIRSTNAME</td>
</tr>
<tr>
<th scope="row">Last Name*:</th>
<td>#_LASTNAME</td>
</tr>
<tr>
<th scope="row">E-Mail*:</th>
<td>#_EMAIL</td>
</tr>
</tbody>
</table>
[eme_if3 tag='#_USER_HAS_ROLE{#_ATT{check}}' value='1']
<table class="eme-rsvp-form">
<tbody>
<tr>
<th scope="row">Area*:</th>
<td>#REQ_FIELD{Condition 2}</td>
</tr>
</tbody>
</table>
[/eme_if3]
#_SUBMIT
[/eme_if2]
[eme_if tag='#_USER_HAS_ROLE{#_ATT{role}}' value='0']<strong>You are unable to book a place on this event. If you would like more details, please contact us with your own, and your organisation details.</strong>[/eme_if]`

We enter the role values as attributes in the event. 

Person 1 logs in, has the right role and can see the first table in the eme_if2 tag.
Person 2 logs in, has the right role and can see both tables in the eme_if2 and eme_if3 tags.

The problem is, person 1 can't submit the booking form as the field that is only shown in the eme_if3 tag is mandatory.

Just wondering if there is any way round this?

Cheers,
David.

**Comment by liedekef** [comment]
See the option "Check required fields upon submit?" in the section "RSVP: registrations and bookings".
