### ISSUE TITLE
Emails sender name and Reply-To

### ISSUE THREAD

**Issue by jantoni** [liedekef/events-made-easy#117]
All outgoing emails are sent under the name of the event contact person. In the plugin settings, a name for all emails and an email address have been activated, but the name of the contact person always appears in all emails.

The email address of the event contact person also appears in the Reply-To field of the email headers.

Email headers:

de:	Malonsofe <webmaster@bkia.es>
responder a:	Malonsofe <xxxxxxxxx@hotmail.com>
para:	ea4dqx@gmail.com
fecha:	23 mar 2023, 0:53
asunto:	Reserva confirmada para '26-4-2023 11:00 Museo Arqueológico Nacional: Edad Media: Visigodos y Al-Andalus'
enviado por:	eu-west-3.amazonses.com
firmado por:	bkia.es
seguridad:	 Cifrado estándar (TLS) [Más información](https://support.google.com/mail?hl=es&p=tls)

in the field (from) should appear "Carpe Diem Event Manager" and not Malosonfe (the event contact person name)

**Comment by liedekef** [comment]
Which settings did you set concerning this in the EME settings? In order to force the from, you need to activate the option "Force sender address everywhere":
![image](https://user-images.githubusercontent.com/75667/227147491-e79e8b57-7f05-4226-b25d-dbe24c18a9f0.png)

**Comment by jantoni** [comment]
Yes, the option "Force sender address everywhere" is activated.

<img width="323" alt="Captura de pantalla 2023-03-23 094129" src="https://user-images.githubusercontent.com/10770143/227149185-8153df42-01ed-43bb-923b-b8a316000546.png">

The issue was detected when updated from 2.3.18 to 2.3.56 (full zip)

**Comment by liedekef** [comment]
Ok, so your problem is not with the "From" but the reply-to
The name can be different: if your event also has webmaster@bkia.es as contact person but with a different name, that name is taken. That means that your wordpress user has a different name but the same email as your settings here (and in that case I don't touch the name).
The reply-to I can accept and fix.

**Comment by liedekef** [comment]
See this change: https://github.com/liedekef/events-made-easy/commit/807c241bdc580981b739f1ab5b4f30454265d91c
And I also added a remark:
https://github.com/liedekef/events-made-easy/commit/f95476567de46aa98b1f22324903f9b0047d656d

**Comment by liedekef** [comment]
Wait, upon queueing I also set the name ... let me check that too

**Comment by jantoni** [comment]
I have not a test site, sorry

**Comment by liedekef** [comment]
I can take a look on your prod-site (and not change anything of course) ...
