### ISSUE TITLE
#_LOCATIONIMAGETHUMB no longer shows anything

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#122]
my events list use a format with It no longer shows anything. instead of the image I have the placeholder

**To Reproduce**
see here https://vogue-et-reve.fr/planning/

**Expected behavior**
the picture instead #_LOCATIONIMAGETHUMB

I use the last version of EME just updated

**Comment by liedekef** [comment]
Please check if this fixes it:
https://github.com/liedekef/events-made-easy/commit/e8a8466240b985a12108b39c0288d47400280b82

**Comment by f14m07** [comment]
Yes that fixes it. I have an other bug in the same format list : 
[eme_if tag='#_IS_USER_MEMBER_OF{Adherents}' value='1'] par #_ATTENDEES [/eme_if]
this shotcode does not work. #_ATTENDEES is not listed

**Comment by f14m07** [comment]
I have an other bug with the placeholder #_ADDBOOKINGFORM that shows nothing

**Comment by liedekef** [comment]
#_ATTENDEES only work inside a single event format, and the booking form placeholder also works fine. When reporting, please explain where/how you use these.

**Comment by f14m07** [comment]
I use #_ATTENDEES inside a single event format, and it works fine before

**Comment by f14m07** [comment]
I have given you admin right

**Comment by liedekef** [comment]
Your planning page use eme_events with template id 4. That template is not using #_ATTENDEES or eme_if at all.
And I checked event id 497 (Croisière-entraînement sur Horatio, étape 2/8), the single event format there (which is empty, so it uses the default from the EME settings) does not contain the  #_ADDBOOKINGFORM placeholder.

**Comment by f14m07** [comment]
Yes because you are not login. If you log in the template change and you have what i said

**Comment by f14m07** [comment]
the link is then https://vogue-et-reve.fr/reservations-navigations/

**Comment by f14m07** [comment]
with the previous version 2.3.58 it all works

**Comment by liedekef** [comment]
ok, the prob is not with #_ATTENDEES, but with the IS_USER_MEMBER_OF etc ... 
I've the fix ready, I'll release a new version

**Comment by f14m07** [comment]
Thanks a lot Franky, all is fine now

**Comment by liedekef** [comment]
Update released, please test that.

**Comment by f14m07** [comment]
yes test is positif
