### ISSUE TITLE
#_IS_USER_IN_GROUP{AAA,BBB} with multiple Groups is bugged

### ISSUE THREAD

**Issue by MichaelWybo** [liedekef/events-made-easy#128]
**Describe the bug**
Made the update from 2.3.58 to 2.3.60 and my eme_if whith #_IS_USER_IN_GROUP with more than 1 group are broken

Back to 2.3.58 and OK again, update to .59 and still OK, update to .60 and broken

![EEME2 3 58](https://user-images.githubusercontent.com/32988994/228552355-a4ef8603-ea9f-482b-8e7e-6309713e03eb.png)

![EME2 3 60](https://user-images.githubusercontent.com/32988994/228552347-11106d23-1dae-4cfc-afda-4bf5a0491442.png)

**Comment by liedekef** [comment]
indeed, I check for characters in the name (which I did in the past too, but not everywhere so that was introduced for more shortcodes). I'll check these again

**Comment by liedekef** [comment]
This should fix it:
https://github.com/liedekef/events-made-easy/commit/05cb9e2966b1c6186f12036fbb804e208aaf3362
