### ISSUE TITLE
changing header in the event page

### ISSUE THREAD

**Issue by DavidLaflamme01** [liedekef/events-made-easy#131]
hi I would like to know how to change the header on the event page. I did  a loom video to help you to understand the problem.
https://www.loom.com/share/b57e13aa46194d7ab26ec00a950c152d

**Comment by liedekef** [comment]
From the doc at https://www.e-dynamics.be/wordpress/category/documentation/3-installation-and-usage/
"_To render events (after creating events in the EME admin section, see next chapter), just create normal regular WordPress pages and use any available EME shortcode (see other part of this doc for all available shortcodes with their options and examples) to render events, locations, … any way you like it.
To be clear: events are not posts, the “special” events page defined in the settings is used to render events and everything else. The reason for this page is to have a link that can be sent for e.g. payments (I need a page to show …) or single events, etc …_"

Now, you can change the layout of the special events page (like you would do with any other page, but from within the backend), or if you want to change the layout per event, assign a WP page template to that event:
![image](https://user-images.githubusercontent.com/75667/229375908-69733bd2-fe57-4794-87de-3a315fff9fc8.png)
