### ISSUE TITLE
arrow to go on another page

### ISSUE THREAD

**Issue by DavidLaflamme01** [liedekef/events-made-easy#135]
Hello I have some problem to put at the center at the bottom of my website the arrow to see more events. what is the best way to use the arrow to be responsive on mobile tablette and desktop. the arrow are not in the same line and not at the bottom of the page and I dont see the arrow at all on tablet

https://lespalmes.davidlaflamme.ca/evenements/
![arrow](https://user-images.githubusercontent.com/93485960/229544164-5f68c7bf-ad26-4fee-8e24-c5d671155f23.png)

thank you

**Comment by liedekef** [comment]
This is a CSS question, and that you should resolve by using a CSS editor :-) I add a class around it, but for the rest it is up to you to style to your liking ...
