### ISSUE TITLE
Limit user by category or something like this

### ISSUE THREAD

**Issue by tiicaa** [liedekef/events-made-easy#141]
I need to create 1 event with 3 different time options.
As a rule: Each duly logged in user will be able to choose only one time slot at a time within this event, not being able to choose another.
Another situation that would be necessary for me would be the event being created with different times for the same day, but when the user chooses a time, that specific time should be blocked for the others as a kind of limitation of vacancies, or even being able to launch separate events with limited spaces to solve this second situation, but the user would not be able to register for any other event of the same category. Any solution for both situations?

**Comment by liedekef** [comment]
You can write your own evaluation filter, where you check at the moment of form submit if the person already checked in for the other 2 events, see the filter eme_eval_booking_form_post_filter at https://www.e-dynamics.be/wordpress/category/documentation/12-hooks-and-filters/
The next version will also have some to help you using a conditional placeholder. From the changelog:
* Add placeholder #_HAS_USER_REGISTERED{xx} (with 'xx' being one or more event ids, seperated by comma) returns 1 if the current logged in user is registered for one of the mentioned events

Meaning you can then checl for the value of #_HAS_USER_REGISTERED{a,b,c} (using [eme_if]) and if it is "1", the user already registered.

**Comment by tiicaa** [comment]
@liedekef  I'm sorry I sent you in different places, it's just that every page that was dropped about your plugin had to be opened in those places. I apologize for that. I thought you could show me a more practical solution, I don't know how to do what you are telling me. I have your plugin installed, which by the way I found very simple and I liked working with it, but I imagined that there was some configuration that I missed to solve my problem, or some snipped ready but what you are telling me I do not know how to do.

**Comment by tiicaa** [comment]
I have tested something like this but without success, as I said I don't know how to apply what you explained.

`add_filter('eme_bookings_validate_checkin_form', 'prevent_multiple_checkins', 10, 4);

function prevent_multiple_checkins($errors, $booking_data, $event_id, $person_id) {
    $booking = eme_get_booking($person_id, $event_id);
    if ($booking) {
        $member = eme_get_member_by_personid_membershipid($booking['person_id'], $booking['membership_id']);
        $member_answers = eme_get_member_answers_all($member['memberid']);
        foreach ($member_answers as $answer) {
            if ($answer['question_id'] == 'checkin' && $answer['answer']) {
                $errors[] = 'You have already checked in to this event.';
                break;
            }
        }
    }
    return $errors;
}
`

**Comment by liedekef** [comment]
On https://www.e-dynamics.be/wordpress/category/documentation/12-hooks-and-filters/ there's an example of eme_eval_booking_form_post_filter . The code you have posted used a filter that doesn't exist, so it will never work.
A basic untested example could be (the relevant event ids are 5, 7 and 10):

```
add_filter('eme_eval_booking_form_post_filter','do_my_stuff');
function do_my_stuff($event) {
    $already_registered=0;

   // we care about events 5, 7 and 10
   $event_ids = array(5,7,10);
   $booker = eme_get_person_by_post();
   if (!empty($booker)) {
       foreach ($attendees as $attendee) {
             if (!empty(eme_get_booking_ids_by_person_event_id($booker['person_id'], $event_id)))
                $already_registered=1;
       }
   }

    if (!$already_registered) {
       // eval is success
       return array(0=>1,1=>'');
       // or just use return, is ok too
       // return;
    } else {
       // bad form entry
       return array(0=>0,1=>'Already registered');
    }
}
```

If you don't know how to code this or where to put this, I refer you to https://www.e-dynamics.be/wordpress/category/documentation/12-hooks-and-filters/ (read the beginning then).

**Comment by tiicaa** [comment]
@liedekef For me this code didn't work, but it helped me a lot to make another one that did:

```
add_filter('eme_eval_booking_form_post_filter','do_my_stuff');
function do_my_stuff($event) {
    $already_registered = false;
    $event_ids = array(4, 5, 6);

    // get the current user
    $booker = eme_get_person_by_post();

    if (!empty($booker)) {
        // check if the user has already registered for one of the events
        foreach ($event_ids as $event_id) {
            if (!empty(eme_get_booking_ids_by_person_event_id($booker['person_id'], $event_id))) {
                $already_registered = true;
                break;
            }
        }

        // check if the event is in the allowed event IDs
        if (in_array($event['event_id'], $event_ids)) {
            // if the user has already registered for one of the events, show an error message
            if ($already_registered) {
                return array(0 => 0, 1 => 'Already registered for one of the events');
            }
        }
    }

    // if the user has not registered for any of the events, allow the registration
    return array(0 => 1, 1 => '');
}
```
With these changes, the user should be able to register for events with IDs other than 4, 5 and 6, as long as he has not previously registered for one of the allowed events. Now I want to go a little further, working with event ids will get me stuck in the code because every time I generate a new event I need to see if I need to insert the id in the code, this would get a little exhausting, but it is still a solution. For me it would help to do the same limit but now per category, and I couldn't evolve on that ....

**Comment by tiicaa** [comment]
This code should check the categories of the current event and see if the user has already registered for an event in one of the same categories. If he has, then the booking is not allowed and an error message is returned. Otherwise the booking is allowed. i.e.: The code should prevent the user from registering for 2 or more events of the same category, he can only register once for events of different categories

```
add_filter('eme_booking_form_post_filter','prevent_duplicate_category_registration', 10, 3);

function prevent_duplicate_category_registration($booking, $event_id, $person_id) {
    // get the categories for the event
    $event_categories = eme_get_event_categories($event_id);

    // get all bookings for this person
    $bookings = eme_get_bookings(array('person_id' => $person_id));

    // loop through the bookings and check if they are in the same category
    foreach ($bookings as $existing_booking) {
        $existing_event_id = $existing_booking['event_id'];
        $existing_categories = eme_get_event_categories($existing_event_id);

        if (array_intersect($event_categories, $existing_categories)) {
            // if the event is in the same category as an existing booking, prevent booking and return error message
            return array(0 => 0, 1 => 'Você já está registrado para um evento nesta categoria');
        }
    }

    // allow booking if the person has no bookings in the same category
    return array(0 => 1, 1 => '');
}
```
I tried but it didn't work, the user can still register for more than 1 event of the same category. Could you help me with this?

**Comment by liedekef** [comment]
Like I alreaady said: eme_booking_form_post_filter is not a valid filter. I don't know where you got that info from, but it will never work. It is eme_eval_booking_form_post_filter, and you just can't add random arguments to it and hope it works ... See my example above to get the person info when submitting the form ($booker = eme_get_person_by_post();)
Also, eme_get_bookings doesn't exist. See my use of eme_get_booking_ids_by_person_event_id above to have something. That needs the event id too, so if you first want a list of events belonging to a certain category (or multiple, seperated by comma, use: eme_get_events("category=1,2,5"). If you want a complete list of bookings for a specific person, there's currently not a function for that, in the dev-version I just added the new function eme_get_bookings_by_person_id

**Comment by liedekef** [comment]
EME has only 1 timeslot per event. So if you want to block registration for other events, you need to use eme_eval_booking_form_post_filter , as I already explained above. Although there's a typo in it, this should be better:
```
add_filter('eme_eval_booking_form_post_filter','do_my_stuff');
function do_my_stuff($event) {
    $already_registered=0;

   // we care about events 5, 7 and 10
   $event_ids = array(5,7,10);
   $booker = eme_get_person_by_post();
   if (!empty($booker)) {
       foreach ($event_ids as $event_id) {
             if (!empty(eme_get_booking_ids_by_person_event_id($booker['person_id'], $event_id)))
                $already_registered=1;
       }
   }

    if (!$already_registered) {
       // eval is success
       return array(0=>1,1=>'');
       // or just use return, is ok too
       // return;
    } else {
       // bad form entry
       return array(0=>0,1=>'Already registered');
    }
}
```

**Comment by tiicaa** [comment]
Pelos ids dos eventos eu já consegui pelo código que postei mais acima, porém eu gostaria de deixar mais automatizado isso o que eu estava tentando o código para categoria OU nome do evento OU localidade:
_Lógica:_ quero impedir que o usuário se cadastre em eventos que tenham o mesmo nome, eles também compartilham a mesma localidade e categoria, mas com datas e ids diferentes. 
Fiz o código abaixo mas claro sem sucesso
```
add_filter('eme_eval_booking_form_post_filter','do_my_stuff');
function do_my_stuff($event) {
    $already_registered = 0;
    
    // Define a categoria dos eventos que serão verificados
    $event_category = 'Category A';
    
    // Obtém o ID da pessoa que está fazendo a reserva
    $booker = eme_get_person_by_post();
    
    if (!empty($booker)) {
        // Obtém todas as reservas da pessoa em questão
        $bookings = eme_get_bookings_by_person($booker['person_id']);
        
        foreach ($bookings as $booking) {
            // Verifica se a reserva é de um evento na categoria definida
            if (eme_get_event_category($booking['event_id']) == $event_category) {
                $already_registered = 1;
                break;
            }
        }
    }

    if (!$already_registered) {
        // A pessoa não está registrada em nenhum evento da categoria definida
        return array(0=>1,1=>'');
    } else {
        // A pessoa já está registrada em pelo menos um evento da categoria definida
        return array(0=>0,1=>'Já existe uma reserva para essa pessoa nessa categoria de evento');
    }
}


```

**Comment by tiicaa** [comment]
Damn man, it's a shame that your plugin doesn't have a solution in the settings to limit one registration per category or even some time limit, for example the user registered and could only make another registration after x hours or days. I tried for 3 weeks some scripting but I couldn't get the model I need. the most I did and that worked until today was to limit certain IDs and events per record, but as I said earlier it works but it's not exactly what I need. I feel like I'll have to look for another solution in maybe another plugin for this. Anyway, thank you for taking the time to answer my questions. Thanks

**Comment by liedekef** [comment]
I gave you the code snippets and function calls needed to be able to filter on categories and check for other bookings during the booking. eme_eval_booking_form_post_filter is the one to use and can check just about everything, but while I give support on the plugin, custom code/snippets are not provided (I can't just go around and solve everybody's problem for them). Either you play around yourself or you pay a dev-guy (or me) for coding.
But as always: feel free to check out other plugins, maybe indeed one is able to do what you want.
