### ISSUE TITLE
Layout 

### ISSUE THREAD

**Issue by DavidLaflamme** [liedekef/events-made-easy#146]
how to take more width on the page and less margin

And I have a problem when i want to edit my events

I never created an events with Rémy Langlois who start at 16h39 and its break my layout when i want to edit so I would like to take this one out to have only my events starting at 18h30.
You can look at my loom video to understand the problem

https://www.loom.com/share/e8f945cddb05448a9a9bc1f2286c086d

to see in backend my events 
https://www.loom.com/share/c5c5b3d8fec54968ac37bccefba9095d

**Comment by liedekef** [comment]
EME follows the CSS and layout of your page template, so check your theme and CSS. Like explained at https://www.e-dynamics.be/wordpress/category/documentation/9-changing-the-layout-css/ : "CSS is something you should learn to master, using a CSS-debugger like Firebug also helps (in firefox). Learn CSS [here](http://www.w3schools.com/css/) . Before asking support on CSS, please do try it yourself and/or ask the theme maker for hints, they are the CSS experts and know best how their theme is working and can provide hints on how to change things."
Also, EME doesn't invent hours, so I'm not sure what you are asking about the hour there, but you need to check the content of your page then.
