### ISSUE TITLE
Latest release troubles

### ISSUE THREAD

**Issue by Diero** [liedekef/events-made-easy#15]
**Describe the bug**
Hey Franky, today i installed the new release from github (latest installed version on my system was 2.3.10 (now it is 2.3.38.). After a perfect install via upload new plugin everything went great but when i try to see my 'old' of 'future' events in the backend  i get an error 
![image](https://user-images.githubusercontent.com/3635882/212477543-a8d62f53-3eff-479b-a117-a75bb5142fe1.png)

Frontend still shows the events in the future.

the problem is a 403 error in wp-admin/admin-ajax.php action=eme_events_list&trash=undefined&jtStartIndex=0&jtPageSize=25 (the response is -1)
 
**To Reproduce**
1. Go to 'admin.php?page=eme-manager'

**Expected behavior**
See all future events

**Comment by liedekef** [comment]
Let me check this ...

**Comment by liedekef** [comment]
I can't reproduce this issue.
Can you (via your browser console) see what EME returns when loading the data for the table? 
Also: anything in the logs? PHP and wordpress version? And did you try to clear your cache to be sure it not related to that?
And: feel free to send me a mail with temporary admin credentials so I can check what is going on.

**Comment by liedekef** [comment]
Btw: I believe it is a caching issue, because the link you mention doesn't contain a "nonce". The table ajax call is something like:
`wp-admin/admin-ajax.php?action=eme_events_list&eme_admin_nonce=97abaf66d4&trash=undefined&jtStartIndex=0&jtPageSize=25`

**Comment by Diero** [comment]
Hey Franky, you were right, it was a caching problem. Sorry to waste your time!
