### ISSUE TITLE
Malformed output of [eme_events] with custom template

### ISSUE THREAD

**Issue by bdrpl** [liedekef/events-made-easy#151]
**Describe the bug**
I've made a custom templates for [eme_events] code is here based on tables. Generated page contais number of `<br>` tags between heading and start of the table.

**To Reproduce**
1. Create templates:
header:
`<table><tbody>`
body:
`<tr><td><a href="#_EVENTPAGEURL"><img src="#_EVENTIMAGEURL" width=100px /></a></td><td>#_LINKEDNAME</td><td>#_STARTDATE - #_ENDDATE</td><td>#_AVAILABLESEATS/#_TOTALSEATS</td></tr>`
footer:
`</tbody></table>`
3. create emty page and place the shortcode:
`[eme_events  scope=today--future template_id_header=[header id] template_id=[body id] template_id_footer=[footer id]`
5. save a page and navigate to it
7. See error - between begining of the table and previous elemnt you'll see number of <br> tags and page will be malformed (table shifted to the bottom of page)

**Expected behavior**
No additional `<br>` tags before `<table>` element

**Online Demo**
here you can see the output:
https://www.idea4pro.com/szkolenia-mikrotik-ubiquiti/kalendarz-szkolen/

best regards,
Bartek

**Comment by bdrpl** [comment]
OK. It seems first I had "Convert newlines" set to Yes. When I saw malformed output I set it to No, but apparently output doesn't update.

Once I removed all newlines from the body part it looks like expected. I think change of this option should update the template and remove all the <br>,

**Comment by liedekef** [comment]
Normally EME doesn't add a br-tag after a closing html-tag (I just tested that too with my code too), even if newlines are present. If deselecting the option "Convert newlines", EME doesn't do anything to add own br-tags anymore ... at least not where I see it. I'll test your example later on.

**Comment by liedekef** [comment]
It is more complicated in fact ... based on current code, it is best that I totally remove that option.
