### ISSUE TITLE
Event has zer0 as price but not show through placeholder on site

### ISSUE THREAD

**Issue by wslybkkr** [liedekef/events-made-easy#157]
Hi,

We have created multiple events where the pricing is zero (free for members), in the backend the price is on zero and shows in backend in overview as Free (Gratis). But when using the placeholders on our website voor #_Eventprice it does not show Free (gratis), it shows nothing. All other events with a pricing are shown with this placeholder. Can you eleborate what is wrong?

![Schermafbeelding 2023-04-21 131528](https://user-images.githubusercontent.com/17185344/233622723-bd1a0aa9-57f8-47f1-8cec-9f13fac0d34f.png)
![Schermafbeelding 2023-04-21 131505](https://user-images.githubusercontent.com/17185344/233622726-23be6956-859a-4bf0-a919-787ea1baecd5.png)
![Schermafbeelding 2023-04-21 131455](https://user-images.githubusercontent.com/17185344/233622727-97f3e6f5-ea6c-49f3-a54a-4aa9843b20a8.png)
![Schermafbeelding 2023-04-21 131433](https://user-images.githubusercontent.com/17185344/233622729-333cdcd0-cd07-4c65-97e2-f70604577581.png)

**Comment by liedekef** [comment]
In the backend it is shown as "free" to have a better user experience.
In the frontend the #_EVENTPRICE is empty if the price is 0. If you want to show anything else, you should use [eme_if] to check for the value and if 0, show a text of choice.
