### ISSUE TITLE
Recaptcha required although not required

### ISSUE THREAD

**Issue by BudoAsahi** [liedekef/events-made-easy#16]
Hi Franky,
In the RSVP of online events we're suddenly getting a Recaptcha warning ("vink aub het Google recaptcha aan") when someone wants to place the booking. But for these events/forms I never used recaptcha. I do however use it in another form so I don't want to completely disable it.
Bug or is it something I never used correct before?
Gr. Dionne

**Comment by liedekef** [comment]
What are your per-event settings for that captcha (for the event where you don't want the recaptcha) ?
You need to (can) disable the recaptcha per event, but if recaptcha is configured it is by default "on" for all forms (so also for new events).

**Comment by liedekef** [comment]
Confirmed as a bug, this should fix it:
https://github.com/liedekef/events-made-easy/commit/c51b21167099a3e90e20527e8fcd0ee1b107b49d

I'll release later on today.
