### ISSUE TITLE
eme_printable_table

### ISSUE THREAD

**Issue by WXQ8NPb5TrbDNqzywcxF** [liedekef/events-made-easy#163]
Hi,

In the booking_printable page,  the class of th for "fist name" and "last name" of the table eme_printable_table are the same.
Is it possible to have a unique class name for fistname and lastname ?

```
<table id="eme_printable_table">
  <tr>
    <th scope='col' class='eme_print_id'>
      ID			</th>
    <th scope='col' class='eme_print_name'>
      Last name			</th>
    <th scope='col' class='eme_print_name'>
      First name			</th>
```

Because if i want to apply a specific css to "First Name", i'm not able.

Thanks !

**Comment by liedekef** [comment]
You can use css selectors: https://www.w3schools.com/CSSref/sel_first-of-type.php

**Comment by liedekef** [comment]
But, to help you along, this will be in the next version:
https://github.com/liedekef/events-made-easy/commit/9c02ced5757f3d297ec0e1d3cdc4a03171d7a2d8
