### ISSUE TITLE
Extra event html headers broken in new version 2.3.66

### ISSUE THREAD

**Issue by TimB111** [liedekef/events-made-easy#171]
When entering meta tags in the Extra event html headers box in EME > Settings > Other and then saving, the meta tags are removed, and any other headers are wrongly written to the top of the live page.

**Comment by liedekef** [comment]
Did you first allow the meta-tag in "Extra html tags" ?
While you can consider this a pain in the ** , it is (was) wordpress requiring this. But since the plugin is no longer on wordpress, I might reconsider this again and at least allow style and meta by default.

**Comment by liedekef** [comment]
This is that change:
https://github.com/liedekef/events-made-easy/commit/8dcc80610fe9b5ae4fb00c05817d64a16d304c99

**Comment by TimB111** [comment]
> Did you first allow the meta-tag in "Extra html tags" ? While you can consider this a pain in the ** , it is (was) wordpress requiring this. But since the plugin is no longer on wordpress, I might reconsider this again and at least allow style and meta by default.

Ah sorry I didn't realise I had to add in the specific tags.
