### ISSUE TITLE
Issue after updating to MySQL 8.0

### ISSUE THREAD

**Issue by blanch80** [liedekef/events-made-easy#178]
We upgraded our server to MySQL 8.0 last night, from MySQL 5.7 and experienced an issue after the upgrade, ended up rolling the server back.

When loading the upcoming events page with the shortcode: [eme_events limit=0 notcategory=21 scope="future"] we just got the spinning circle of doom on the browser and it ended up with a 504 error. The odd thing is this only happened when the user was logged in. If we hit that page without being logged in it loaded as quick as I've seen it.

There was probably 175 events listed on the page. When running on MySQL 5.7 the page loads as expected with no problems.

We have another page with the same shortcode but it's limited to two categories [eme_events limit=0 category=29,30 scope="future"]. The same thing happened when accessing the page when no user was logged in, the page loaded very quickly. When loading this page when logged in it did load eventually but took over 15 seconds. This lead us to believe that the main list of all events wasn't loading as there were too many in the list and a page with a smaller number of events does load but slowly - but we can't understand why this is only an issue when a user is logged in.

We tried three different user logins with different roles, the same thing happened for each.

An individual event page with a booking form loads as expected.

The other very unusual thing is that we got a similar issue when trying to edit the page from the WordPress dashboard. We could edit any other page with no problem, but when trying to edit the upcoming events page we got the 504 error again. We tried creating a new page, adding the shortcode and the same thing happened.

It worked fine in our test environment but we only had two events listed in there.

**To Reproduce**
I'm unable to show you the error as we had to roll the server back, but it was simply loading the page with that shortcode ended up with a 504 error when trying to load all events.

**Expected behavior**
To load the page with all events as usual, as it does when running MySQL 5.4

**Additional context**
The gut feeling based on the testing we did is that there is some recursive code that it checking time and time again whether the event needs to be listed on the page with that shortcode or not.

We do have some WordPress role based checks that happen on the booking forms but when loading an individual event, whether logged in or logged out, the individual event always loaded with no problem.

Hope you can help with this, this might affect others in the future when migrating to MySQL 8.x

Thanks,
David

**Comment by liedekef** [comment]
It seems more like a protected column name in mysql 8, that was not present in older mysql versions. In your error logs it should mention something like that. However, I'm running mariadb on several servers (latest versions) without issues.
So: which version of EME are you using? And: check the network return in your browser console when something happens again (and your php error logfiles).

**Comment by blanch80** [comment]
Thanks Franky. We're on EME 2.3.64. I'll see if I can grab the php error log files from last night, we'll need to schedule in an upgrade of the server soon to do the troubleshooting you've suggested.

**Comment by liedekef** [comment]
Btw: with "protected" I mean "reserved". But from the doc I have no issues there, so: when upgrading, activate mysql sql-logging so you can see which queries are executed (maybe only for queries that fail, if that's possible). Then that might give a hint too

**Comment by blanch80** [comment]
We checked the PHP errors and nothing major appeared, there were some deprecated notices but no errors. Couldn't see an issue in the browser console either, other than it took an age to load.

We're gonna try again and do some more troubleshooting.

**Comment by liedekef** [comment]
Hum ... If all events are showing maybe it is not EME related?
Slow query log in MySQL might help, or timing all queries for the duration of debugging.
