### ISSUE TITLE
Previous month not showing on paging

### ISSUE THREAD

**Issue by blanch80** [liedekef/events-made-easy#179]
**Describe the bug**
We have two shortcodes on a page:
[eme_filterform category=1,18,29,30,34,36,35,33,38,32,40 submit="Filter"]
[eme_events limit=0 scope=this_month paging=1]

Next month appears and works, but when moving to the next month the option to go back to the previous month doesn't appear. Removing the filter doesn't make a difference.

**To Reproduce**
1. Go to (https://learning.necsu.nhs.uk/events-test/)
2. Click on Next month
3. Previous month isn't available as an option to navigate backwards

**Expected behavior**
Should see a Previous month link to move backwards in the events list

**Comment by liedekef** [comment]
I think paging works as long as there are events to show. Is it possible that the current month has no events?
I will try here too.

**Comment by liedekef** [comment]
Can you check via mysql the output from this sql:
`
SELECT wp_eme_events.*,wp_eme_locations.location_name,wp_eme_locations.location_address1,wp_eme_locations.location_address2,wp_eme_locations.location_zip,wp_eme_locations.location_city,wp_eme_locations.location_state,wp_eme_locations.location_country,wp_eme_locations.location_latitude,wp_eme_locations.location_longitude,wp_eme_locations.location_attributes,wp_eme_locations.location_properties FROM wp_eme_events LEFT JOIN wp_eme_locations ON wp_eme_events.location_id=wp_eme_locations.location_id WHERE event_status IN (1,2) AND (event_start < '2023-06-01') ORDER BY event_start ASC, event_name ASC LIMIT 1 
`

Maybe the date comparision at the end is causing an issue ?

**Comment by liedekef** [comment]
Btw, this is the trivial fix: https://github.com/liedekef/events-made-easy/commit/b885cf5e076693917857ea1812192a6f7e7d6d44

**Comment by blanch80** [comment]
Hi - this doesn't seem to have worked. There are definitely events listed in the month as I've moved from May to June but am unable to move back to May where there are 15-20 events listed.

I've run that query and it is bringing back one event from 2019?

![image](https://github.com/liedekef/events-made-easy/assets/123082349/67ee0953-9293-4673-9587-dab9a10f07d0)

**Comment by liedekef** [comment]
1 event only? Can you do some other queries to play with "WHERE event_status IN (1,2) AND (event_start < '2023-06-01 00:00:00')" ? Can it be some indexing is broken on your DB? Are the other events in the correct status (either 1 or 2)? And what if you leave out "event_status IN (1,2)" ?

**Comment by liedekef** [comment]
Also, try this query: "SELECT count(*) from wp_eme_events where event_status IN (1,2) AND (event_start < '2023-06-01 00:00:00')"

**Comment by blanch80** [comment]
Yeah - took me by surprise. I've tried the query in the last update you put on and got a count of 3277.

That first query had LIMIT 1 on the end, taking that off brought back the same result as the other query.

**Comment by liedekef** [comment]
Hum .. that would mean the previous mo the link should show up ...

**Comment by liedekef** [comment]
No further feedback, so closing for now
