### ISSUE TITLE
Old emails being re-sent when WordPress is updated

### ISSUE THREAD

**Issue by MayaHM1** [liedekef/events-made-easy#181]
I have a website that I stopped using last year. A few days ago on 16th May, WordPress updated itself to version 5.9.6 and Events Made Easy (version 2.2.99) sent out payment received emails from an event I ran in April 2021, followed by a few emails on 17 May, 18 May and 19 May. Then on 20 May, WordPress updated itself to version 5.9.7 and sent out payment received emails from event I ran in April and May 2021, and again today.

I wanted to be sure that these emails were coming from Events Made Easy and not somewhere else and on the Email Management page it shows 21 emails that were queued and sent from 16-23 May 2023. These are all booking paid emails. There are no booking pending emails.

Today I was contacted by a couple of guests of those events who are wondering why this is happening 2 years later. I've had old emails sent out in the past and I seem to remember it happening around the same time as a WordPress update, but ignored it because nobody contacted me about them.

This is also happening with Events Made Easy on another website I stopped using a couple of years ago which is on version 2.2.88. This site also sent emails on 16/17/18/20/23 May, but no emails directly to guests, just admin emails.

Is there some way to fix this?

**Comment by liedekef** [comment]
Your wordpress is outdated and next to that EME is as well. Update both to the latest version. For EME, read the installation section for existing wordpress users here:
https://github.com/liedekef/events-made-easy

**Comment by MayaHM1** [comment]
I've updated WordPress and Events Made Easy on both sites.

Was this a bug that was previously fixed?

**Comment by liedekef** [comment]
I remember someone saying something similar in the past, but can't recall it nor find specific github commits on this.
Anyway, bugs should be filed against the latest version :-)
