### ISSUE TITLE
Redirect to payment page stopped working

### ISSUE THREAD

**Issue by markrdavidson** [liedekef/events-made-easy#183]
Hi Frankie,

I've been using v 2.3.50 for a while, but just discovered that after the "Booking recorded message" is displayed, the redirect to the payment page is no longer successful.  There's no error message -- it just sits at the booking recorded message.

Any suggestions for me on where to look?  (There is nothing in the browser console.)  Or perhaps I just need to update to the latest EME?

Also, is there a way to make the redirect faster... or immediate?

Thanks,
Mark

**Comment by markrdavidson** [comment]
I have ALSO just discovered that the payment link in the email is not right!  I don't understand this at all... the template uses

- <a href="#_PAYMENT_URL">

but the link in the confirmation email is this in my email client:

- imap://mrdavidson%40intelliga%2Ecom@outlook.office365.com:993/fetch%3EUID%3E/INBOX%3E24758

...and missing altogether in Office365... which perhaps means Office365 is doing something awful, but JUST IN CASE you have seen this before and know of a fix, I'd be very happy for any guidance.

Thanks again

**Comment by liedekef** [comment]
Hi,
First indeed update to the latest version. Then check if you have automatic redirect to the payment page activated, and check the seconds configured for it 
Concerning your last issue: that's a weird outlook issue, IMAP/fetch is even a command to fetch a mail from an IMAP server/mailbox, so something is intervening there.

**Comment by markrdavidson** [comment]
I have updated the plugin, but I'm still experiencing the same issues.
https://www.brackdriving.com/registration-form/

I have "Redirect towards payment page?" set to Yes.
I have "Redirect wait period" set to 0.
Interestingly, I have "" set to

- < a href="#_PAYMENT_URL" style="color:white!important" >You will be redirected to the payment page in a few seconds, or click here to go there immediately< /a >.

...but the < a > and < /a > tags aren't rendered.

**Comment by liedekef** [comment]
I tried a registration and got an email with an empty url (causing the imap/... thingie apparently).
Can it be that you did not indicate which payment gateway to use for the event?

**Comment by markrdavidson** [comment]
Looking into the payment gateway ASAP... out of the office today, though.  Thank you for taking a look.

**Comment by liedekef** [comment]
no further feedback, closing

**Comment by markrdavidson** [comment]
I did *just* find that the payment method options weren't set for one event -- the one you tried.  I guess it's likely that that was the problem.  Thanks for your help!
