### ISSUE TITLE
Multiple persons in 1 booking

### ISSUE THREAD

**Issue by Wessiez** [liedekef/events-made-easy#184]
Goodday Frankie,

I'm building an bookingform for parents with children for a walking event.
Some families walk with 1 parent and 1 child. Other families walk with 2 parents and 3 childeren.

Now is created a custom field called "Medalls". There's a dropdown menu with extra charge set to yes
The field values are: [ 0 II 6 II 6 II etc]
The field tags are: [No medal II number 1 II number 2 II etc]. 
I think this should work for the price setting.

But how can I create something like a button to add an extra parent and extra children?
How would you solve this?

Best regards,
Larz

**Comment by liedekef** [comment]
Please read this:
https://github.com/liedekef/events-made-easy/discussions/85
