### ISSUE TITLE
Possible to add Cloudflare Turnstile ?

### ISSUE THREAD

**Issue by WXQ8NPb5TrbDNqzywcxF** [liedekef/events-made-easy#2]
Hi,  would like to know if it is possible to add support for Cloudflare Turnstile as Captcha Provider ?

**Comment by liedekef** [comment]
I think adding that is a five-minute job :-)

**Comment by liedekef** [comment]
This changeset implements it: https://github.com/liedekef/events-made-easy/commit/23a8bdc9374dd3eff7ae75ff6fbee0085eb0f5e3
It is rather big. Although the code to add captcha methods is easy to do, I should start changing the logic more to avoid duplicated code here too.

Feel free to test it out or wait for the next release.

**Comment by WXQ8NPb5TrbDNqzywcxF** [comment]
Thanks,  i'll certainly use it in the next release.

**Comment by WXQ8NPb5TrbDNqzywcxF** [comment]
Hi !
Seem to work pretty well,  only things I see for the moment is that the 2 fields for the config don't appear when we select "Yes",  have to save and refresh to make it appear.

Thanks you very much

**Comment by liedekef** [comment]
This should fix it (to test, you'll need to refresh your browser cache once):
https://github.com/liedekef/events-made-easy/commit/1f265f0fe4ccbd43acb259b3b73c261908cdd9c0

**Comment by liedekef** [comment]
2.3.33 is released (for another bug, but this fix is in it too)

**Comment by WXQ8NPb5TrbDNqzywcxF** [comment]
I'm sorry,  I made more tests within RSVP forms,  and i got a yellow error message when I submit the forms

**Comment by liedekef** [comment]
Please open a new bug report for this, describe the error and what you find in the logs. Also, be aware that I am not able to test this myself as it seems you need to be American for signing up (unless I am mistakes).

**Comment by liedekef** [comment]
While without reaction, I checked the code and found that I copied over a mistake from hCaptcha code (which I reworked to be more compliant with WP requirements). This should fix it:
https://github.com/liedekef/events-made-easy/commit/b8b90e45bfef841e1df035b1558796ca123f2fea

**Comment by liedekef** [comment]
This is now in the released version, so closing for now.
