### ISSUE TITLE
Removing queued mail

### ISSUE THREAD

**Issue by TommieNL** [liedekef/events-made-easy#210]
Hello Franky,

Question about the mail queue. I had to stop a certain mail from sending from the queue. 

The queue stated there were still mails to be processed. So i disabled my mail plugin and the EME plugin (hopefully i was fast enough). I've deleted the record from the database, under tabe `xxx_eme_mqueue`.

Do you think this should be enough?

Hoping to hear from you. 
Greets.

**Comment by liedekef** [comment]
If it is a mailing, you can cancel the mailing (tab "Mailings" in submenu "Email management"). If it is an individual mail, you can cancel that single mail (tab "Sent emails" in submenu "Email management" ==> despite the menu saying "Sent emails" it also contains all planned emails).
So no need to manually go in the DB

**Comment by TommieNL** [comment]
Thanks for the fast reply! And oh wow, didn't know that! 

Would the manual removal action I did be enough or should I still cancel the (individual) mail via the sent mail tab?

**Comment by liedekef** [comment]
Manual removal is also ok

**Comment by TommieNL** [comment]
Thanks!
