### ISSUE TITLE
PDF output translate Custom Field

### ISSUE THREAD

**Issue by MichaelWybo** [liedekef/events-made-easy#23]
**Describe the bug**
When I use the PDF Output, in the generated PDF file a custom field is translated
Database value: Sunday
PDF value: Dimanche

**Expected behavior**
Not translate custom field

**Screenshots**
Export data pdf : https://i.ibb.co/QX08CZ0/Sunday-1.png
PDF Output : https://i.ibb.co/hCskrzp/Sunday-2.png

**Comment by liedekef** [comment]
While it is not really considered as a bug, I understand the issue at hand.
This fixes it:
https://github.com/liedekef/events-made-easy/commit/4d46a6fa755aaa8148b1d38d7e830dcde5dde916
