### ISSUE TITLE
after updating to the latest version i cannot update our memberships to create the wp users

### ISSUE THREAD

**Issue by kdovale** [liedekef/events-made-easy#232]
open any membership and check the create wp-users, and save the page, then go back in and the setting is not saved. this therefore does not create the wordpress users and send them an email to change their password and access other content.

**Comment by kdovale** [comment]
after further investigation, i can give you further feedback. 
I edited the database directly and looked at the membership entries, if i set the recaptcha and create wp user, and then go look at the memberships i see the checkboxes are there and ticked. However if I save the membership and go back in they are removed. it looks like the save option is defaulting the form and not updating the DB.

**Comment by liedekef** [comment]
Confirmed and fixed in dev (but for wp user creation there was another bug too, that's also already fixed).
I'll release today.

**Comment by liedekef** [comment]
New version has been released
