### ISSUE TITLE
For 4 hour last automatic Update 2.37 - 2.4 critical error in wordpress 6.2 PHP 8.0

### ISSUE THREAD

**Issue by GerdSchwarz** [liedekef/events-made-easy#233]
**Describe the bug**

**To Reproduce**
2. Set '...' to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Online Demo**
While screenshots can say something, they don't say everything.
So, if possible, include a link to a demo page demonstrating the issue.

**Log output**
If applicable, check your php error logfile and add php errors here

**Additional context**

**Comment by liedekef** [comment]
This is not a valid bug report. No info has been provided at all.
Please for "critical errors", check your php error logfile and add php errors here. Either that or a full reproducable case.

**Comment by GerdSchwarz** [comment]
Sorry, here is a copy from error.log:

Fri Jul 14 21:02:39.823049 2023] [fcgid:warn] [pid 80778:tid 34407058432] [remote 87.146.86.213:52597] mod_fcgid: stderr: #29 {main}, referer: https://www.eldagsen.de/
[Fri Jul 14 21:02:39.823065 2023] [fcgid:warn] [pid 80778:tid 34407058432] [remote 87.146.86.213:52597] mod_fcgid: stderr: thrown in /usr/local/www/apache24/noexec/eldagsen.de/wp-content/plugins/events-made-easy/eme-widgets.php on line 66, referer: https://www.eldagsen.de/
PHP Warning: Module "openssl" is already loaded in Unknown on line 0
 [Fri Jul 14 21:02:49.131012 2023] [fcgid:warn] [pid 80780:tid 34411639808] [client 66.249.76.202:57100] mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Undefined constant "scope" in /usr/local/www/apache24/noexec/eldagsen.de/wp-content/plugins/events-made-easy/eme-widgets.php:66
[Fri Jul 14 21:02:49.131096 2023] [fcgid:warn] [pid 80780:tid 34411639808] [client 66.249.76.202:57100] mod_fcgid: stderr: Stack trace:
[Fri Jul 14 21:02:49.131115 2023] [fcgid:warn] [pid 80780:tid 34411639808] [client 66.249.76.202:57100] mod_fcgid: stderr: #0 /usr/local/www/apache24/noexec/eldagsen.de/wp-includes/class-wp-widget.php(394): WP_Widget_eme_list->widget(Array, Array)
 [Fri Jul 14 21:02:49.131130 2023] [fcgid:warn] [pid 80780:tid 34411639808] [client 66.249.76.202:57100] mod_fcgid: stderr: #1 /usr/local/www/apache24/noexec/eldagsen.de/wp-includes/widgets.php(835): WP_Widget->display_callback(Array, Array)
[Fri Jul 14 21:02:49.131146 2023] [fcgid:warn] [pid 80780:tid 34411639808] [client 66.249.76.202:57100] mod_fcgid: stderr: #2 /usr/local/www/apache24/noexec/eldagsen.de/wp-content/themes/Divi/sidebar.php(8): dynamic_sidebar('sidebar-1')

Gerd Schwarz

________________________________
Von: Franky Van Liedekerke ***@***.***>
Gesendet: Friday, July 14, 2023 10:10:31 PM
An: liedekef/events-made-easy ***@***.***>
Cc: Gerd Schwarz ***@***.***>; Author ***@***.***>
Betreff: Re: [liedekef/events-made-easy] For 4 hour last automatic Update 2.37 - 2.4 critical error in wordpress 6.2 PHP 8.0 (Issue #233)


This is not a valid bug report. No info has been provided at all.
Please for "critical errors", check your php error logfile and add php errors here. Either that or a full reproducable case.

**Comment by liedekef** [comment]
Ok, a typo in eme-widgets.php. I've released a new version that fixes this.
