### ISSUE TITLE
Wrong display in 4.1 in widget

### ISSUE THREAD

**Issue by GerdSchwarz** [liedekef/events-made-easy#234]
Thats the output of the widget in eldagsen.de on the right site:
Termine
%3Cspan+class%3D%22emdate%22%3E%23_STARTDATE%3C%2Fspan%3E%3Cbr%3E%0D%0A%3Cspan+class%3D%22emname%22%3E%23_LINKEDNAME%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emtime%22%3E%23_STARTTIME+Uhr%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emort%22%3EOrt%3A+%23_LOCATIONNAME%3C%2Fspan%3E%3Chr%3E%3Cspan+class%3D%22emdate%22%3E%23_STARTDATE%3C%2Fspan%3E%3Cbr%3E%0D%0A%3Cspan+class%3D%22emname%22%3E%23_LINKEDNAME%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emtime%22%3E%23_STARTTIME+Uhr%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emort%22%3EOrt%3A+%23_LOCATIONNAME%3C%2Fspan%3E%3Chr%3E%3Cspan+class%3D%22emdate%22%3E%23_STARTDATE%3C%2Fspan%3E%3Cbr%3E%0D%0A%3Cspan+class%3D%22emname%22%3E%23_LINKEDNAME%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emtime%22%3E%23_STARTTIME+Uhr%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emort%22%3EOrt%3A+%23_LOCATIONNAME%3C%2Fspan%3E%3Chr%3E%3Cspan+class%3D%22emdate%22%3E%23_STARTDATE%3C%2Fspan%3E%3Cbr%3E%0D%0A%3Cspan+class%3D%22emname%22%3E%23_LINKEDNAME%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emtime%22%3E%23_STARTTIME+Uhr%3C%2Fspan%3E%3Cbr%3E%3Cspan+class%3D%22emort%22%3EOrt%3A+%23_LOCATIONNAME%3C%2Fspan%3E%3Chr%3E

**Comment by liedekef** [comment]
Confirmed as a bug, fixed in 2.4.2
(urlencode call no longer needed in the widget calls, thanks to php8 new method of calling the function, but I forgot to remove it)
