### ISSUE TITLE
Error showing single event

### ISSUE THREAD

**Issue by MartenPlus** [liedekef/events-made-easy#235]
**Describe the bug**
Critical error when trying to show single event.

**To Reproduce**
Go to this page https://skaneplus.se/events/konstutstallning-kathrin-bernekorn/

**Expected behavior**
This page should show a single event

**Online Demo**
https://skaneplus.se/events/konstutstallning-kathrin-bernekorn/

**Log output**
[15-Jul-2023 07:58:49 UTC] PHP Warning:  Undefined variable $events in /home/qagwaezp/public_html/skaneplus.se/wp-content/plugins/events-made-easy/eme-events.php on line 3896
[15-Jul-2023 07:58:49 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/qagwaezp/public_html/skaneplus.se/wp-content/plugins/events-made-easy/eme-events.php:3896
Stack trace:
#0 /home/qagwaezp/public_html/skaneplus.se/wp-content/plugins/events-made-easy/eme-events.php(4668): eme_replace_event_placeholders('<div class=" bd...', Array)
#1 /home/qagwaezp/public_html/skaneplus.se/wp-content/plugins/events-made-easy/eme-events.php(1349): eme_display_single_event('konstutstallnin...')
#2 /home/qagwaezp/public_html/skaneplus.se/wp-content/plugins/events-made-easy/eme-events.php(1415): eme_events_page_content()
#3 /home/qagwaezp/public_html/skaneplus.se/wp-includes/class-wp-hook.php(308): eme_filter_events_page('')
#4 /home/qagwaezp/public_html/skaneplus.se/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#5 /home/qagwaezp/public_html/skaneplus.se/wp-includes/post-template.php(255): apply_filters('the_content', '')
#6 /home/qagwaezp/public_html/skaneplus.se/wp-content/themes/NewSkane/functions.php(532): the_content('Continue readin...')
#7 /home/qagwaezp/public_html/skaneplus.se/wp-content/themes/NewSkane/includes/blog_3.php(106): theme_get_content()
#8 /home/qagwaezp/public_html/skaneplus.se/wp-content/themes/NewSkane/page_19.php(232): theme_blog_3()
#9 /home/qagwaezp/public_html/skaneplus.se/wp-includes/template-loader.php(106): include('/home/qagwaezp/...')
#10 /home/qagwaezp/public_html/skaneplus.se/wp-blog-header.php(19): require_once('/home/qagwaezp/...')
#11 /home/qagwaezp/public_html/skaneplus.se/index.php(17): require('/home/qagwaezp/...')
#12 {main}
  thrown in /home/qagwaezp/public_html/skaneplus.se/wp-content/plugins/events-made-easy/eme-events.php on line 3896

**Additional context**

**Comment by liedekef** [comment]
Fixed here:
https://github.com/liedekef/events-made-easy/commit/2b4d34e7d1ba54ed7adfb745dcc878acd6d2ff43

Since this is just a fix for #_IS_LAST_RECURRENCE I'm not releasing a new version currently (and the bug was in there for quite some versions I'd say)
