### ISSUE TITLE
Membership features

### ISSUE THREAD

**Issue by Sp0run** [liedekef/events-made-easy#24]
Sorry, if i have posted this in the wrong area as it's more of a feature request.

1. Would it be possible to have memberships require approval, much like event RSVP? Memberships from my club require committee approval so it would be great if we could approve them and then send the applicant to the payment url.
2. Family memberships - would it be possible to charge per family member?
3. Limit the amount of family members? currently sits at 10. I have got around this by changing the for loop to <=3 but it might be nice to control it per membership

Apologies if this is already possible but I havent been able to find anything in the documentation.

**Comment by liedekef** [comment]
Feature requests are to be posted here, so that's ok.
Concerning your questions: certainly the second one will not happen: if I need to charge per family member, it is an individual membership, not a family membership. The whole idea of a family membership is to have 1 person to pay for the family.
I'll think about the others ...

**Comment by Sp0run** [comment]
Thank you, for point 2 I'm not suggesting that the family members pay individually (like you say that is an indvidual membership), but that there is a charge per member. For example, a family of 2 will pay less than a family of 4.

**Comment by liedekef** [comment]
That is already possible via discount settings (of type "Code"), where you can then make your own checks and provide a discount based on your own ruleset.

**Comment by liedekef** [comment]
Concerning 1: the next version will have a "Skip payments" option for memberships, as already present for events/bookings. So people won't be redirected the payments page, but stay "pending". Then you can first internally see if that member is ok or not and then send him the payment info. After payment arrives, you can set "Mark as paid" as usual (or if the payment is online, that happens automatically). See this changeset:
https://github.com/liedekef/events-made-easy/commit/efafba119149057befcb56e829991aa08fbbadb8

**Comment by Sp0run** [comment]
Brilliant, thanks!

**Comment by liedekef** [comment]
For the last question, from the changelog for the next version (https://github.com/liedekef/events-made-easy/commit/eb0bced7298a8a89557c07075b18ab27094d772c ):
Family memberships now have a setting that defines the max number of family members allowed per main member (default 10)

**Comment by Sp0run** [comment]
As always, thanks for the rapid response
