### ISSUE TITLE
Stop booking form pre-popuating

### ISSUE THREAD

**Issue by blanch80** [liedekef/events-made-easy#25]
Hi Franky,

I was wondering if it's possible to stop the booking form from pre-populating with the WordPress data.

We'd like to have people need to be logged in and have a specific WordPress role in order to book onto events, which we currently have setup and working, but we'd like the booking form to be clear and not automatically bring in the WordPress profile data. I understand this won't link the booking to the WordPress profile and this is fine.

Is this possible?

Thanks,
David.

**Comment by liedekef** [comment]
If you don't activate the option "Logged-in users only", then the logged-in user can clear the field (with a simple click on "x" in the lastname field).

**Comment by blanch80** [comment]
Thanks Franky, I'll have a look and see if I can get it working. Appreciate the reply.

**Comment by blanch80** [comment]
Hi Franky,

The booking for is hidden for logged out users using #_ADDBOOKINGFORM_IF_LOGGED_IN as expetced, but when logged in and unticking Require WP membership for booking the booking form is still populating with the WP info. I've also set By default require WP membership to be able to register? in the main RSVP settings to No.

I've tried with the admin and a standard subscriber account.

Single event format is:

`<strong>Date/Time</strong>: #_STARTDATE{l}, #_STARTDATE - #_STARTTIME -  #_ENDTIME <br>
<strong>Description</strong><br>#_NOTES
<br>
#_ADDBOOKINGFORM_IF_LOGGED_IN`

Have I missed something?

Thanks.

**Comment by liedekef** [comment]
It's prepolulated, but using the "x" in the lastname field, it can be emptied in one click.
