### ISSUE TITLE
Fatal Error when trying to display a single event

### ISSUE THREAD

**Issue by Schneleed** [liedekef/events-made-easy#250]
Following Error is thrown when a user wants to book a ticket for a single event:

> Fatal error: Uncaught Error: Unknown named parameter $limit
> in /var/www/vhosts/mcwelden.de/website/wp-content/plugins/events-made-easy/eme-events.php on line 1828
> 
> Call stack:
> 
>     eme_template_redir()
>     wp-includes/class-wp-hook.php:308
>     WP_Hook::apply_filters()
>     wp-includes/class-wp-hook.php:332
>     WP_Hook::do_action()
>     wp-includes/plugin.php:517
>     do_action()
>     wp-includes/template-loader.php:13
>     require_once()
>     wp-blog-header.php:19
>     require()
>     index.php:17

EME-Version: 2.4.3
PHP-Version: 8.1.21
WP-Version: 6.2.2

**Comment by liedekef** [comment]
That error is not when booking for an event, but when clicking on a calendar day and the option to directly go to the event if only one event is on that day is selected.
Anyway, it is indeed a typo and is fixed in dev. I'll release a new version now (I cleaned up other parts too :-) )

**Comment by Schneleed** [comment]
Thanks for the fast fix, it works fine again!
And yes, I wrote a pretty unprecise description of where the error occurred, sorry for that.
