### ISSUE TITLE
SiteAudit: Double slash in URL

### ISSUE THREAD

**Issue by Medius7** [liedekef/events-made-easy#26]
ahrefs.com's SiteAudit found an error:
Double slash in URL

URL:
/wp-content/plugins/events-made-easy/js/jquery-select2/select2-4.1.0-rc.0/dist//js/i18n/de.js?ver=2.2.57 

Maybe you can fix this.

**Comment by liedekef** [comment]
While this is not a real issue at all, it is fixed here:
https://github.com/liedekef/events-made-easy/commit/bc922507d31fc5d6456677c37a3da31ecf3bb802
