### ISSUE TITLE
Placeholder #_EVENTCATEGORIES{}{} does not work  

### ISSUE THREAD

**Issue by crkc** [liedekef/events-made-easy#27]
Hi Franky,
first of all thank you for this great plugin.
I am using #_EVENTCATEGORIES{1}{} placeholder to show a special category.  It worked fine, but in the current version I get:
Fatal error: Uncaught Error: Call to undefined function eme_list_of_int() in C:\xampp81new\htdocs\wp\wp-content\plugins\events-made-easy\eme-events.php:3416. 
Without filtering erverything works fine,

**Comment by liedekef** [comment]
Confirmed as  a bug and fixed here:
https://github.com/liedekef/events-made-easy/commit/3175fd98f26deba96b307773ca7bbdf37f565d35

**Comment by crkc** [comment]
Hi Franky,

It works on my website again :)
Thank you so much for this very quick fix.

Rudolf
