### ISSUE TITLE
WordPress Database Error: [Unknown column 'event_tasks' in 'field list']

### ISSUE THREAD

**Issue by blaue-mango** [liedekef/events-made-easy#274]
**Describe the bug**
I can't add new events. 
When trying to add recurring events it says "0 events added". 
When trying to add single event it says "Error adding to database".
(not the exact words, I'm getting the errors in german so I tried to translate)

Turning on debug in wp-config throws me this error when saving new event:

> WordPress-Datenbank-Fehler: [Unknown column 'event_tasks' in 'field list']
INSERT INTO `wp_eme_events` (`event_name`, `event_status`, `event_start`, `event_end`, `event_notes`, `event_rsvp`, `event_tasks`, `price`, `currency`, `rsvp_number_days`, `rsvp_number_hours`, `registration_requires_approval`, `registration_wp_users_only`, `event_seats`, `location_id`, `event_author`, `event_contactperson_id`, `event_category_ids`, `event_attributes`, `event_page_title_format`, `event_single_event_format`, `event_contactperson_email_body`, `event_respondent_email_body`, `event_registration_pending_email_body`, `event_registration_updated_email_body`, `event_registration_cancelled_email_body`, `event_registration_trashed_email_body`, `event_registration_paid_email_body`, `event_registration_form_format`, `event_cancel_form_format`, `event_registration_recorded_ok_html`, `event_prefix`, `event_slug`, `event_image_url`, `event_image_id`, `event_external_ref`, `event_url`, `recurrence_id`, `event_properties`, `creation_date`, `modif_date`) VALUES ('test mb1', '5', '2023-08-22 10:15:00', '2023-08-22 12:30:00', '', '0', '0', '0', 'EUR', '0', '0', '0', '0', '10', '0', '7', '1', '', '[]', '', '', '', '', '', '', '', '', '', '', '', '', '', 'test-mb1', '', '0', '', '', '0', '{\"create_wp_user\":0,\"auto_approve\":0,\"ignore_pending\":0,\"email_only_once\":0,\"person_only_once\":0,\"invite_only\":0,\"all_day\":0,\"take_attendance\":0,\"require_user_confirmation\":0,\"min_allowed\":\"1\",\"max_allowed\":\"10\",\"rsvp_start_number_days\":\"\",\"rsvp_start_number_hours\":\"\",\"rsvp_start_target\":\"start\",\"rsvp_end_target\":\"start\",\"rsvp_discount\":\"\",\"waitinglist_seats\":0,\"check_free_waiting\":0,\"rsvp_discountgroup\":\"\",\"rsvp_required_group_ids\":[],\"rsvp_required_membership_ids\":[],\"rsvp_addpersontogroup\":[],\"rsvp_password\":\"\",\"use_paypal\":0,\"use_legacypaypal\":0,\"use_2co\":0,\"use_webmoney\":0,\"use_fdgg\":0,\"use_mollie\":0,\"use_payconiq\":0,\"use_worldpay\":0,\"use_opayo\":0,\"use_sumup\":0,\"use_stripe\":0,\"use_braintree\":0,\"use_instamojo\":0,\"use_mercadopago\":0,\"use_fondy\":0,\"use_offline\":0,\"cancel_rsvp_days\":\"0\",\"cancel_rsvp_age\":\"0\",\"attendance_begin\":\"5\",\"attendance_end\":\"0\",\"ticket_template_id\":\"\",\"ticket_mail\":\"approval\",\"wp_page_template\":\"\",\"use_hcaptcha\":0,\"use_recaptcha\":0,\"use_cfcaptcha\":0,\"use_captcha\":0,\"captcha_only_logged_out\":0,\"dyndata_all_fields\":0,\"booking_attach_ids\":\"\",\"pending_attach_ids\":\"\",\"paid_attach_ids\":\"\",\"multiprice_desc\":\"\",\"price_desc\":\"\",\"attendancerecord\":0,\"skippaymentoptions\":0,\"vat_pct\":\"0\",\"task_registered_users_only\":\"0\",\"task_requires_approval\":\"0\",\"task_allow_overlap\":\"0\",\"task_reminder_days\":\"\",\"rsvp_pending_reminder_days\":\"\",\"rsvp_approved_reminder_days\":\"\",\"event_page_title_format_tpl\":\"0\",\"event_single_event_format_tpl\":\"0\",\"event_contactperson_email_body_tpl\":\"0\",\"event_registration_recorded_ok_html_tpl\":\"0\",\"event_respondent_email_body_tpl\":\"0\",\"event_registration_pending_email_body_tpl\":\"0\",\"event_registration_userpending_email_body_tpl\":\"0\",\"event_registration_updated_email_body_tpl\":\"0\",\"event_registration_cancelled_email_body_tpl\":\"0\",\"event_registration_trashed_email_body_tpl\":\"0\",\"event_registration_form_format_tpl\":\"0\",\"event_cancel_form_format_tpl\":\"0\",\"event_registration_paid_email_body_tpl\":\"0\",\"event_contactperson_email_subject_tpl\":\"0\",\"event_respondent_email_subject_tpl\":\"0\",\"event_registration_pending_email_subject_tpl\":\"0\",\"event_registration_userpending_email_subject_tpl\":\"0\",\"event_registration_updated_email_subject_tpl\":\"0\",\"event_registration_cancelled_email_subject_tpl\":\"0\",\"event_registration_trashed_email_subject_tpl\":\"0\",\"event_registration_paid_email_subject_tpl\":\"0\",\"contactperson_registration_pending_email_subject_tpl\":\"0\",\"contactperson_registration_pending_email_body_tpl\":\"0\",\"contactperson_registration_cancelled_email_subject_tpl\":\"0\",\"contactperson_registration_cancelled_email_body_tpl\":\"0\",\"contactperson_registration_ipn_email_subject_tpl\":\"0\",\"contactperson_registration_ipn_email_body_tpl\":\"0\",\"contactperson_registration_paid_email_subject_tpl\":\"0\",\"contactperson_registration_paid_email_body_tpl\":\"0\",\"attendance_unauth_scan_tpl\":\"0\",\"attendance_auth_scan_tpl\":\"0\",\"task_signup_email_subject_tpl\":0,\"task_signup_email_body_tpl\":0,\"cp_task_signup_email_subject_tpl\":0,\"cp_task_signup_email_body_tpl\":0,\"task_signup_pending_email_subject_tpl\":0,\"task_signup_pending_email_body_tpl\":0,\"cp_task_signup_pending_email_subject_tpl\":0,\"cp_task_signup_pending_email_body_tpl\":0,\"task_signup_updated_email_subject_tpl\":0,\"task_signup_updated_email_body_tpl\":0,\"task_signup_cancelled_email_subject_tpl\":0,\"task_signup_cancelled_email_body_tpl\":0,\"cp_task_signup_cancelled_email_subject_tpl\":0,\"cp_task_signup_cancelled_email_body_tpl\":0,\"task_signup_trashed_email_subject_tpl\":0,\"task_signup_trashed_email_body_tpl\":0,\"task_signup_form_format_tpl\":0,\"task_signup_recorded_ok_html_tpl\":0,\"task_signup_reminder_email_subject_tpl\":0,\"task_signup_reminder_email_body_tpl\":0,\"event_registration_reminder_email_subject_tpl\":\"0\",\"event_registration_reminder_email_body_tpl\":\"0\",\"event_registration_pending_reminder_email_subject_tpl\":\"0\",\"event_registration_pending_reminder_email_body_tpl\":\"0\",\"event_contactperson_email_subject\":\"\",\"event_respondent_email_subject\":\"\",\"event_registration_pending_email_subject\":\"\",\"event_registration_userpending_email_subject\":\"\",\"event_registration_userpending_email_body\":\"\",\"event_registration_updated_email_subject\":\"\",\"event_registration_cancelled_email_subject\":\"\",\"event_registration_paid_email_subject\":\"\",\"event_registration_trashed_email_subject\":\"\",\"contactperson_registration_pending_email_body\":\"\",\"contactperson_registration_cancelled_email_body\":\"\",\"contactperson_registration_ipn_email_body\":\"\",\"contactperson_registration_pending_email_subject\":\"\",\"contactperson_registration_cancelled_email_subject\":\"\",\"contactperson_registration_ipn_email_subject\":\"\",\"contactperson_registration_paid_email_subject\":\"\",\"contactperson_registration_paid_email_body\":\"\",\"attendance_unauth_scan_format\":\"\",\"attendance_auth_scan_format\":\"\",\"event_registration_reminder_email_subject\":\"\",\"event_registration_reminder_email_body\":\"\",\"event_registration_pending_reminder_email_subject\":\"\",\"event_registration_pending_reminder_email_body\":\"\"}', '2023-08-21 10:15:24', '2023-08-21 10:15:24')

**To Reproduce**
1. Trying to add a new event as single or recurring.

**Expected behavior**
The new events are added without errors.

**Screenshots**
![image](https://github.com/liedekef/events-made-easy/assets/32264292/ecc97753-5865-46be-9e5c-5709ffb337ab)

**Online Demo**
N/A

**Log output**

> [21-Aug-2023 08:44:12 UTC] WordPress database error Unknown column 'event_tasks' in 'field list' for query INSERT INTO `wp_eme_events` (`event_name`, `event_status`, `event_start`, `event_end`, `event_notes`, `event_rsvp`, `event_tasks`, `price`, `currency`, `rsvp_number_days`, `rsvp_number_hours`, `registration_requires_approval`, `registration_wp_users_only`, `event_seats`, `location_id`, `event_author`, `event_contactperson_id`, `event_category_ids`, `event_attributes`, `event_page_title_format`, `event_single_event_format`, `event_contactperson_email_body`, `event_respondent_email_body`, `event_registration_pending_email_body`, `event_registration_updated_email_body`, `event_registration_cancelled_email_body`, `event_registration_trashed_email_body`, `event_registration_paid_email_body`, `event_registration_form_format`, `event_cancel_form_format`, `event_registration_recorded_ok_html`, `event_prefix`, `event_slug`, `event_image_url`, `event_image_id`, `event_external_ref`, `event_url`, `recurrence_id`, `event_properties`, `creation_date`, `modif_date`) VALUES ('test mb5', '5', '2023-08-22 10:43:00', '2023-08-22 14:00:00', '', '0', '0', '0', 'EUR', '0', '0', '0', '0', '10', '0', '7', '1', '', '[]', '', '', '', '', '', '', '', '', '', '', '', '', '', 'test-mb5', '', '0', '', '', '0', '{\"create_wp_user\":0,\"auto_approve\":0,\"ignore_pending\":0,\"email_only_once\":0,\"person_only_once\":0,\"invite_only\":0,\"all_day\":0,\"take_attendance\":0,\"require_user_confirmation\":0,\"min_allowed\":\"1\",\"max_allowed\":\"10\",\"rsvp_start_number_days\":\"\",\"rsvp_start_number_hours\":\"\",\"rsvp_start_target\":\"start\",\"rsvp_end_target\":\"start\",\"rsvp_discount\":\"\",\"waitinglist_seats\":0,\"check_free_waiting\":0,\"rsvp_discountgroup\":\"\",\"rsvp_required_group_ids\":[],\"rsvp_required_membership_ids\":[],\"rsvp_addpersontogroup\":[],\"rsvp_password\":\"\",\"use_paypal\":0,\"use_legacypaypal\":0,\"use_2co\":0,\"use_webmoney\":0,\"use_fdgg\":0,\"use_mollie\":0,\"use_payconiq\":0,\"use_worldpay\":0,\"use_opayo\":0,\"use_sumup\":0,\"use_stripe\":0,\"use_braintree\":0,\"use_instamojo\":0,\"use_mercadopago\":0,\"use_fondy\":0,\"use_offline\":0,\"cancel_rsvp_days\":\"0\",\"cancel_rsvp_age\":\"0\",\"attendance_begin\":\"5\",\"attendance_end\":\"0\",\"ticket_template_id\":\"\",\"ticket_mail\":\"approval\",\"wp_page_template\":\"\",\"use_hcaptcha\":0,\"use_recaptcha\":0,\"use_cfcaptcha\":0,\"use_captcha\":0,\"captcha_only_logged_out\":0,\"dyndata_all_fields\":0,\"booking_attach_ids\":\"\",\"pending_attach_ids\":\"\",\"paid_attach_ids\":\"\",\"multiprice_desc\":\"\",\"price_desc\":\"\",\"attendancerecord\":0,\"skippaymentoptions\":0,\"vat_pct\":\"0\",\"task_registered_users_only\":\"0\",\"task_requires_approval\":\"0\",\"task_allow_overlap\":\"0\",\"task_reminder_days\":\"\",\"rsvp_pending_reminder_days\":\"\",\"rsvp_approved_reminder_days\":\"\",\"event_page_title_format_tpl\":\"0\",\"event_single_event_format_tpl\":\"0\",\"event_contactperson_email_body_tpl\":\"0\",\"event_registration_recorded_ok_html_tpl\":\"0\",\"event_respondent_email_body_tpl\":\"0\",\"event_registration_pending_email_body_tpl\":\"0\",\"event_registration_userpending_email_body_tpl\":\"0\",\"event_registration_updated_email_body_tpl\":\"0\",\"event_registration_cancelled_email_body_tpl\":\"0\",\"event_registration_trashed_email_body_tpl\":\"0\",\"event_registration_form_format_tpl\":\"0\",\"event_cancel_form_format_tpl\":\"0\",\"event_registration_paid_email_body_tpl\":\"0\",\"event_contactperson_email_subject_tpl\":\"0\",\"event_respondent_email_subject_tpl\":\"0\",\"event_registration_pending_email_subject_tpl\":\"0\",\"event_registration_userpending_email_subject_tpl\":\"0\",\"event_registration_updated_email_subject_tpl\":\"0\",\"event_registration_cancelled_email_subject_tpl\":\"0\",\"event_registration_trashed_email_subject_tpl\":\"0\",\"event_registration_paid_email_subject_tpl\":\"0\",\"contactperson_registration_pending_email_subject_tpl\":\"0\",\"contactperson_registration_pending_email_body_tpl\":\"0\",\"contactperson_registration_cancelled_email_subject_tpl\":\"0\",\"contactperson_registration_cancelled_email_body_tpl\":\"0\",\"contactperson_registration_ipn_email_subject_tpl\":\"0\",\"contactperson_registration_ipn_email_body_tpl\":\"0\",\"contactperson_registration_paid_email_subject_tpl\":\"0\",\"contactperson_registration_paid_email_body_tpl\":\"0\",\"attendance_unauth_scan_tpl\":\"0\",\"attendance_auth_scan_tpl\":\"0\",\"task_signup_email_subject_tpl\":0,\"task_signup_email_body_tpl\":0,\"cp_task_signup_email_subject_tpl\":0,\"cp_task_signup_email_body_tpl\":0,\"task_signup_pending_email_subject_tpl\":0,\"task_signup_pending_email_body_tpl\":0,\"cp_task_signup_pending_email_subject_tpl\":0,\"cp_task_signup_pending_email_body_tpl\":0,\"task_signup_updated_email_subject_tpl\":0,\"task_signup_updated_email_body_tpl\":0,\"task_signup_cancelled_email_subject_tpl\":0,\"task_signup_cancelled_email_body_tpl\":0,\"cp_task_signup_cancelled_email_subject_tpl\":0,\"cp_task_signup_cancelled_email_body_tpl\":0,\"task_signup_trashed_email_subject_tpl\":0,\"task_signup_trashed_email_body_tpl\":0,\"task_signup_form_format_tpl\":0,\"task_signup_recorded_ok_html_tpl\":0,\"task_signup_reminder_email_subject_tpl\":0,\"task_signup_reminder_email_body_tpl\":0,\"event_registration_reminder_email_subject_tpl\":\"0\",\"event_registration_reminder_email_body_tpl\":\"0\",\"event_registration_pending_reminder_email_subject_tpl\":\"0\",\"event_registration_pending_reminder_email_body_tpl\":\"0\",\"event_contactperson_email_subject\":\"\",\"event_respondent_email_subject\":\"\",\"event_registration_pending_email_subject\":\"\",\"event_registration_userpending_email_subject\":\"\",\"event_registration_userpending_email_body\":\"\",\"event_registration_updated_email_subject\":\"\",\"event_registration_cancelled_email_subject\":\"\",\"event_registration_paid_email_subject\":\"\",\"event_registration_trashed_email_subject\":\"\",\"contactperson_registration_pending_email_body\":\"\",\"contactperson_registration_cancelled_email_body\":\"\",\"contactperson_registration_ipn_email_body\":\"\",\"contactperson_registration_pending_email_subject\":\"\",\"contactperson_registration_cancelled_email_subject\":\"\",\"contactperson_registration_ipn_email_subject\":\"\",\"contactperson_registration_paid_email_subject\":\"\",\"contactperson_registration_paid_email_body\":\"\",\"attendance_unauth_scan_format\":\"\",\"attendance_auth_scan_format\":\"\",\"event_registration_reminder_email_subject\":\"\",\"event_registration_reminder_email_body\":\"\",\"event_registration_pending_reminder_email_subject\":\"\",\"event_registration_pending_reminder_email_body\":\"\"}', '2023-08-21 10:44:12', '2023-08-21 10:44:12') made by do_action('toplevel_page_eme-manager'), WP_Hook->do_action, WP_Hook->apply_filters, eme_events_page, eme_db_insert_event
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118
[21-Aug-2023 08:44:13 UTC] PHP Warning:  Undefined array key "event_tasks" in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-events.php on line 10118

**Version info**
PHP version: 8.0, now updated to 8.1
EME version: just updated via release to v2.4.5 (was not able to add events before update, that's why I updated)

**Additional context**
From the error, looks like a column is missing in the database. Is there an option to add the column or repair the database?

**Comment by liedekef** [comment]
That means the WP database user was not able to add the table (it has been present in EME since over a year).
To fix this, go in EME settings, tab "Other" and set the option "EME DB version" to a number one lower as what is in there now (normally the current value is 371, so set it at 370).
Upon saving, EME will detect the lower value, do some DB stuff (in this case that will try to add the column) and increase the value of "EME DB version" again (so the value will be as before in fact).
If that doesn't solve it, your wordpress DB user has problems (not enough rights, ...) to add a column.

**Comment by liedekef** [comment]
Make sure you run php 8.x and try again. Also check your php error logfiles for hints, maybe it says something about the update not working (it should). You can put WP in debug mode (temporary) to make sure you see all output.
You can always add a column manually, but this might mean other columns are missing too ...

**Comment by blaue-mango** [comment]
Alright. I'm running PHP 8.1.

I set to 370 and saved while debugging was set to true. Here is the debug.log entry. There seems to be an error with the "Row size".

> [21-Aug-2023 09:50:00 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-functions.php on line 2492
[21-Aug-2023 09:50:00 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-functions.php on line 2492
[21-Aug-2023 09:50:00 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-functions.php on line 2492
[21-Aug-2023 09:50:00 UTC] PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/users/mb-dev/www/kunden/clientid/wordpress/wp-content/plugins/events-made-easy/eme-functions.php on line 2492
[21-Aug-2023 09:50:00 UTC] WordPress database error Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs for query ALTER TABLE wp_eme_events ADD event_tasks bool DEFAULT 0; made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, eme_actions_init, _eme_install, eme_create_tables, eme_create_events_table, maybe_add_column
[21-Aug-2023 09:50:00 UTC] WordPress database error Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs for query ALTER TABLE wp_eme_bookings DROP COLUMN lang; made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, eme_actions_init, _eme_install, eme_create_tables, eme_create_bookings_table, eme_maybe_drop_column
[21-Aug-2023 09:50:00 UTC] WordPress database error Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs for query ALTER TABLE wp_eme_people ADD random_id varchar(50); made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, eme_actions_init, _eme_install, eme_create_tables, eme_create_people_table, maybe_add_column
[21-Aug-2023 09:50:00 UTC] WordPress database error Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs for query ALTER TABLE wp_eme_people ADD newsletter bool DEFAULT 1; made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, eme_actions_init, _eme_install, eme_create_tables, eme_create_people_table, maybe_add_column
[21-Aug-2023 09:50:01 UTC] WordPress database error Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs for query ALTER TABLE wp_eme_people ADD bd_email bool DEFAULT 0; made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, eme_actions_init, _eme_install, eme_create_tables, eme_create_people_table, maybe_add_column
[21-Aug-2023 09:50:01 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ';
         comment text,
         random_id varchar(50),
         UNIQUE KEY ...' at line 6 for query CREATE TABLE wp_eme_task_signups (
	 id int(11) NOT NULL auto_increment,
         task_id mediumint(9) NOT NULL,
         person_id mediumint(9) NOT NULL,
         event_id mediumint(9) NOT NULL,
         signup_status BOOL DEFAULT 1;
         comment text,
         random_id varchar(50),
         UNIQUE KEY  (id),
         KEY  (event_id)
         ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, eme_actions_init, _eme_install, eme_create_tables, eme_create_task_tables, maybe_create_table

Can I fix this?

**Comment by liedekef** [comment]
Ok, I fixed the last error (for the create table), and the php warnings (in dev). Also fixed it hopefully for the bookings and people table: I was using "tinytext" for some fields and apparently that is different for row size than just "text" (mysql stores "test" in a different blob table and counts only specific bytes for the rowsize, apparently not for tinytext).
I'm still looking on how to fix it for the events table (not much use of tinytext there, so I'm going to assume your max row size is quite limited as no other person has ever reported this). Would it be an option to increase that?

**Comment by liedekef** [comment]
Some more info: that limit (8126) is very very old (I only find references to such a small limit if I go back to 2011 for innodb type storage).

**Comment by blaue-mango** [comment]
I think I fixed it. 

The solution I found was this one: https://toolset.com/forums/topic/row-size-too-large-the-maximum-row-size-for-the-used-table-type-not-counting/

So I went into the DB and changed the ROW_FORMAT of each table that was mentioned in the error to "DYNAMIC" instead of "COMPACT".

![image](https://github.com/liedekef/events-made-easy/assets/32264292/85163022-fb75-4ed5-912b-b7ee546ef180)

Then I changed the 371 to 370 in the settings again and saved.

The Row size errors were gone. (The one with the SQL syntax error remained, though)

Then I tried to create a single event and a recurring one and both saved without errors!

So that seems to have fixed it for me.

**Comment by liedekef** [comment]
Great! 
The sql creation syntax error is fixed here:
https://github.com/liedekef/events-made-easy/commit/55654d1365b0daef82b42c3679908cea2a3d11e4
And to activate it, I increased the db version too:
https://github.com/liedekef/events-made-easy/commit/847f11c61b868717a3f864536e9291ff998ddc54

So if you apply these 2 changes, that should be ok then.
