### ISSUE TITLE
Kortingen

### ISSUE THREAD

**Issue by gdornez** [liedekef/events-made-easy#291]
Bij het toevoegen van een eerste korting krijg ik volgende foutmelding, zie bijlage
![ScreenHunter 600](https://github.com/liedekef/events-made-easy/assets/144883236/2ab0b31c-eb6c-4215-b202-8bca3d7ec144)

**Comment by liedekef** [comment]
This is not a valid bug report. Please:
- speak English
- provide php error logfiles (as requested when creating a bug report)
- provide steps needed to reproduce (what kind of discount, all the parameters etc ...)

**Comment by gdornez** [comment]
Important note:
When I go to RSVP to an event, I can select the discount code "Test".
I have no idea what effect this will have.

**Comment by liedekef** [comment]
If you don't know where the php logfile is, you should ask your provider.
But, based on what I read, it seems something in the database is not ok, causing the initial popup and also the error when adding a discount.
What version of EME are you on?
And, if you go in the EME settings, tab "Other", you'l see a setting "EME DB version" ==> what value does it say?

**Comment by gdornez** [comment]
![ScreenHunter 601](https://github.com/liedekef/events-made-easy/assets/144883236/d5f0a06d-7674-4e64-ab9a-22b9e6217baa)

EME DB version: 362

**Comment by gdornez** [comment]
![ScreenHunter 602](https://github.com/liedekef/events-made-easy/assets/144883236/624b3623-02a2-4343-8f24-4c93cd3744c4)

**Comment by gdornez** [comment]
Franky, Thanks for your help, everything seems to be working again. By the way, the discount I created was actually on the list.
I will have to keep a closer eye on the updates from now on.

**Comment by gdornez** [comment]
Thanks
