### ISSUE TITLE
CSV separator	has no affect

### ISSUE THREAD

**Issue by loelismurf** [liedekef/events-made-easy#298]
**Describe the bug**
if i set unter Settings-> Other the CSV to ";" and i make a Export of CSV on Edge from Approved Bookings he fill in ","
**To Reproduce**
1. Go to 'Settings'
2. Set 'Settings-> Other -> CSV Seperator' to ';'
3. Click on 'Save Changes'
4. Export a Approved Booking List
5. See the Seperator in the File

**Version info**
EME version: 2.4.9

**Comment by liedekef** [comment]
The CSV button indeed did not do this, but the "CSV export" link does obey the setting.
This fix solves it for the CSV button too: https://github.com/liedekef/events-made-easy/commit/92e61b266a67d026b75d788a7c35b3cf3ccbd075
