### ISSUE TITLE
Member updated Email is not sended

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#30]
**Describe the bug**
I think it is an old issue. About a membership a mail should be sent when the member is updated.

**To Reproduce**
1. Create a membership
2. Choose this membership in memberships menu
3. In "Mail format settings" create a "member updated Email"
4. Add a people in this membership
5. Update the member. The mail is never sent
6. 
**Expected behavior**
A mail should be sent to the member

**Comment by liedekef** [comment]
In fact (and it has always been like that), the "update member" mail was only sent when marking a member as unpaid. This change now makes EME do more as advertised:
https://github.com/liedekef/events-made-easy/commit/c2845b9ae4601d9ff52d4550379f9b45ed9b6cf4

**Comment by f14m07** [comment]
The membership has two custom fields that can be update in the backend. In this case, is member informed by the "member update email"?

**Comment by liedekef** [comment]
When updating (meaning: editing) a member a mail will be sent, not when updating membership.
