### ISSUE TITLE
Installation via events-made-easy.zip fails with "The link you followed has expired"

### ISSUE THREAD

**Issue by chrzimmer** [liedekef/events-made-easy#323]
Sorry, my fault ... my upload limit was only 2MB. I never saw this error message before ... 

**Describe the bug**
If i try to install the new version via events-made-easy.zip over my existing installation and it fails.

**To Reproduce**
1. Go to PlugIns -> Add PlugIn -> Upoad plugIn
2. Set events-made-easy.zip on my local file system
3. Click on 'Install now'
4.  See error:
"The link you followed has expired
Please try again"

**Expected behavior**
The new version of EME should install

**Version info**
Wordpress: 6.3.2
PHP version: 7.4.33
EME version: 2.2.86

**Comment by liedekef** [comment]
EME requires PHP version 8 or newer (7.4 is end of life since the beginning of this year).
