### ISSUE TITLE
after the Update the Placeholder do not fill out anything Example: https://www.pfadiriko.ch/events/uebertritt-21-10-2023

### ISSUE THREAD

**Issue by loelismurf** [liedekef/events-made-easy#325]
after the Update the Placeholder do not fill out anything Example: https://www.pfadiriko.ch/events/uebertritt-21-10-2023

this is my code for a Singel Event (found under new Event -> Event Section Singel Event
```
#_STARTDATE<br />
#_TOWN<br />
#_NOTES<br />
Anmeldung<br />
#_ADDBOOKINGFORM<br />
<details>
  <summary>Abmeldung</summary>
  #_CANCELBOOKINGFORM
</details>
<br />
#_MAP
```

_Originally posted by @loelismurf in https://github.com/liedekef/events-made-easy/discussions/324_

**Comment by liedekef** [comment]
This is not an EME issue: you have javascript errors on your pages ("Uncaught ReferenceError: jQuery is not defined"), which is the cause of the problem. Fix those and all will work again.
