### ISSUE TITLE
Multi-Edit of events does not work

### ISSUE THREAD

**Issue by LorenzLoesch** [liedekef/events-made-easy#33]
*How to Reproduce:*
- Filter events
- select Multiple events
- apply new category to events

See video: https://photos.app.goo.gl/fZskkGjowWhrgLJMA

*Expected Behavior:*
- all selected Events have new category

*Actual behavior:*
- selected Events still have no category

**Comment by liedekef** [comment]
Confirmed as a bug. Due to code refactor, I accidentally removed a variable there. This one-liner fixes it:
https://github.com/liedekef/events-made-easy/commit/325a199c2da279cddac276c6b81a4dc0050357f7
