### ISSUE TITLE
Facebook Import

### ISSUE THREAD

**Issue by Christoph111** [liedekef/events-made-easy#333]
hi,

i´ve been using EME for years now and it worked perfectly - thank you so much! some month ago the facebok Plugin eme-sync-facebook-events did not properly import new events, and after trying everything i can not get it to work again...maybe facebook changed something. Updating EME did not help....
any ideas how to automatically import facebook events?
cheers and thank you!
chris

**Comment by liedekef** [comment]
I don't maintain that plugin anymore, not for a long time already. Somebody else offered to maintain it, but it seems they failed to do so.
