### ISSUE TITLE
empty variable in eme-payments-.php

### ISSUE THREAD

**Issue by MichelaPau** [liedekef/events-made-easy#339]
i'm using the filter 'eme_ipn_member_action' in line 3483
the $booking variable is not defined here it seems better tu use $member

	if ( $payment['target'] == 'member' ) {
		eme_accept_member_payment( $payment_id, $pg, $pg_pid );
		if ( $is_ipn ) {
			$member = eme_get_member_by_paymentid( $payment_id );
			oiml_message($member,'ipn');
			eme_email_member_action( $member, 'ipnReceived' );
			if ( has_action( 'eme_ipn_member_action' ) ) {
				do_action( 'eme_ipn_member_action', $booking );
			}
		}

**Comment by liedekef** [comment]
confirmed, fixed in dev (see https://github.com/liedekef/events-made-easy/commit/8e24da15cd9f2e8fc1a825cff9c894a34bbd5f1f )
