### ISSUE TITLE
v2.4.13 release zip contains 2.4.12 version code

### ISSUE THREAD

**Issue by bellwood** [liedekef/events-made-easy#340]
Grabbed the zip file from the latest release (2.4.13) and upon extraction noticed it contains v2.4.12 code including versioning in readme.txt, etc

**Comment by liedekef** [comment]
I downloaded the zip, 2.4.13 is clearly present in the readme.txt . Maybe some caching issue?

**Comment by bellwood** [comment]
@liedekef I believe you are correct. I can no longer download the zip from the path previously used and a fresh download does indeed contain v2.4.13 as expected.

Thank you for the timely response 👍🏻
