### ISSUE TITLE
Unable to have "-" in front of numbers for Permalink

### ISSUE THREAD

**Issue by refugeindhamma** [liedekef/events-made-easy#352]
**Describe the bug**
If my Event Name is EME 2024, the slug will become "eme". If I type in "eme-2024" and save/update the event, the slug will revert back to "eme". Only if I put it as "eme2024" will the slug be saved.

**Expected behavior**
The slug with a "-" in front of numbers should remain after saving/updating.

**Version info**
PHP version: 8.0
EME version: 2.4.15

**Comment by liedekef** [comment]
Based on a quick code review (not tested yet), this only happens because "eme-2024" is already taken as a slug by something else in EME, so EME starts from the beginning (removing "-" and all numbers at the end of a slug and start with just "eme", then "eme-1" etc ...).

**Comment by refugeindhamma** [comment]
I'm using "EME" just as an example. The full title of the event is "Children's Drawing Class 2024". However, EME does not allow my slug to be "childrens-drawing-class-2024". I can only put it as "childrens-drawing-class2024".

**Comment by liedekef** [comment]
In general slugs are made unique by adding '-' followed by a number to it.
For recurrences, the same reasoning exists: recurring events exist of a series of single events and single events can't have the same slug. The first one would have childrens-drawing-class-2024, but the second one would have childrens-drawing-class (removing "-" followed by numbers until the end), the third one childrens-drawing-class-2, etc ...
To avoid such a difference, I remove the "-" and the numbers to begin with (for a recurrent series) and so the events will have as slug childrens-drawing-class, childrens-drawing-class-2, childrens-drawing-class-3, etc ...

However, there was a small glitch when wanting to change the slug for an event that ended with "-" followed by a number (the change was ignored in that case). Now the change will go through (after checking the new slug is unique of course or making it unique by adding a number again). The next version will correct that, but it won't change your "problem".
