### ISSUE TITLE
scope problem

### ISSUE THREAD

**Issue by mltest1** [liedekef/events-made-easy#356]
**Describe the bug**
[eme_events scope=now++100d] shows all event not only the first 100. I also tried with smaller number of days but it's the same problem.

**To Reproduce**
Look at https://skaneplus.se/evenemang-i-skane/

**Expected behavior**
I expected it to only show events from the first 100 days.

**Version info**
PHP version: 8.2.12
EME version:  2.4.15

**Comment by liedekef** [comment]
It's not an actual problem, but a doc issue: should be `now--100d`  (doc has been corrected)
