### ISSUE TITLE
"Booking Pending Email" for Contact Person not being sent

### ISSUE THREAD

**Issue by refugeindhamma** [liedekef/events-made-easy#370]
**Describe the bug**
This is a multibooking event.
I set the RSVP to require booking approval as shown below:
![Screenshot 2023-12-05 140021](https://github.com/liedekef/events-made-easy/assets/101639308/8dce9820-d437-4efe-bdec-d00c970e10ae)

After the registrant has confirmed the booking, the registrant will receive an email stating that the booking is pending approval. This part works fine. However, no email is being sent to the Contact Person even though the templates are not empty as shown below:
![Screenshot 2023-12-05 145544](https://github.com/liedekef/events-made-easy/assets/101639308/65204386-f606-43e1-a083-b9efa161276f)

**Expected behavior**
An email should be sent to the Contact Person for events pending approval, after the registrant has confirmed the bookings.

**Version info**
PHP version: 8
EME version: 2.4.16

**Comment by liedekef** [comment]
confirmed and fixed in the dev version
