### ISSUE TITLE
Generic email not sending

### ISSUE THREAD

**Issue by carlbannister** [liedekef/events-made-easy#385]
Generic email not sending when Target Audience set to 'Send to active members belongs to'

Members have been checked as active

Test email works and using target audience to number of members works

**Expected behavior**
Email to be sent to active members

**Screenshots**
![image](https://github.com/liedekef/events-made-easy/assets/143013419/149d8722-515e-40e8-8ccc-aa504e491aa1)

![image](https://github.com/liedekef/events-made-easy/assets/143013419/25f88f43-27fc-4a3c-b7a4-bbef2935a87c)

**Log output**
If applicable, check your php error logfile and add php errors here

**Version info**
PHP version:8.2.5
EME version:2.4.19 but have also tested with 2.4.16

**Additional context**

**Comment by liedekef** [comment]
This can't be reproduced: works fine here.
Do the people linked to your memberships have "Massmail" set to "Yes"? If not, you can use the option "Ignore massmail setting" when sending the generic mail.

**Comment by liedekef** [comment]
No reaction, closing.
