### ISSUE TITLE
Missing shortcode  [eme_edit_member_form]

### ISSUE THREAD

**Issue by mltest1** [liedekef/events-made-easy#386]
**Describe the bug**

Shortcode [eme_edit_member_form] missing

**To Reproduce**
Doesn't work at all if put in a page

**Expected behavior**
Expected to get a form to edit the member

**Online Demo**
While screenshots can say something, they don't say everything.
So, if possible, include a link to a demo page demonstrating the issue.

**Log output**
If applicable, check your php error logfile and add php errors here

**Version info**
PHP version: Latest
EME version: Latest

**Additional context**

**Comment by liedekef** [comment]
Do you have the needed rights to edit a member? Try by logging in as admin first

**Comment by liedekef** [comment]
Also, the code is a bit too strict in checking nonces, causing the form submit to return nothing. The dev version has this fixed already.

**Comment by mltest1** [comment]
It doesn't return nothing, it shows [eme_edit_member_form] like it's not interpretated

**Comment by mltest1** [comment]
...as a shortcode.

**Comment by liedekef** [comment]
Then make sure the "[" and "]" are exactly those characters and not some html-equivalent (make sure to use "text" input)

**Comment by mltest1** [comment]
Yes , it's correct characters. I can't find the shortcode in your code. In which module is it located?

**Comment by mltest1** [comment]
I don't know why, but now it shows. Sorry, you can close this now.

**Comment by liedekef** [comment]
If it all of the sudden shows: caching issue. I'm 100% against wordpress caching plugins :-)
