### ISSUE TITLE
text or name search in filterform

### ISSUE THREAD

**Issue by mltest1** [liedekef/events-made-easy#387]
**Describe the feature**
Having a website with 1000 locations/events/members  it's not very helpfull to get a drop-down list in the filterform. It would make more sense to have a text field in the filterform to be able to search a location/event/member

Using Wordpress search implementation is not nice because you don't want to mix results of eme with other wordpress items

**Comment by liedekef** [comment]
Converting the dropdown to something else can be done by adding this to eme.js:
```
        $('#eme_loc_filter').select2();
        $('#eme_cat_filter').select2();
        $('eme_city_filter').select2();
        $('eme_country_filter').select2();
        $('eme_contact_filter').select2();
        $('eme_author_filter').select2();
```
This converts all dropdown-selects to better selects :-) I'll test this too and add to the code if no further side-effects.

**Comment by mltest1** [comment]
What is select2 doing differently? Can I test this by adding just above lines in my live installation?

**Comment by mltest1** [comment]
I found you changes in the code and it works fine. Many thanks!

**Comment by liedekef** [comment]
I've changed the commit a bit, is better now :-)
https://github.com/liedekef/events-made-easy/commit/c461f303fb38f9dc914fcffad4b2e141182148ce
