### ISSUE TITLE
Offline Payment Option not showing

### ISSUE THREAD

**Issue by knoterich** [liedekef/events-made-easy#388]
**Describe the bug**
When I create an event with multiple payment options it is not showing the information under "offline payment info" in settings.

**To Reproduce**
Set up payment options
![image](https://github.com/liedekef/events-made-easy/assets/5469489/f3cd2667-c0cb-4b24-bf53-95d76631298b)

Set payment redirect
![image](https://github.com/liedekef/events-made-easy/assets/5469489/1779a0e2-99db-4068-9bad-a65dd4c7c046)
![image](https://github.com/liedekef/events-made-easy/assets/5469489/0b44c534-5671-43ee-aed3-6b3edc21fcf8)

Create event and select payment options
![image](https://github.com/liedekef/events-made-easy/assets/5469489/b6623f40-f923-46cf-aead-fbd29912403b)

When a booking is made there is no offline payment info
![image](https://github.com/liedekef/events-made-easy/assets/5469489/3780c7da-07f0-466a-a60a-bf33af496397)

**Version info**
PHP version: 7.4
EME version: Version 2.3.14

**Comment by liedekef** [comment]
Please update both php and EME before posting a bug (see the section about "For existing wordpress users that have version 2.3.18 or older" on the main github page https://github.com/liedekef/events-made-easy ) . I tested the latest version and it works as advertised.

**Comment by knoterich** [comment]
Updating fixed the issue.
Thank you.
