### ISSUE TITLE
WP Data not retrieved in the eme_add_member_form

### ISSUE THREAD

**Issue by MichaelWybo** [liedekef/events-made-easy#395]
**Describe the bug**

User always create their WP account first, then go to membership form (eme_add_member_form)

usually are these data retreived and prefilled:

#_LASTNAME
#_FIRSTNAME
#_EMAIL

Now the fields are empty and readonly, i've done a fallback to version 2.4.16 and it's working again 2.4.17 is broken

**Comment by liedekef** [comment]
Confirmed. This changeset (rather large) should fix it:
https://github.com/liedekef/events-made-easy/commit/4b5e18cdf8ea9428f43ef3c20598995954afd7f3

**Comment by liedekef** [comment]
I released 2.4.21 today for this

**Comment by MichaelWybo** [comment]
Thanks Freddy
