### ISSUE TITLE
Pb with Recaptcha on last version

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#4]
Hy Franky
members can't book because of recaptcha. They fill in the RSVP form and check the recaptcha box, the green box appears but they are asked again to check the box when it is already checked. By reinstalling the .31 version instead of .33 the problem disappears

**Comment by liedekef** [comment]
Confirmed. While I mistakenly thought wp_remote_get and wp_remote_post functions work in a similar way, it seems you can't just add url options for wp_remote_get ...
This is the fix you want :+1: 
https://github.com/liedekef/events-made-easy/commit/fc0444b6949028a90862d788e44098d12b99c95a

I'll release a new version for this.

**Comment by f14m07** [comment]
Thanks à lotEnvoyé de mon mobile Le 6 janv. 2023 à 17:28, Franky Van Liedekerke ***@***.***> a écrit :﻿
Closed #4 as completed.
