### ISSUE TITLE
delete the user account together with the person

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#40]
Hi Franky,
In the past I had set up this snippet :
add_action('eme_trash_person_action', 'my_eme_trash_person_function');
function my_eme_trash_person_function($person) {
   wp_delete_user($person['wp_id']);
}
 so that when we deleted people we deleted the WP user account at the same time. 
 But it doesn't seem to work anymore ?

**Comment by liedekef** [comment]
Confirmed as a bug (not feature request). Fixed here (one-liner in eme-people.php):
https://github.com/liedekef/events-made-easy/commit/c1757b752a84c599a5fcf65185b8d821c3bfe805
