### ISSUE TITLE
wpdb::prepare was called incorrectly

### ISSUE THREAD

**Issue by JosiahCarberry** [liedekef/events-made-easy#404]
**Describe the bug**
On a page containing the shortcode [eme_events], the following error message is displayed twice:
Notice: Function wpdb::prepare was called incorrectly. Unsupported value type (array). Please see Debugging in WordPress for more information. (This message was added in version 4.8.2.) in /blahblah/wp-includes/functions.php on line 6031

**To Reproduce**
1. Go to a page containing the shortcode [eme_events]
2. See error

**Expected behavior**
No error message
**Screenshots**

**Version info**
PHP version: 8.2
EME version: 2.4.22
WP: 6.4.2

**Additional context**

**Comment by JosiahCarberry** [comment]
Additional info:
The page is defined within Elementor.
The following template is used:
<table>
<tr><td style="width:12%; border-style:none; border-width:0px; border-color:black; border-radius: 10px; padding:20px; margin-top:50px;  background-color:grey; color: white; text-align: center;">#d #M<br />#Y<br /><hr style="width:"60%";">#_STARTTIME<span style="font-size:.65em"> UTC</span>+1</td><td style="padding-left:10px;  font-size: 22px;"><h4>#_LINKEDNAME</h4><span style="font-size:22px;">#_EXCERPT</span>[eme_if tag='#ESC_CITY']#_CITY[/eme_if]</td><td style="width:50%;text-align:center;">#_EVENTIMAGE</td></tr>
</table>

**Comment by liedekef** [comment]
I can't reproduce this, so I'm guessing it has something to do with the definition of the event(s). Can you check via a backtrace (wordpress debug) where in EME the error is triggered?

**Comment by liedekef** [comment]
No reply, considering invalid

**Comment by JosiahCarberry** [comment]
I had replied to your message, but for some reason the reply did not get posted here. I hope you can help me take the next steps.
I have never done what you requested and am not sure how to proceed. I presume it involves a call to the function wp_debug_backtrace_summary . If you could describe precisely how to do it, I will gladly implement it and provide the results here.

**Comment by liedekef** [comment]
For debugging I referr to the wp doc: https://wordpress.org/documentation/article/debugging-in-wordpress/

**Comment by JosiahCarberry** [comment]
Yes, I have made all those changes to wp-config.php in the document to which you refer, but it yields no more information than what I have already communicated above. I presume I need to call the function wp_debug_backtrace_summary to get the information you are seeking, but I have no idea how to do that.

**Comment by liedekef** [comment]
I don't know about that either, but there's an easier way: install "Query Monitor", that will catch backtraces for you in the browser console (and much more useful info). Don't forget to deactivate it when done of course.
If unsure: feel free to provide me with a temp admin access (and the page in question triggering the issue).

**Comment by liedekef** [comment]
Any feedback on this?

**Comment by JosiahCarberry** [comment]
Am on vacation. Thanks for your patience.

**Comment by JosiahCarberry** [comment]
Have installed Query Monitor. The call stack appears under the "Doing it wrong" rubric, as follows:

`Function wpdb::prepare was called incorrectly. Unsupported value type (array). (This message was added in version 4.8.2.)	

    eme_get_category_id_by_name_slug()
    wp-content/plugins/events-made-easy/eme-categories.php:463
    eme_get_events()
    wp-content/plugins/events-made-easy/eme-events.php:5459
    eme_get_events_list()
    wp-content/plugins/events-made-easy/eme-events.php:4293
    WP_Widget_eme_list->widget()
    wp-content/plugins/events-made-easy/eme-widgets.php:65
    Elementor\Widget_WordPress->render()
    wp-content/plugins/elementor/includes/widgets/wordpress.php:256
    Elementor\Controls_Stack->render_by_mode()
    wp-content/plugins/elementor/includes/base/controls-stack.php:2297
    Elementor\Widget_Base->render_content()
    wp-content/plugins/elementor/includes/base/widget-base.php:614
    Elementor\Widget_Base->print_content()
    wp-content/plugins/elementor/includes/base/widget-base.php:755
    Elementor\Element_Base->print_element()
    wp-content/plugins/elementor/includes/base/element-base.php:464
    Elementor\Element_Base->print_content()
    wp-content/plugins/elementor/includes/base/element-base.php:1375
    Elementor\Element_Base->print_element()
    wp-content/plugins/elementor/includes/base/element-base.php:464
    Elementor\Element_Base->print_content()
    wp-content/plugins/elementor/includes/base/element-base.php:1375
    Elementor\Element_Base->print_element()
    wp-content/plugins/elementor/includes/base/element-base.php:464
    Elementor\Element_Base->print_content()
    wp-content/plugins/elementor/includes/base/element-base.php:1375
    Elementor\Element_Base->print_element()
    wp-content/plugins/elementor/includes/base/element-base.php:464
    Elementor\Element_Base->print_content()
    wp-content/plugins/elementor/includes/base/element-base.php:1375
    Elementor\Element_Base->print_element()
    wp-content/plugins/elementor/includes/base/element-base.php:464
    Elementor\C\B\Document->print_elements()
    wp-content/plugins/elementor/core/base/document.php:1749
    Elementor\C\B\Document->print_elements_with_wrapper()
    wp-content/plugins/elementor/core/base/document.php:1144
    Elementor\Frontend->get_builder_content()
    wp-content/plugins/elementor/includes/frontend.php:1179
    Elementor\Frontend->apply_builder_in_content()
    wp-content/plugins/elementor/includes/frontend.php:1074
    apply_filters('the_content')
    wp-includes/plugin.php:205
    the_content()
    wp-includes/post-template.php:256
    genesis_do_post_content()
    wp-content/themes/genesis/lib/structure/post.php:486
    do_action('genesis_entry_content')
    wp-includes/plugin.php:517
    genesis_standard_loop()
    wp-content/themes/genesis/lib/structure/loops.php:119
    genesis_do_loop()
    wp-content/themes/genesis/lib/structure/loops.php:38
    do_action('genesis_loop')
    wp-includes/plugin.php:517
    genesis()
    wp-content/themes/genesis/lib/framework.php:66`

**Comment by liedekef** [comment]
Ok, I think I figured it out: you're using the category and the notcategory options, but for category you're using category id's and for notcategory you're using a name, correct?
The error is in the code for the name-part (and a wrong var). I corrected the code, this changeset should help:
https://github.com/liedekef/events-made-easy/commit/d8328fc5070a77cb67d0d01583ea8c78add163b2
