### ISSUE TITLE
eme-manager link not working

### ISSUE THREAD

**Issue by kevin-vanb** [liedekef/events-made-easy#41]
**Describe the bug**
When logged in into the wordpress admin module with administrator rights, clicking on the events opens the website outside the dashboard
**To Reproduce**
1. Log in into wordpress as administrator
2. Open the EME menu on the leftside
3. Click on events
4. The link followed is the url of the website, not the events link

**Expected behavior**
Opening the admin module of the events

**Comment by liedekef** [comment]
If clicking on wp-admin/admin.php?page=eme-manager opens a frontend page, something else is wrong. Cache, other plugin, ... but this is in no way an EME issue. Check for conflicts or so or try to recreate this on a test-setup and give me access

**Comment by kevin-vanb** [comment]
Sorry Franky, je had gelijk, local cache was het probleem.
Ik zocht het te ver
