### ISSUE TITLE
compicated recurring event has issues

### ISSUE THREAD

**Issue by hmhofman** [liedekef/events-made-easy#416]
**Describe the bug**
I'm trying to create a recurring event on the 3rd Wednesday of every month. 
For some reason, it resets to every 1st Monday. 

I notice the POST request has the fields in there twice: 
```
(...)
Content-Disposition: form-data; name="recurrence_byweekno"

3
-----------------------------271634183624509698881162458920
Content-Disposition: form-data; name="recurrence_byday"

3
-----------------------------271634183624509698881162458920
Content-Disposition: form-data; name="recurrence_byweekno"

1
-----------------------------271634183624509698881162458920
Content-Disposition: form-data; name="recurrence_byday"

1
(...)
```
The field are in the HTML in the spans with id **monthly-selector** and **specific_months-selector**

**Expected behavior**
Only send the right value for _recurrence_byweekno_ and _recurrence_byday_

**Version info**
PHP version: v8.2.14
WordPress 6.4.2 (NL)
MYSQL: v10.5.23-MariaDB

**Comment by liedekef** [comment]
Can you check if this changeset for eme_recurrence.php fixes it?
https://github.com/liedekef/events-made-easy/commit/3880e8f8223bbb185b06ea7f23ca18b026d25281

**Comment by liedekef** [comment]
This changeset should be ok, so I'll close this and release the fixed version.
