### ISSUE TITLE
Attendance record not updating

### ISSUE THREAD

**Issue by knoterich** [liedekef/events-made-easy#42]
**Describe the bug**
Attendance records not showing in RSVP field #_BOOKINGDBFIELD{attend_count}. 

**To Reproduce**
-Create Event with RSVP and scanable attendance
-have #_BOOKINGDBFIELD{attend_count} as a field in "Bookings list format" in settings
-scan paid booking
-check attendance report, attendance has been created correctly
-the value does not update

**Expected behavior**
The number should show the number of scanned QR codes (at least it did until around November 2022)

**Screenshots**
![DeepinScreenshot_select-area_20230128195437](https://user-images.githubusercontent.com/5469489/215285762-0d416062-ad02-49a0-b9dd-83b7cbf95cdb.png)

**Log output**

**Additional context**

Code of Booking list format:
```
<div class="divTableRow">  
<div class="divTableCell"><a href="#_ATTENDANCE_URL">#_RESPSEATS{1}</a></div>  
<div class="divTableCell">#_PERSONLASTNAME</div>
<div class="divTableCell">#_BOOKINGDBFIELD{attend_count}</div>
[eme_if tag='#ESC_FIELDVALUE{workshop1}']
<div class="divTableCell">#_RESPSEATS{3}</div>[/eme_if]
[eme_if tag='#ESC_FIELDVALUE{workshop2}']
<div class="divTableCell">#_RESPSEATS{4}</div>[/eme_if] 
<div class="divTableCell">
[eme_if tag='#_FIELD{15}']true[/eme_if]</div> 
<div class="divTableCell">#_EMAIL</div> </div>
```

The Response from the QR scan says the code has not been scanned too:

![2023-01-28-195633_002](https://user-images.githubusercontent.com/5469489/215285892-30df287c-9210-4a95-8465-cf14f9cd4e0c.jpeg)

**Comment by liedekef** [comment]
Confirmed, this fixes it:
https://github.com/liedekef/events-made-easy/commit/0506309dcdef9f700981bc486f98f1f8bb48f626#diff-0038741b4ca95fe8d3bf5c33a2ae0c7522152497d9f79c800cb488336df1760a
(only the changes in lines 987 and 988 of eme_evens.php are relevant for the fix)

**Comment by knoterich** [comment]
Can confirm the fix. Thank you.
