### ISSUE TITLE
Multiline text for some settings

### ISSUE THREAD

**Issue by knoterich** [liedekef/events-made-easy#43]
**Describe the feature**
With complex formatting a single line can be quite cumbersome to edit and multiline support would be cleaner and easider to maintain.
Workaround for us right now is copying the line and editing in external editor which works but is sometimes bit of a hassle.

![DeepinScreenshot_select-area_20230128231905](https://user-images.githubusercontent.com/5469489/215293724-854533b6-d933-4f72-ac87-7c6707d27908.png)

**Comment by liedekef** [comment]
The generic settings here are indeed limited, I never imagined people would use them for more than simple things.
Since this however are settings that impact each event, one should always be careful what to put in there.
Why not use [eme_bookings] with templates as options?

**Comment by knoterich** [comment]
This works like a Charm, thank you. It somehow never crossed our mind to do it this way.
