### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by loelismurf** [liedekef/events-made-easy#433]
**Describe the bug**
Permission not taken effekt on list up Events

**To Reproduce**
1. give the User only permission for list events.
2. go to Events no events displayed

**Screenshots**
With that permission it is not work
![image](https://github.com/liedekef/events-made-easy/assets/77551562/24e804e4-4204-4d76-bbab-302a3311d548)

With that permission it work but all editable
![image](https://github.com/liedekef/events-made-easy/assets/77551562/91333890-f6e1-41f2-9c6f-f303272c14f5)

*same issue for approved booking

With that Permission set:
![image](https://github.com/liedekef/events-made-easy/assets/77551562/4c1814dd-0019-49bc-ba61-0f409df12449)
You get
![image](https://github.com/liedekef/events-made-easy/assets/77551562/a93cc98a-5aed-4dd9-bbe6-805515c6dd91)

But i unterstand it so that the User with eme_leiter can list up but not edit.

If i change the Right for Accept all booking to eme_leiter it display all

The roles eme_leiter and eme_admin are createt self my User Role Editor.

**Comment by liedekef** [comment]
You need to check the definition of "eme_leiter". I've tested locally and all works fine here.
FYI: the permission to "list events" will only show events the user has a right to change, maybe I should make that more clear ... or add an extra option to show at least all events ...

**Comment by liedekef** [comment]
The next version will show all events (but not all the links will be shown, only those with access). The old-style (limited list of events) can be set in the Access tab when setting the rights for listing events.

**Comment by loelismurf** [comment]
Very nice and fast improvment thanks.
Yeah i understand it wrrongt.

The Option
"Veranstaltungen auflisten" should list all Events but not all editbale

Same for
Auflistung der ausstehenden Buchungen
Auflistung der genehmigten Buchungen

and if i will have that they can edit i set follow permission
Autor Genehmigung von Buchungen
Autor Bearbeitung von Buchungen
Veranstaltungen bearbeiten

May be you can change the german description

Now:
![image](https://github.com/liedekef/events-made-easy/assets/77551562/eea55c8b-3d84-4475-a44a-c71b30e9553e)

May be change a small flag "all"
![Uploading image.png…]()

**Comment by liedekef** [comment]
Sorry, I don't maintain the German translation nor do I speak Germen (fluently). Feel free to read the main readme (contains info on translations) and create a pull request.
