### ISSUE TITLE
The payment link to Stripe no longer works

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#438]
**Describe the bug**
The Stripe payment button does not appear on the payment page

**To Reproduce**
1. Fill in the membership form.
2. Normally you are redirected to the payment page. A payment button should appear on this page, redirecting you to the stripe gateway.
3. no button appears. It was working fine until a few days ago

**Expected behavior**
A payment button should appear
**Screenshots**

**Online Demo**
You can complete the enrolment process [ici](https://vogue-et-reve.fr/adhesion-eme/)

**Log output**
There are no errors on the console or in the php log

**Version info**
PHP version: 8.2
EME version: 2.4.27

**Additional context**
It was working fine until a few days ago

**Comment by liedekef** [comment]
confirmed and fixed in dev (typo). I'll release a new version today
