### ISSUE TITLE
Custom Attributes: display all by default

### ISSUE THREAD

**Issue by mattwarrenwilson** [liedekef/events-made-easy#440]
Hi Franky,

is there a way to modify the plugin so that, by default, all of my custom attributes are already shown in the Attributes tab when creating a new event, rather than having to click Add Attribute and select the attribute multiple times?

I do already use custom fields extensively, however, the custom attributes feature works well for our use case. Please see attached screenshot. "Attributes" in my case is modified to read "Crew".

Thanks & kind regards

Matt

<img width="1248" alt="Screenshot 2024-02-06 at 13 47 36" src="https://github.com/liedekef/events-made-easy/assets/18306352/72f0c845-c57b-42c2-a29c-f5c64c6203c6">

**Comment by liedekef** [comment]
no, this is not the intention since not all attributes are relevant to all events (maybe that's the case for you, but not in general)
