### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by bartleynen** [liedekef/events-made-easy#444]
**Describe the bug**
I deactivated all plugins and used the theme Twenty-Twenty Four and tried to activate the plugin in this way but I got the same error message. I uploaded the ZIP file first, which didn't work, then I uploaded the plugin files through FTP, and tried to install the plugin but that didn't work either.

What I also did:
increase memory_limit to 128M
increase max_execution_time to 300

**To Reproduce**
2. Set '...' to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error
Not relevant because I cannot activate the plugin

**Expected behavior**
Plugin should be activated successfully

**Screenshots**
Not relevant because I cannot activate the plugin

**Online Demo**
While screenshots can say something, they don't say everything.
So, if possible, include a link to a demo page demonstrating the issue.
Not relevant because I cannot activate the plugin

**Log output**
If applicable, check your php error logfile and add php errors here:
[Thu - - [Thu Feb 08 16:16:59.430749 2024][Thu Feb 08 16:16:59.430749 2024, [proxy_fcgi:error, [pid 17693:tid 139933607925504, [client 185.190.217.43:0, AH01071: Got error 'PHP message: objectcache.critical: Failed to locate and load object cache API', referer: https://anders-paardrijden.be/wp-admin/plugins.php?plugin=events-made-easy-main%2Fevents-manager.php
[Thu - - [Thu Feb 08 16:16:58.907573 2024][Thu Feb 08 16:16:58.907573 2024, [proxy_fcgi:error, [pid 17693:tid 139933624710912, [client 185.190.217.43:0, AH01071: Got error 'PHP message: objectcache.critical: Failed to locate and load object cache APIPHP message: PHP Parse error: syntax erro............xpecting ')' in /home/524613.cloudwaysapps.com/cxhnsmdujd/public_html/wp-content/plugins/events-made-easy-main/eme-filters.php on line 252', referer: https://anders-paardrijden.be/wp-admin/plugins.php?plugin=events-made-easy-main%2Fevents-manager.php
[Thu - - [Thu Feb 08 16:16:52.988952 2024][Thu Feb 08 16:16:52.988952 2024, [proxy_fcgi:error, [pid 17693:tid 139933859706624, [client 185.190.217.43:0, AH01071: Got error 'PHP message: objectcache.critical: Failed to locate and load object cache API', referer: https://anders-paardrijden.be/wp-admin/plugins.php?plugin=events-made-easy-main%2Fevents-manager.php

**Version info**
PHP version: Server running PHP version: 7.4.33. MySQL version: 10.5.11-MariaDB-1:10.5.11+maria~buster-log
EME version: The latest one I downloaded here; 2.4.28

**Additional context**

**Comment by liedekef** [comment]
The messages "Failed to locate and load object cache API" are yours to fix. If you have configured a non-functional object cache in wordpress, this will cause issues. EME only uses the cache via the standard wordpress functions.
Concerning the syntax error: based on the limited info you show, it seems you're still using php 7. EME only supports PHP 8 and newer (as indicated). Also: PHP 7.4 is end-of-life since the beginning of 2023, so upgrading is advised.

**Comment by bartleynen** [comment]
I disabled redis Cache and upgraded my server to PHP 8.4

Now I have been able to activate EME

Thanks

**Comment by liedekef** [comment]
EME never removes old events/db info unless you instruct it to do so (it's an option in the EME settings). If you had that option "on" by accident (or any other reason for the db info to be gone), you can restore the db from before (if you know the EME version you had before though, because I'll need to walk you through another setting then).

**Comment by bartleynen** [comment]
OK, thanks again, I restored my backup and will find the setting that caused the events te be deleted, adjust it, and then install the new plugin version again.

I am immensely grateful that you are keeping the legacy of EME alive, Franky. It's been on one of my client's site for as long as I can remember, wouldn't know what to do without it.

**Comment by bartleynen** [comment]
Hi Franky

I have tried again to update the EME plugin to the last version. Unfortunately, the events have been removed again. I created a staging application so fortunately, no harm's been done today. 

I found the setting that tells the plugin to remove or save the EME data when upgrading the plugin or removing it. To be clear, I took the screenshot before I installed the new version of the plugin. 
![FE55B75E-1A01-4FAB-A970-E4039E7B1CE5_4_5005_c](https://github.com/liedekef/events-made-easy/assets/60266382/e06db45f-05bc-4aec-b85b-d54909222d03)

Is there an option to export all event data before upgrading and then import it again once I have upgraded the plugin.

Thanks

**Comment by liedekef** [comment]
How exactly are you upgrading? And did you check your database if the tables are gone? What happens if you just disable/enable EME? 2.3.11 is like 2 years old ...
Like I said: EME doesn't remove data when upgrading (I'm managing 10 sites for years, never encountered issues ...).

**Comment by bartleynen** [comment]
I removed the old plugin, and then uploaded the new version through FTP.I checked the table rows, the live website with the old version of EME has 221 rows for eme_events in the database, the new one just 3.

What do you mean with 'What happens if you enable/disable EME?' If I disable EME I see EME shortcodes on the Event page, but I guess that's not a surprise, so not sure what you meant here.

If this all else seems to fail, can I export the event details from the DB and then import them into the DB for the staging copy I am now working on/with?

**Comment by liedekef** [comment]
After you removed the old plugin and before uploading ==> how many rows were in then in the eme_events table?
Next to that: the recommended method for upgrading is letting wordpress do it's job: see the main readme for this:

For existing wordpress users that have version 2.3.18 or older:
-     Download the zip "events-made-easy.zip" from the [latest release on github](https://github.com/liedekef/events-made-easy/releases)
-     Go in the Wordpress 'Plugins' menu, and click on "Add new"
-     Select the zip you downloaded, this will upload the zip and replace the existing installation without losing data
-     If the file is too big, or you need to use FTP/SSH: use your favorite upload tool to upload the contents of the zip file to the /wp-content/plugins/events-made-easy directory (remove the old files first)
-     After that, updating the plugin will be as usual in the backend

While the FTP method should work fine, it seems to me something is wrong when removing the old version. You should not do that: just disable the plugin, remove the files and upload the new ones, then reactivate. But first try the "normal" method via the "Add new" plugin method

**Comment by bartleynen** [comment]
HI Franky

Problem solved. Using the FTP method did the trick. Thanks again.
