### ISSUE TITLE
'Subscribe email subject' not displaying languages correctly

### ISSUE THREAD

**Issue by sonalvrioss-svyatos** [liedekef/events-made-easy#45]
**Describe the bug**
`[:en]Subscription request[:zh]订阅请求[:]` is entered in 'Subscribe email subject'. Email sent displays the code as is in the subject header.
![Email](https://user-images.githubusercontent.com/101639308/215299269-251498f8-027b-4e06-8c1c-ea27c603e0c1.png)

**To Reproduce**
1. Enter `[:en]Subscription request[:zh]订阅请求[:]` into 'Subscribe email subject' in the 'Email Templates" on Settings page.
2. User enters email and subscribes.
3. Email sent to the user will show the error.

**Expected behavior**
When a user subscribes from the English webpage, it should display only the [:en] portion and [:zh] for the Chinese webpage. 

**Additional context**
This is my settings for subscription email:
![Newsletter subscription](https://user-images.githubusercontent.com/101639308/215299300-34d4207a-827f-4ef7-a16e-36c521ede34d.png)

As can be seen from the screenshot, the email body also has both [:en] and [:zh] tags and they are working correctly.

**Comment by liedekef** [comment]
Confirmed as a bug, fixed here: https://github.com/liedekef/events-made-easy/commit/d907bd2e014f667795c6a41dfa1a8a4a2feef9f8
