### ISSUE TITLE
using #_RSVPSTART causes a fatal error

### ISSUE THREAD

**Issue by JuKo5310** [liedekef/events-made-easy#486]
using #_RSVPSTART or causes #_RSVPSTART{xx} a fatal error

Version 2.4.34

**Comment by liedekef** [comment]
Please obey the instructions for generating a bug report. In this case: the log files (explaining what error) and your relevant event settings (the RSVP start/end settings). If nothing is provided, I can't assist.

**Comment by liedekef** [comment]
no further reaction, closing
