### ISSUE TITLE
special message after login

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#49]
Hi Franky
When a member logs on to the site, I would like to be able to display a reminder if their membership has expired. Is there a simple way to display this?

**Comment by liedekef** [comment]
I'd use the [eme_mymemberships] shortcode, together with a template that checks for the value of #_IS_MEMBER_EXPIRED (via [eme_if] ) and display something if it returns 1.

**Comment by f14m07** [comment]
This [eme_mymemberships] shortcode seems to be not documented

**Comment by liedekef** [comment]
Correct, an oversight. Corrected now: https://www.e-dynamics.be/wordpress/eme_mymemberships/

**Comment by f14m07** [comment]
Thanks a lot Franky
