### ISSUE TITLE
Bug in members renewal

### ISSUE THREAD

**Issue by MichelaPau** [liedekef/events-made-easy#494]
It seems difficult to change property  "renewal' in memberships and membership renewal do not work
for the expired members
In the db renewal allowed type is on/off  when i replace directly it by 1/0 renewal it's allowed again

**Comment by liedekef** [comment]
Confirmed as a bug. This changeset fixes it (only the change in eme-members.php is relevant):
https://github.com/liedekef/events-made-easy/commit/8911fc0e93716cc6baf01c106afeb0fa3b050bb8
