### ISSUE TITLE
Person able to book when event is full

### ISSUE THREAD

**Issue by TimB111** [liedekef/events-made-easy#496]
A person (A) has managed to book a place when an event is full. Looking at the booking time, it seems that he submitted his details in the booking form at 2.30pm when there was 1 place remaining but didn't pay immediately. Someone else (B) then booked the last place and paid at 2.37pm. Then at 2.55pm the first person (A) completed the payment, which meant the event was overbooked.

I believe EME holds a place for 5 minutes after submitting the booking form? Is it also possible to set a timeout on the payment page so that it isn't possible for someone to leave the payment page open for more than 5 minutes which leads to this overbooking issue? Thanks

**Comment by liedekef** [comment]
Meanwhile, I think I can work around this border-case. Check this changeset:
https://github.com/liedekef/events-made-easy/commit/b3baf907e321a5fd9fe4acd87370c993aa3f49f9

**Comment by TimB111** [comment]
Yes I have both "consider pending bookings as available" and "auto-approve after payment" set to yes, so the booking process is automatic and I don't need to look at pending bookings.

Thanks, I'm trying to understand how the work around works. So once someone completes payment, EME checks for available places. And then if the event is already full are the guest & event admin notified of the issue?

**Comment by liedekef** [comment]
There's no "issue" EME-wise. The mails for payment being received are sent, but the pending booking will not get approved.  I'm still not sure if this is ok, since in fact it can only happen if someone leaves the payment window at the payment provider open for a long time (and I have no control over that, but I'm still surprised that still works after 30 minutes ...).

**Comment by TimB111** [comment]
Thank you. I think a specific email to notify the contact person is a good idea so they can take action, otherwise the guest will turn up at the event believing that they are booked in.
