### ISSUE TITLE
Event description is displayed as a list

### ISSUE THREAD

**Issue by bkeplinger** [liedekef/events-made-easy#503]
**Describe the bug**
Hi,

I noticed today as I was modifying events that descriptions are entered as a single list item, so if I enter a list within the description, I get a nested list within the description. Is this how it’s supposed to function? This was not how earlier versions functioned.

**To Reproduce**
Enter an event and add a description.

**Expected behavior**
I expect that the description would be displayed as entered, and not within a list item.

**Screenshots**
Output:
![output](https://github.com/liedekef/events-made-easy/assets/5461060/a4db71e1-c1c4-4eb6-af4d-fa9941a679a8)

Generated markup:
![markup](https://github.com/liedekef/events-made-easy/assets/5461060/0d1041fc-acfa-4bfe-bf04-207734cacbf6)

Thank you.

**Comment by liedekef** [comment]
EME renders the description as you make it, no conversion is done there. So check your event format and description (in text-mode, to make sure)

**Comment by bkeplinger** [comment]
Sorry, I entered a comment just as this came in. Again, my apologies.
