### ISSUE TITLE
#_IS_USER_MEMBER_PENDING{xxx} return 1 even if membership is Active

### ISSUE THREAD

**Issue by MichaelWybo** [liedekef/events-made-easy#526]
**Describe the bug**
The Shortcode #_IS_USER_MEMBER_PENDING is returning 1 when the membership is active, and 0 when pending :)

Using this shortcode to Debug

[eme_if tag='#_IS_LOGGED_IN' value='1'] _IS_LOGGED_IN:1 [/eme_if]
[eme_if tag='#_IS_LOGGED_IN' value='0'] _IS_LOGGED_IN:0 [/eme_if]
[eme_if tag='#_IS_USER_MEMBER_OF{DressageClubPicardie}' value='1']_IS_USER_MEMBER_OF{DressageClubPicardie}:1[/eme_if]
[eme_if tag='#_IS_USER_MEMBER_OF{DressageClubPicardie}' value='0']_IS_USER_MEMBER_OF{DressageClubPicardie}:0[/eme_if]
[eme_if tag='#_IS_USER_MEMBER_PENDING{DressageClubPicardie}' value='1']_IS_USER_MEMBER_PENDING{DressageClubPicardie}:1[/eme_if]
[eme_if tag='#_IS_USER_MEMBER_PENDING{DressageClubPicardie}' value='0']_IS_USER_MEMBER_PENDING{DressageClubPicardie}:0[/eme_if]**

Output: 

`<div id="debug">
 _IS_LOGGED_IN:1 <br>
_IS_USER_MEMBER_OF{DressageClubPicardie}:1<br>
_IS_USER_MEMBER_PENDING{DressageClubPicardie}:1<br>
</div>`

I Also tried with eq=1
Tried also to replace Membership name by the ID of the membership but same problem

**Expected behavior**
Should be the opposite of the current behavior, as show in the documentation (https://www.e-dynamics.be/wordpress/generic-placeholders/)

**Version info**
PHP version: 8.1.28 (Supporte les valeurs 64 bits)
EME version: Version 2.4.39

**Additional context**

**Comment by liedekef** [comment]
Confirmed, this should fix it:
https://github.com/liedekef/events-made-easy/commit/78a45c11675f99a2c2b4272bc2f7ea3c8ad38bd4
