### ISSUE TITLE
Unable to update membership settings

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#528]
**Describe the bug**
I recently noticed that a membership on my site wasn't working properly. An icon indicated that no membership form had been defined. On checking, it seems that all the membership parameters have been lost. The type is 'rolling period' duration period 'forever'. If I set the membership form and update the membership, the form is not saved. All membership-related emails have lost their parameters

**To Reproduce**

I can give you admin access to check. Because you need to be connected for this
**Expected behavior**
I'd like to find all my lost settings or at least be able to define them again.

** Error console
Warning	Undefined variable $found_key	

    wp-content/plugins/events-made-easy/eme-members.php:1310
    eme_add_update_membership()
    wp-content/plugins/events-made-easy/eme-members.php:841
    eme_memberships_page()
    wp-includes/class-wp-hook.php:324
    do_action('events-made-easy_page_eme-memberships')
    wp-admin/admin.php:259

**Version info**
PHP version:8.2
EME version:2.4.39

**Additional context**
The issue is the same on my local installation

**Comment by f14m07** [comment]
I have also the console msg 👍 Uncaught Error: Syntax error, unrecognized expression: [name=properties[familymember_form_tpl]]
    jQuery 11
    invalidHandler Ember
    each jQuery
    invalidHandler Ember
    jQuery 17
    <anonymous> Ember
    jQuery 13
[jquery.min.js:2:11769](https://vogue-et-reve.fr/wp-includes/js/jquery/jquery.min.js?ver=3.7.1)
    jQuery 11
    invalidHandler Ember
    each jQuery
    invalidHandler Ember
    jQuery 17
    <anonyme> Ember
    jQuery 13

**Comment by liedekef** [comment]
I'm not sure who is is generating that js error (not reproducable for now), but your first php error is the cause of the problem (causing memberships that were being edited to lose their parameters). I'll release a fix version now for this, see this changeset: https://github.com/liedekef/events-made-easy/commit/e04d8a923665fea58d3dabc0d00f5030df381bee

**Comment by f14m07** [comment]
The fix is ok. The Pb is resolved, and thanks a lot for your quick support. I have some works now to restore the membership mail setting. But no other pb, people are still in this membership
