### ISSUE TITLE
The booking form is no longer displayed

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#529]
**Describe the bug**
Since the last update, the booking form is no longer displayed. If I use the 2.4.39 it works, but not with the 2.4.40. The display of the form depends on 
[eme_if tag='#_IS_USER_MEMBER_OF{Adhérents}' value='1']. 
If I remove this condition, the form is displayed.
**To Reproduce**
You must be admin

**Expected behavior**
The condition works fine before

**Log output**
There is no php error.
**Version info**
PHP version:8.2
EME version:2.4.40

**Additional context**
The Pb is with the last version. I will give you admin access if you wont

**Comment by liedekef** [comment]
Yes, I made a typo in a file (causing a "," to become a ".", must have happened when fixing something else in vi ...). I once again released a version to fix this.
