### ISSUE TITLE
Strange thing since last update

### ISSUE THREAD

**Issue by pacaja** [liedekef/events-made-easy#536]
Today I have update to the latest version. I did this by downloading from GitHub and install the zip file. Updating through WordPress was not possible.

After the update all my events that were closed for reservation were open again. In the admin of the event the day from where to allow reservations was filled with the value of the day till the reservations are possible.

![image](https://github.com/liedekef/events-made-easy/assets/17810545/ec360262-3cb2-4bda-975e-c8b328e88a82)

**Comment by liedekef** [comment]
Indeed, when updating from an old version, there was a bug ...
This fixes it:
https://github.com/liedekef/events-made-easy/commit/31f21854ab86a821f53481b587d3ebe6e927658d

**Comment by pacaja** [comment]
I can fix that but the wrong values will not restore so I have to change every day for all future events, correct?

**Comment by liedekef** [comment]
Indeed, either that or you restore the db to before the update, do the fix and the wp will do the update again.

**Comment by pacaja** [comment]
In that order: restore db and then the fix in Wordpress (or in the zip file before updating)?

**Comment by liedekef** [comment]
Make sure wp is shut down or not accessible. EME should be at the latest version with the fix applied. Then restore the db and make wp accessible again, then go in the backend. Normally wp should have done the EME update procedure then.
If that is not the case: restore the db and EME to the old version, apply the fix to the zipped version and update as done now.

**Comment by liedekef** [comment]
I assume this is fixed (with the small fix and the redo)? So I closed this for now (and will release a new version this weekend)
