### ISSUE TITLE
'Cancel no longer allowed text' not displaying languages correctly

### ISSUE THREAD

**Issue by sonalvrioss-svyatos** [liedekef/events-made-easy#54]
**Describe the bug**
'Cancel no longer allowed text' is not displaying correctly when using `[eme_cancel_all_bookings_form]` shortcode.
![Screenshot 2023-02-01 at 08-40-31 Registration Cancellation](https://user-images.githubusercontent.com/101639308/215917248-e8552d43-4ee9-42ee-8d3a-8194300eb195.png)

My settings:
![Cancellations](https://user-images.githubusercontent.com/101639308/215917298-1ef4c1a0-8d01-421f-9aba-5c33a8cd26c3.png)

**To Reproduce**
1. Set up 2 or more languages for 'Cancel no longer allowed text'
2. Event is over / Cancellation date is over
3. See error

**Expected behavior**
'Cancel no longer allowed text' should display the language based on the website language.

**Comment by liedekef** [comment]
Fixed here:
https://github.com/liedekef/events-made-easy/commit/a3f0f247dc7e2248cebd4ed696fd03716615d6a1
