### ISSUE TITLE
RE Captcha doesn't work

### ISSUE THREAD

**Issue by Schneleed** [liedekef/events-made-easy#545]
After closing a registration period, we decided to reactivate it for one more day.
After reactivation of the form it was not accepting the ReCaptcha Field anymore. It always threw the error "wrong code"

**To Reproduce**
As I needed to fix it temporarily, I simply deactivated ReCaptcha for now. Tomorrow I will post the link to the form which isn't working.

**Expected behavior**
Work as designed and as before the break of registration with a working Google ReCaptcha check.

![IMG-20240506-WA0005.jpg](https://github.com/liedekef/events-made-easy/assets/140977913/cc92d301-fc84-4198-aae5-4f1e65271a0e)

![IMG-20240506-WA0006.jpg](https://github.com/liedekef/events-made-easy/assets/140977913/32f24548-2f4c-42dd-9650-5c06a6f0580b)

![IMG-20240506-WA0007.jpg](https://github.com/liedekef/events-made-easy/assets/140977913/a2fcc947-3975-4120-9b07-992cc87d4792)

**Online***
Link will be posted tomorrow

**Log output**
If applicable, check your php error logfile and add php errors here

**Version info**
PHP version: 8.1.28
EME version: 2.4.42

**Additional context**

**Comment by Schneleed** [comment]
Interesting as this form worked pretty nice until yesterday evening by using ReCaptcha. Then it was automatically deactivated by timing in the event and with the reactivation today it didn't work with ReCaptcha and I needed to change back to eme_captcha to make it work again.
Within the form template there was nowhere any eme_captcha defined.
Or did any update change something regarding the setting within the event itself where eme Captcha must be chosen?
So far it did work nicely with having the EME Captcha checked in the event but using ReCaptcha in the form.

**Comment by liedekef** [comment]
Your latest comment is very confusing to me :-)
Anyway: the error comes from the EME captcha check failing, but I don't see where you can enter the captcha.
Make sure not to activate multiple captcha's for a form, that will cause issues.

**Comment by Schneleed** [comment]
So just to clarify:
If I check the box for EME Captcha within the event, I need to make sure not to use any other captcha solution for the booking form than EME Captcha, correct?
If I uncheck this box for EME Captcha in the event, I can use any other captcha solution without getting this error?

Fun fact:
It worked nicely with ReCaptcha AND the checkbox activated for EME Captcha w/o having a field for entering an EME Captcha code, which in this case wouldn't have made sense as there was no EME Captcha code displayed in the form due to the usage of the #_RECAPTCHA placeholder in the template.

Anyway, please confirm if I am right with my both questions in the beginning, so that I can fix this on my site.

**Comment by liedekef** [comment]
You should only use 1 captcha solution in the form, the order of preference (if more than one is configured) is determined by the code (if recaptcha is to be used, that wins, then hcaptcha, then cfcaptcha, then eme captcha). The check for captcha correctness however is not that clever and will check all configured captchas.
So: just use 1 captcha solution in your form.
