### ISSUE TITLE
Plugin update through Wordpress not working

### ISSUE THREAD

**Issue by pacaja** [liedekef/events-made-easy#546]
The update of the plugin does not work, have I missed something? How can I solve this, thanks in advance.

![EME_UpdateError_20240508](https://github.com/liedekef/events-made-easy/assets/17810545/d7ec8b67-c818-4a5c-b415-f2f19a218f23)

**Comment by liedekef** [comment]
You need to check what is blocking your access to github (I don't own github :-) )
If that's not working, download the zip from github and upgrade via the wordpress zip-upload method.

**Comment by pacaja** [comment]
Ok, I will try to find out what the problem is. I have tried to update the plugin manually by downloading and installing the zip. INow I have two instances of the plugin. Version 2.4.41 is still active and the update to 2.4.42 is inactive.

<img width="1529" alt="image" src="https://github.com/liedekef/events-made-easy/assets/17810545/b57efb96-3a5b-402f-bb42-e79c33e47418">

<img width="1305" alt="image" src="https://github.com/liedekef/events-made-easy/assets/17810545/a015ecd4-e3cf-46c9-9f69-e1f95afe848d">

**Comment by liedekef** [comment]
I don't know how you installed the zip (it needs to be done via the wordpress admin panel, not manually). Now you need to remove one of the 2 instances, but that is wordpress support (and not EME) and rename the plugin dir of the new one to be "events-made-easy"
