### ISSUE TITLE
Cancellation for recurrence and multibooking events

### ISSUE THREAD

**Issue by sonalvrioss-svyatos** [liedekef/events-made-easy#55]
**Current Usage & Issues**
Currently, the shortcode `[eme_cancel_all_bookings_form]` only allows individual events to be cancelled. If a participant signs up for recurrent and/or multibooking events, it is very troublesome to cancel the events through the shortcode. Every single event cancellation requires the name & email input which means signing up for a 5-session recurrent event will require entering the name & email 5 times to cancel the booking.

**Describe the feature**
Allow cancellations for recurrent and multibooking events so that participants only need to enter their name & email once to cancel multiple registered events.

**Comment by liedekef** [comment]
A shortcode is either used inside an event or standalone. As such it needs an id of some kind, programmed in the page. The payment id is not known so can't be set in the shortcode, so it should thus be given via the url of some kind.
And there we already have the solution: use #_CANCEL_URL in your mails when booking (see also the options "Cancel one payment form format" and "Cancel one payment form: booking line format" for layout changes).  That url allows people to cancel all bookings related to 1 payment in one go.
