### ISSUE TITLE
2.4.44 implemented #_IS_USER_IN_GROUP for Dynamic Groups but broke #_IS_USER_IN_GROUP for registered groups in EME

### ISSUE THREAD

**Issue by MichaelWybo** [liedekef/events-made-easy#560]
**Describe the bug**
Hello Franky

Since 2.4.44 update 
This line always return 0:

[eme_if tag='#_IS_USER_IN_GROUP{Admins,Agility,Chiots,GroupeA,GroupeB,GroupeC,Assistant,Moniteur}' value='0']

Fallback to 2.4.43 and its OK

![image](https://github.com/liedekef/events-made-easy/assets/32988994/a7ad952d-3f8b-49f6-aa9f-53ef9e9bc148)

**Comment by MichaelWybo** [comment]
That helped for single group.
Found out that the problem is also the fact that there is more than 1 group

--> [eme_if tag='#_IS_USER_IN_GROUP{Admins,Moniteur,Assistant}' value='1'] --> Not Working
--> [eme_if tag='#_IS_USER_IN_GROUP{Admins}' value='1'] --> Working

**Comment by liedekef** [comment]
That seems to be working fine here ... can you test further with the just released version? Also: check your php error logfiles, if there's an issue some error (php or mysql) should be logged somewhere (if you log errors to file, which of course everyone should)

**Comment by MichaelWybo** [comment]
Nothing specific in error_log

But I reverted this change: [ef53a2f](https://github.com/liedekef/events-made-easy/commit/ef53a2f75163ddf54eba9e40620ff432a9a5fbbf) and it's working again with 2.4.45 and only this reverted change

**Comment by liedekef** [comment]
ok, I see ... it is because you specify the group names, not their id's. The old code worked unintentionally :-)
The change you reverted is ok, but less efficient if someone uses lots of group ids. This change should help too:

https://github.com/liedekef/events-made-easy/commit/9823ff87b2b7e58a1fc792b282bead774a084d1c

**Comment by MichaelWybo** [comment]
I made the page that uses these placeholders long time ago, and the documentation (https://www.e-dynamics.be/wordpress/generic-placeholders/) say "called xxx" so i assumed that was only their names, not ids :)

Thanks for the modfication

**Comment by liedekef** [comment]
It might very well be that I did it like it was before just for this reason, but I didn't document it :-) So now the code is better documented too, this can now be closed.
