### ISSUE TITLE
Error when copying an event

### ISSUE THREAD

**Issue by TimB111** [liedekef/events-made-easy#564]
**Describe the bug**
When copying an event I get the following error in the "Bookings and tasks" panel on the right-hand colum:
`Warning: Undefined array key "event_id" in /home/myserver/public_html/mysite.co.uk/w/wp-content/plugins/events-made-easy/eme-events.php on line 6537

Warning: Undefined array key "event_id" in /home/myserver/public_html/mysite.co.uk/w/wp-content/plugins/events-made-easy/eme-events.php on line 6538

Warning: Undefined array key "event_id" in /home/myserver/public_html/mysite.co.uk/w/wp-content/plugins/events-made-easy/eme-events.php on line 6558

Warning: Undefined array key "event_id" in /home/myserver/public_html/mysite.co.uk/w/wp-content/plugins/events-made-easy/eme-events.php on line 6565
RSVP Info: Free: 0, Approved: 0, Max: 21 `

**To Reproduce**
Go to EME > Events > Filter events (using a category and event name) > Copy event > A panel called "Bookings and tasks" appears between "Event status" panel and "Author" panel, and this "Bookings and tasks" panel contains the error.

**Version info**
PHP version: 8.0
EME version: 2.4.46

**Comment by liedekef** [comment]
It's not an error, but php warnings :-) Nothing bad in fact (and you should avoid showing php warnings on screen, just in logfiles).
This fixes it: https://github.com/liedekef/events-made-easy/commit/037ebc91f4bfa22da43f3f20d269084aa98e8812

**Comment by TimB111** [comment]
Ok thank you.
