### ISSUE TITLE
replies-to always the email from the admin

### ISSUE THREAD

**Issue by rskina9073** [liedekef/events-made-easy#568]
**Describe the bug**
I have a problem with sending e-mails and can't figure out what the problem might be. I manage several pages and subpages of a rescue organization (so I am a super admin). My problem is, no matter which emails EME sends I am always listed as replies-to with my email address. Everyone who books a course/event and receives an email and then clicks on “reply” gets my email address suggested in the “To” field. Although I have neither created the course/event, nor am I listed as a contact person in the respective event. What could be the reason for this? Thank you very much

**To Reproduce**

**Expected behavior**
there should be always the senders email in the replies to field.

**Screenshots**

**Online Demo**
While screenshots can say something, they don't say everything.
So, if possible, include a link to a demo page demonstrating the issue.

**Log output**
If applicable, check your php error logfile and add php errors here

**Version info**
PHP version:
EME version: 2.3.9

**Additional context**

**Comment by liedekef** [comment]
Your EME version is way out of date, please update first (per the instructions in the generic readme) and try again.

**Comment by liedekef** [comment]
No further response, closing
