### ISSUE TITLE
Undefined variable: wp

### ISSUE THREAD

**Issue by JosiahCarberry** [liedekef/events-made-easy#57]
**Describe the bug**
The following messages appear in the front end when displaying event pages:
```

Notice: Undefined variable: wp in /blahblah/wp-content/plugins/events-made-easy/eme-functions.php on line 1305

Notice: Trying to get property 'request' of non-object in /blahblah/wp-content/plugins/events-made-easy/eme-functions.php on line 1305
```

**To Reproduce**
1. Open an event in the front end
2. See error

**Expected behavior**
No messages

**Additional context**
EME VERSION 2.3.47
WP version 6.1.1

**Comment by liedekef** [comment]
duplicate from #53 
Also: showing php warnings/notices in your frontend is not a recommended practice. Either log those to a file or don't, but showing them in the frontend will lead to path disclosure for any plugin/thing causing a php warning or notice.
