### ISSUE TITLE
Impossible to update to the last version 2.4.51

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#602]
**Describe the bug**
WP stop the EME update process
**To Reproduce**
I try to update and WP has an error
I reinstall 2.4.50 and WP work again.
I try again and it was the same issue.
I will see that tomorrow. But maybe a network issue

**Comment by liedekef** [comment]
No, a new issue with code I put in place for option arrays. But for striipe (which is a special case for specific reasons) this code was untested and resulted in an error.  I undid that code part too and released yet anotherr version.
