### ISSUE TITLE
The "Cleanup action" form  is confusing in Swedish translation

### ISSUE THREAD

**Issue by WP-admin-i-Sjomarken** [liedekef/events-made-easy#608]
**Describe the bug**
1. The first and second last action has the same wording in Swedish translation. "Remove bookings in thrash older than" is the same as "Remove events older than" in the first action.
2. The confirmation text when deleting events older than 36 months is wrong in Swedish translation.
"Action info
Cleanup done: events (and corresponding booking data) older than 36 month(s) have been removed." does not appear. Instead I got 
"Handlingsinfo
Rensning utförd: obetalda bokningar som inväntar bekräftelse och är äldre än 36 minuter har tagits bort."

**To Reproduce**
1. Go to 'Events Made Easy' chose 'Cleanup actions'
2. Fill in: Ta bort event som är äldre än 36 Månad(er) 
3. Click on 'Verställ' and confirm.
4. Read the confusing message.

**Expected behavior**
The form must behave and translate in the same manner in Swedish as in English.

**Version info**
PHP version: Server running PHP version: 8.3.9. MySQL version: 10.11.6-MariaDB-0+deb12u1
EME version: Version 2.4.53 | Av [Franky Van Liedekerke](https://www.e-dynamics.be/)

**Comment by liedekef** [comment]
I can't translate EME in Swedish myself, contributions are needed for that. Read the main readme on how to contribute to translations.
