### ISSUE TITLE
Displaying the groups column for people

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#61]
Hi,
When I display the people in the backend, I can choose the Groups column and I expect to see the groups to which the people belong. But nothing is displayed?

**To Reproduce**
1. Go to '.wp-admin/admin.php?page=eme-people'
2. Right click to the head of column
3. check the groups case
4. Nothing appear in the column and the bulk action has no effect

**Expected behavior**
The names or the ID of the groups should appear.

Maybe a bug

**Comment by liedekef** [comment]
This is not reproducable here. Can you reproduce that on a test site? Or give me admin access to check?

**Comment by f14m07** [comment]
Thanks for your proposal. You have now admin access vogue-et-reve.fr

**Comment by f14m07** [comment]
I think there is a similar problem with the "last seen on" column in the members table

**Comment by liedekef** [comment]
It seems "groups" is now a reserved keyword in mysql, causing the problem. I'll rewrite these SQL statements.
The "last seen on" column in the members table is empty for all your members though, so it is logical it is not showing anything.
