### ISSUE TITLE
event frontend submit form and custom fields

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#614]
**Describe the bug**
Two custom fields are not well rendering, and two warning PHP logs 

**To Reproduce**
I added two customfields in my form with this code
```html
                <div class="input">
                        <label for="CodePonton">Code accès ponton le jour du départ, il sera transmis la veille aux équipiers</label><br />
			#REQ_CUSTOMFIELD{CodePonton}
                </div>
                <div class="input">
                        <label for="Emplacement de départ">Emplacement du voilier le jour du départ, il sera transmis la veille aux équipiers</label><br />
			#REQ_CUSTOMFIELD{Emplacement de départ}
                </div>
```

**Expected behavior**
The text area to set the value doesn't appear

**Screenshots**
<img width="593" alt="image" src="https://github.com/user-attachments/assets/7f6c95d9-16b3-47c8-a709-346478b2d77f">

**Online Demo**
later if necessary

**Log output**
These lines two times
Warning: Undefined array key 1 in /Users/fredericmoriniere/Local Sites/vogue-reve/app/public/wp-content/plugins/events-made-easy/eme-fs.php on line 153
**Version info**
PHP version:
EME version:

**Additional context**

**Comment by liedekef** [comment]
Confirmed and fixed here (2 lines changed):
https://github.com/liedekef/events-made-easy/commit/8444836b96730de7edf2daed8eb30ce69b3cd59f

**Comment by f14m07** [comment]
Thanks a lot. That is OK now.
**But** the button "Submit" is not taken into account.
Even I add nothing to the form and then I have a button with "Create event"
It is I add #_SUBMIT{Publier ma navigation} it is the same result : no event created

**Comment by liedekef** [comment]
Is there an error? Or do you require specific permissions to add? Or do you add it as guest?

**Comment by f14m07** [comment]
Sorry, no error in the PHP log. But in the console I have this
<img width="752" alt="image" src="https://github.com/user-attachments/assets/b3d358dd-e2b7-4a98-9b6a-fb3d7086e436">

**Comment by f14m07** [comment]
Not activated

**Comment by liedekef** [comment]
ok, in fact a bug I discovered in the old plugin but I forgot to check if activated in the new version :-)
This will fix it:
https://github.com/liedekef/events-made-easy/commit/3b9e12db947e41653e504880c77da48dcead2d07
and
https://github.com/liedekef/events-made-easy/commit/d1d7dbe4da059f130bb64e384ee71683546a384e

**Comment by f14m07** [comment]
Yes the button is ok now.
But it seems that the number waiting list seats included are not taken into account.
I choose 6 seats and 2 seats on the waiting list. There should be 4 seats available. But there are 6 and none are marked on the waiting list.
And is it possible to choose the after submit redirection URL?

**Comment by liedekef** [comment]
The redirection url has been replaced by a success message that can accept event placeholders.
Concerning the seats: how do you do this (relevant part of your event form)? I've almost copy/pasted that part from the old plugin ...

**Comment by f14m07** [comment]
I use this code in the form:
```html
<div class="input"><label for="event_seats">Nombre total de places équipiers incluant celles qui seront placés en attente</label>
#REQ_FIELD{event_seats}</div>
<div class="input"><label for="waitinglist_seats">Nombre de places en attente</label>
#_FIELD{waitinglist_seats}</div>
```

**Comment by liedekef** [comment]
waitinglist_seats is not a basic event setting, but a property. This works (as an example):

RSVP: #_FIELD{event_rsvp}{binary}
Seats: #_FIELD{event_seats}
waiting lis: #_PROP{waitinglist_seats}

The next version of EME will try to catch this and treat #_FIELD as #_PROP if a property exists with that name.

**Comment by f14m07** [comment]
With EMEFS I used this code:
```php
 <div class="input">
			<label for="event_seats"><?php _e('Indiquer le nombre de réservations maximum incluant celles qui seront en attente','events-made-easy-frontend-submit'); ?></label><br />
			<?php EMEFS::required_field('event_seats'); ?>
			<?php EMEFS::error('event_seats'); ?>
		</div>
        <!--Pour les places en liste d'attente -->
        <div class="input">
			<label for="waitinglist_seats"><?php _e('Indiquer le nombre de places qui seront placées en attente','events-made-easy-frontend-submit'); ?></label><br />
			<?php EMEFS::property('waitinglist_seats'); ?>
			<?php EMEFS::error('waitinglist_seats'); ?>
```
My question is: How can I integrate your exemple in my form? I will read again the doc

**Comment by liedekef** [comment]
just replace #_FIELD{waitinglist_seats} by #_PROP{waitinglist_seats} in your form.

**Comment by f14m07** [comment]
Thanks a lot. All seems fine now. 
All I have to do now is make the substitution and delete EMEFS.
It's an easier feature to implement now.

**Comment by liedekef** [comment]
I think so too :-) And it uses more generic code, so easier to maintain (no separate css so easier to override, a simple extra js etc ...).
