### ISSUE TITLE
Error WP with the last update

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#616]
**Describe the bug**
This is the WP message:
This plugin failed to load properly and is paused during recovery mode.
An error of type E_PARSE was caused in line 115 of the file /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-fs.php. Error message: syntax error, unexpected token "{"
**To Reproduce**

**Version info**
PHP version: 8.3
EME version: 2.5.3

**Additional context**
Just after the update

**Comment by f14m07** [comment]
I upload the last eme-fs.php file I had from yesterday and it works. So maybe it is a specific issue of my update.

**Comment by liedekef** [comment]
sorry, new version released that fixes the typo.
