### ISSUE TITLE
Since last update update [eme_if tag='#_IS_USER_IN_GROUP{x,xx,xxx}' value='0']

### ISSUE THREAD

**Issue by MichaelWybo** [liedekef/events-made-easy#63]
**Describe the bug**
Since the renaming of groups for MYSQL it seems that de the IF combine with #_IS_USER_IN_GROUP is not working anymore

Fallback to v2.3.48 and it's working again

**Screenshots**

Code used:

`[eme_if tag='#_IS_LOGGED_IN' value='0']
[Inscrivez-vous ou connectez-vous pour voir le calendrier](https://dressagepicardie.com/connexion/)[/eme_if][eme_if tag='#_IS_LOGGED_IN' value='1'][eme_if2 tag='#_IS_USER_IN_GROUP{Admins,Agility,Chiots,Groupe A,Groupe B,Groupe C,Mondioring,Assistant,Moniteur}' value='0'][eme_if3 tag='#_IS_USER_MEMBER_OF{Dressage Club Picardie}' value='1']

[Vous n'avez pas encore de groupe attribué, veuillez contacter le secrétariat](https://dressagepicardie.com/contact/)

[/eme_if3][/eme_if2][/eme_if]`

**Comment by liedekef** [comment]
Confirmed, this fixes it: https://github.com/liedekef/events-made-easy/commit/1d99a7be3e7214483539f14f7fcb296c6bc38307

**Comment by MichaelWybo** [comment]
Super efficient as usual 
Thank you Franky
