### ISSUE TITLE
The #_PAYMENT_URL placeholder does not allow payment

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#635]
**Describe the bug**
I use #_PAYMENT_URL in the booking confirmation email and on a private page after login to enable online payment for the booking. This link no longer has any effect when you click on it, you stay on the same page. I made my last payment on 22 August

**Expected behavior**
Displaying the payment page for paying with Stripe

**Log output**
No error on console 
I found this error in PHP log
25-Aug-2024 09:51:48 UTC] PHP Warning:  Undefined variable $eme_is_admin_request in /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-formfields.php on line 1568
?
**Version info**
PHP version:8.3
EME version:2.5.8

**Additional context**
same issue on local site and public site

**Comment by f14m07** [comment]
I've noticed that when I move my mouse over the link I get the page address and not events/p/ a long code.
I've deactivated the cache and wordfence

**Comment by liedekef** [comment]
Is this for bookings, members or frontend submit?

**Comment by f14m07** [comment]
Sorry, I was out. The issue is on booking. I'm stumped because I have a local site where it works and another where it doesn't.

**Comment by f14m07** [comment]
I checked the setting of the event RSVP and the payment method was not defined. I don't understand why because before this setting was set by defaut

**Comment by f14m07** [comment]
I think since the new fs submit, this setting is not set by default

**Comment by liedekef** [comment]
ok, that's a different bug :-) This should help:
https://github.com/liedekef/events-made-easy/commit/4069f26752c4e2d391cf2684b98821e286643c3e

**Comment by f14m07** [comment]
Thanks for all Franky. Your support is always efficient. I'll come back after test

**Comment by f14m07** [comment]
I upload the four files (rsvp, members, events, and fs). I choose stripe in the fs tab setting, but when I check in admin, the new event planned in the frontend it has no payment method settled with stripe. What I have missed?

**Comment by liedekef** [comment]
The payment methods in FS admin settings are used when you need to pay for event submits, it is not related to any RSVP setting. For new events, EME will by default chose the chosen payment method if only 1 payment method is configured. If more are configured, nothing gets selected automatically.

**Comment by liedekef** [comment]
Btw, the next version of EME will make it more clear which payment gateways are considered configured.

**Comment by f14m07** [comment]
I only have Stripe and Offline defined. I have never had this problem before with EMEFS. I will remove Offline. Could a filter hook consolidate the device?

**Comment by liedekef** [comment]
Well, I uniformised some illogical payment code, so it is possible that in the past the offline method didn't count as extra method , but it is in fact a payment method like any other. I'll check an older version to be sure though.

**Comment by liedekef** [comment]
I verified up to 2.4.46 and EME behaved like this all the time. I'll check the latest frontend submit code too now

**Comment by liedekef** [comment]
Tested it with 1 configured payment method and then that method gets selected (at least with the current dev-code)

**Comment by f14m07** [comment]
Not for me. But I have uploaded only 4 files. Maybe I need to upload all the zip dev version.

**Comment by f14m07** [comment]
It's OK with all the dev version

**Comment by liedekef** [comment]
When I mean it gets selected I mean that a newly submitted event has that payment gateway as configured payment gateway. Works as expected.

**Comment by f14m07** [comment]
However, I already have a filter in the uploads/event-made-easy/includes directory, but it seems to have no effect on allowing online payment from the link generated by #_PAYMENT_URL.
```php

function my_emefs_event_insert_filter($event){
  $event['event_properties']['person_only_once'] = 1;
  $event['event_properties']['email_only_once'] = 1;
  $event['event_properties']['check_free_waiting'] = 1;
  $event['event_properties']['use_stripe'] = 1;
  $event['event_properties']['skippaymentoptions'] = 1;
  return $event;
}
add_filter('eme_fs_event_insert_filter','my_emefs_event_insert_filter');
add_filter('eme_insert_event_filter','my_emefs_event_insert_filter');
```

**Comment by liedekef** [comment]
ok, there something needs to changed
`  $event['event_properties']['use_stripe'] = 1;`
to:
`$event['event_properties']['payment_gateways'] = ['stripe'];`

**Comment by f14m07** [comment]
Thanks for all.
On the production website, I have still the 2.5.8 version. I have noticed some php warnings:
```
[25-Aug-2024 09:51:48 UTC] PHP Warning:  Undefined variable $eme_is_admin_request in /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-formfields.php on line 1568
[26-Aug-2024 07:50:18 UTC] PHP Warning:  foreach() argument must be of type array|object, false given in /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-people.php on line 1387
[26-Aug-2024 07:53:54 UTC] PHP Warning:  foreach() argument must be of type array|object, false given in /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-people.php on line 1387
[26-Aug-2024 08:11:55 UTC] PHP Warning:  Trying to access array offset on null in /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-functions.php on line 371
[26-Aug-2024 09:18:31 UTC] PHP Warning:  Undefined variable $eme_payment_form_footer_format in /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-payments.php on line 395
[26-Aug-2024 09:35:10 UTC] PHP Warning:  foreach() argument must be of type array|object, false given in /home/taeq4768/vogue-et-reve.fr/wp-content/plugins/events-made-easy/eme-people.php on line 1387
```

**Comment by liedekef** [comment]
ok, new version released :-)
