### ISSUE TITLE
Deletion of a holiday list, leads to an error

### ISSUE THREAD

**Issue by d0grafter** [liedekef/events-made-easy#639]
**Describe the bug**
Deletion of a holiday list, leads to an error.

**To Reproduce**
1. Go to holiday
2. select a list
3. Click on 'delete
4. click on ok
5. See error

**Comment by liedekef** [comment]
Typo confirmed, this fixes it: https://github.com/liedekef/events-made-easy/commit/41d1e30c2783fa05c1a178376995baf93b87465f
