### ISSUE TITLE
Email sending method

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#64]
Hi Franky
My configuration includes a plugin : Easy WP SMTP, I'm wondering what the correct setting is in the "Settings/Email/Email sending method". When I choose 'WordPress Email' or 'PHP email function' it works, but when I choose SMTP with the same settings than in the plugin Easy WP SMTP, EME tell me "SMTP connect() failed". Is it due to the plugin Easy WP SMTP ? or is it normal to choose  'WordPress Email' or 'PHP email function' in EME ?

**Comment by f14m07** [comment]
I have not open that as a bug. I click open a blank issue because no categorie was discussion (only bug, feature request and vulnerability. As I said I used the same setting in EME than in  Easy WP SMTP (port SSL user/pwd) my question is : are EME emails will be intercepted by Easy WP SMTP or not ?

**Comment by liedekef** [comment]
For future reference (it may not have caught your eye): https://github.com/liedekef/events-made-easy/discussions
Concerning Easy WP SMTP: when using smtp they should not get intercepted, because *normally* only calls via wp_mail are intercepted by other plugins.
In this case: did you try to activate the smtp debug mode in EME and see the output?

**Comment by f14m07** [comment]
Yes I did and it works with SMTP only if I desactive name sender and pwd

**Comment by liedekef** [comment]
Well, if it works without username/pwd, then the server is not requesting those and/or the username/pwd combo was wrong. Based on the info given so far, that's about all I can say.

**Comment by f14m07** [comment]
so should I use SMTP or WordPress Email (default)? Another consideration is that I use a plugin to beautify emails 'WP HTML Mail - Email Template Designer' and if I use SMTP in EME the email is not beautified. Is there any way to modify the CSS of the email sent by EME?

**Comment by liedekef** [comment]
EME mails can be templated to your liking (don't forget that CSS and all needs to be 100% present in the mail).
See the config section on mail templates, can even be changed per event.
How you send mails is up to you. I don't rely on a third party product for SMTP in wordpress, but use EME directly. YMMV
