### ISSUE TITLE
List of holidays are not shown in calendar

### ISSUE THREAD

**Issue by d0grafter** [liedekef/events-made-easy#640]
**Describe the bug**
The List of holiday are not shown in the calendar.

ex.:
2024-05-01--2024-08-31, Sommerpause
2024-10-03, Feiertag
2024-12-20--2024-12-31, Weihnachtsferien

with

[eme_calendar full=1 htmltable=0 htmldiv=1 holiday_id=1]

I would expect the names of the holidays in the calendar

**Comment by liedekef** [comment]
This can't be reproduced: I copied over your holidays as-is and the calendar shortcode: the title shows perfectly. Maybe some CSS is hiding it on your end?

**Comment by liedekef** [comment]
holiday_chosen is passed as a data-param in eme-calendar.php, search for next_link there. So unless something is going on with how the data-params are interpreted, this should be ok. I just tried with extra alert-lines in eme.js, and the value is correctly taken.
Maybe debug eme-calendar.php there? But here it works as intented ...

**Comment by liedekef** [comment]
btw: can you demo this?

**Comment by liedekef** [comment]
I see an auto-optimize JS in your video, did you install an caching/optimizer plugin? If so: which one?
Also, check this small fix (that needed fixing anyway): https://github.com/liedekef/events-made-easy/commit/5d43d310744f4fa201b21923f6620e0db6877cb7

**Comment by liedekef** [comment]
Can you show it on a live site? So I can check some html being generated?

**Comment by liedekef** [comment]
As I suspected, the next-link has holiday_id=0:
`<a class="next-month eme-cal-next-month" href="#" data-full="1" data-htmltable="1" data-htmldiv="1" data-long_events="" data-month="10" data-year="2024" data-category="0" data-author="" data-contact_person="" data-location_id="" data-notcategory="0" data-template_id="0" data-holiday_id="0" data-weekdays="" data-language="de" data-calendar_divid="eme-calendar-122">&gt;&gt;</a>
`
So something is wrong in the shortcode-calling itself. Can you verify the shortcode and arguments?

**Comment by liedekef** [comment]
If you want, you can add some debugging in eme-calendar.php, in the function eme_get_calendar_shortcode. You could add a line 
`var_dump($atts);`
at the beginning of the function (just for 1 minute of course) and see if that already contains the correct info (should contain your shortcode arguments and values).

**Comment by liedekef** [comment]
that's like if holiday_id=1 is between quotes ... could you remove all that and add it manually? Or look in the text-version of the html editor to see if no other characters are present ...

**Comment by liedekef** [comment]
If you copy/paste parts from the EME website into your html, then this can happen. Good to know it works (and it got me to fix a minor non-bug anyway :-) )
