### ISSUE TITLE
php message on homepage as well as on pdf-ticket

### ISSUE THREAD

**Issue by SPSMH** [liedekef/events-made-easy#644]
**Describe the bug**
The following (unformatted) message is constantly shown on top of the homepage as well as on top of a created event-ticket-pdf:

div.eme-rsvp-message-success, div.eme-member-message- success,div.eme-rsvp-message-error, div.eme-member-message-error { color:#000 !important; }

**To Reproduce**
1. Go to 'https://www.bodhipath-hd.de'
5. See error on top-line

**Expected behavior**
no such line
<img width="860" alt="Bildschirmfoto 2024-09-05 um 00 04 45" src="https://github.com/user-attachments/assets/eb73251b-64b6-4c12-84c9-714aa493b4eb">

**Log output**
If applicable, check your php error logfile and add php errors here

**Version info**
PHP version: 8.2
EME version: 2.5.9

Anyway, thank you a lot for your efforts, Franky. The project is gorgeous as ever!

**Comment by liedekef** [comment]
this is not added by EME. I'm guessing you need to check your custom css files, it seems to me you tried to change the color of certain messages but did something wrong in the css.

**Comment by SPSMH** [comment]
I finally found it after a couple of hours of sleep and with a fresh mind. I will suggest to our board to send you a donation. Thanks for the swift response. Again: awesome job and many thanks for your work!

**Comment by liedekef** [comment]
So, what was the problem?

**Comment by SPSMH** [comment]
The main problem was PEBKAC. 

Technically explained: there was the precise code in the additional HTML header under EME -> settings -> other. As we didn't have any RSVP events for a while, now we have one. So apparently it was not shown until. As soon as the one event was set to RVSP it appeared. Can't explain how the CSS code made it into that field, but there it was.
