### ISSUE TITLE
Send out approved booking reminders

### ISSUE THREAD

**Issue by WXQ8NPb5TrbDNqzywcxF** [liedekef/events-made-easy#648]
**Describe the bug**
In "Settings" "RSVP" "Send out approved booking reminders" if I put multiple reminder separated by coma,  when I tried to create a new event, the default value of "RSVP" "Generic RSVP info" "Set the number of days before reminder emails will be sent for approved bookings (counting from the start date of the event). If you want to send out multiple reminders, seperate the days here by commas. Leave empty for no reminder emails." is set to only the first number,  others after coma are not shown

**To Reproduce**
1. Go to 'Setting' and 'RSVP'
2. Set 'Send out approved booking reminders' to '3,1'
3. Create a new event go to "RSVP" "Generic RSVP Info"
4. See option set to '3' instead of '3,1'
5. Go to 'Setting' and 'RSVP'
6. Set 'Send out approved booking reminders' to '8'
7. Create a new event go to "RSVP" "Generic RSVP Info"
8. See option set to '8' as it should be
9. Go to 'Setting' and 'RSVP'
10. Set 'Send out approved booking reminders' to '8,2'
11. Create a new event go to "RSVP" "Generic RSVP Info"
12. See option set to '8' instead of '8,2'

**Expected behavior**
Default settings should be applied to new event

**Screenshots**
![image](https://github.com/user-attachments/assets/849980f5-59f1-4fb5-a3dd-b1387fdbf4f4)
![image](https://github.com/user-attachments/assets/df03cde6-4532-4703-bcb5-ad5cfeb5ffed)

**Version info**
PHP version: 8.3.10
EME version: 2.5.10

**Comment by liedekef** [comment]
confirmed and fixed in dev, will be in the next version. This is the fix (but also fixes some indentations and spaces):
https://github.com/liedekef/events-made-easy/commit/9f28d1ca685db6ace79bd3b93e8f6f8fd198d0e4
