### ISSUE TITLE
Minimum Age limit for event

### ISSUE THREAD

**Issue by Sp0run** [liedekef/events-made-easy#65]
Would it be possible to age limit an event? The RSVP form would need to use the #_BIRTHDATE people field so that age could be calculated and prevent or allow the applicant to submit booking. The process must take into account the date of the event and calculate the age at the time of the event (somebody may sign up for an event under age but be the correct age at the time of the event). If using #_BIRTHDATE is not possible then perhaps a mandatory field which asks for the "age at time of event".

Either way, it would be great to prevent submission based on entered age criterion.

**Comment by liedekef** [comment]
EME has filters you can use upon RSVP submit so you can check the person birthdate compared to the event date or so.
See https://www.e-dynamics.be/wordpress/category/documentation/12-hooks-and-filters/ , the eme_eval_booking_form_post_filter is the filter you want to use.
Concerning a mandatory field: you can create custom fields and make them required.
