### ISSUE TITLE
PDF Ticket not sent when manually change from via "Mark as Paid and confirm"-Button AND #AVAILABLESPACES inadequate in e-mail

### ISSUE THREAD

**Issue by SPSMH** [liedekef/events-made-easy#657]
**Describe the bug**
Hey Franky, 

We have setup an Event with payment (in this case via Mollie), and it works very good. But some of our attendees cannot or don't want to pay through a payment service and prefer to pay through transfer. In this case the attendees fall into the "unpaid" list.

ISSUE #1
When someone pays through Mollie, they automatically receive an E-Mail with a PDF ticket (created from templates) incl. QR-Code. We receive both, a copy of the email plus an internal confirmation E-Mail.

When I set an attendee after manual bank transfer on "mark as paid and confirm" within the list, we get the internal confirmation, but the ticket-email is not sent to the attendee.
(additional question: is there a possibility to send a ticket afterwards to those who have not or claim to have not received the ticket?)

ISSUE #2
We did some test runs before going public with the event and booked some tickets. Before going online, we deleted the test-attendees. 
In the internal note I am using two placeholders. One is correct, but the other one still counts the deleted test attendees apparently. We have 95 tickets incl. 15 Waiting List.
#_RESERVEDSPACES (correct number - 20)
#_AVAILABLESPACES (less available places - 61) 
The numbers don't add (81 vs. 95).

When looking into the event itself, all numbers are correctly shown ,the numbers add. 

Besides that, I have spoken with the other board members, I told them that we are working now for a considerable time with your grenade of a tool, and we decided to make a small and humble donation, because you're awesome.

Thankfully yours,
Sebastian

**Comment by liedekef** [comment]
First: thanks for the donation, much appreciated!
Now, concerning the issues.
Issue 2: here #_FREESPACES ignores the spaces on the waiting list, so the numbers should add up then. It means you only have 80 seats and 15 extra on the waiting list. Those 15 won't get used unless all the others are used (the dropdown takes that into account when reserving seats and the warning that a reservation is on the waiting list will only appear later on)
Issue 1: I'm guessing you have auto-approve after payment activated and then "mark paid and approve" should do the same as just "mark paid". Now in this case it wasn't like that (the approval mail gets precedence). So either implement this changeset ( https://github.com/liedekef/events-made-easy/commit/d7b90117c8a9b511667c70b1794e15ff7c2d2d5a ), or configure the event to send the ticket upon approval (and not payment).
Using the latter solution, you can then also use the bulk option "resend mail after approved booking" so people will get the approval mail again (with the ticket then ...).

**Comment by liedekef** [comment]
I got no response, so I assume it is fixed. Feel free to reopen the ticket if it is not the case.
