### ISSUE TITLE
EME-group booking

### ISSUE THREAD

**Issue by d0grafter** [liedekef/events-made-easy#658]
Hello dear team,

I would like an internal option for booking recurring events. Specifically, when I have a series that repeats every four weeks. With the first booking participants are automatically assigned to an EME group. I would like this group to be internally booked through me for a new event without me having to enter each participant manually or have each participant book the series themselves. This process (loop over eme-group and book the indiviuals) should happen automatically.

Best regards,
Stefan

**Comment by liedekef** [comment]
And what exactly are you trying to achieve? Why not using a multi-booking form with your recurrence and set the min/max number of seats to book to 1 per event? That way people won't get to select the number of seats to book for an event, but just the normal info will be required (name/email/...).

**Comment by liedekef** [comment]
no further reaction, so closing.

**Comment by liedekef** [comment]
currently you can achieve this using eme_if and check the recurrence number for the rsvp form
The subsequent booking is another story. For now I would still go for the multibooking solution.
I'm guessing you have some kind of course-thing in mind?

**Comment by liedekef** [comment]
Then why not create a series for the non-booking events (second in the series until the last) and 1 bookable for the first event?

**Comment by liedekef** [comment]
Currently I believe my last suggestion is the easiest and most manageable, so for now I'm closing this.
