### ISSUE TITLE
Custom Field - Dropdown - age

### ISSUE THREAD

**Issue by Wessiez** [liedekef/events-made-easy#659]
Hai Franky,

I'm creating a custom field called "age". I want this field to become a dropdown field with age from 10 till 99.

Is there a easier way to create that dropdown, rather than insert in the field_value: 10II11II12II etc till 99?

Best regards,
Larz

**Comment by liedekef** [comment]
dropdown needs all the values, so no way around that.
But why not use html5 here? The number-type can help you with a min/max attribute:
`<input type="number" id="hour" min="10" max="99" >`
When defining a field of this type, you can enterr the min/max attributes in the "HTML field attributes" section of the new field definition.
