### ISSUE TITLE
Pre-filled Booking Form

### ISSUE THREAD

**Issue by tobuehner** [liedekef/events-made-easy#660]
Hey Franky,

I would like to invite people to a personalized event. Is it possible to pass on data from the URL to the event booking form? So that it is already pre-filled?  Since the invitees do not yet have an wp-account on the site, this is unfortunately not an option. 

Thankfully yours,
tobi

**Comment by liedekef** [comment]
Currently the only fields that can be prefilled via a GET param are the mail field (GET param name "eme_email"), the lastname (GET param name "eme_ln") and the first name (GET param name "eme_fn").
If you want more fields, javascript can help you to fill out form values based on GET params :-)

Hope this helps.
