### ISSUE TITLE
export CSV in admin Events tab

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#674]
**Describe the bug**
The CSV button on the admin Events tab does not produce the expected export file. Only a new tab, ‘about:blank’, is displayed. 

**To Reproduce**
Go in admin Events tab. Click on CSV button

**Expected behavior**
Upload a CSV file

**Log output**
No EME php error

**Version info**
PHP version: 8.3
EME version: 2.5.16

It's the same issue on production site and Local site

**Comment by liedekef** [comment]
I can't reproduce that here, the CSV button works as expected. Can you check your browser console for javascript errors?

**Comment by f14m07** [comment]
No error in the console. Print button works well. No cache in the Local site. I am going to deactivate a maximum of plugin

**Comment by f14m07** [comment]
It was not due to another plugin but due to safari. When I use chrome it works fine.

**Comment by f14m07** [comment]
Your reply was helpful, thanks a lot. Why Safari block I don't know?

**Comment by liedekef** [comment]
I'm not able to test safari, I don't own a mac ... running linux here (so I can test chrome/firefox/opera/...).
The CSV export is done via a javascript function and I assume safari doesn't like the output, but normally the outout is saved in a file, so maybe safari also saves the file?

**Comment by f14m07** [comment]
In fact, I have found an error in the console of the tab opened (about:blanck). This is the error
Not allowed to navigate top frame to data URL 'data:text/csv;charset=utf8,%22Name%22%2C%22Status%22%2C%22Copy%22%2C%22RSVP%22%2C%22Event%20price%22%2C%22Location%22%2C%22Date%20and%20time%22%2C%22Created%20on%22%2C%22CodePonton%22%2C%22Ponton-Place%20de%20d%C3%A9part%22%0D%0A%22Et%20si%20on%20naviguait%20un%20peu%20avant%20l'hiver%0Anavigation%0ARSVP%20Info%3A%20Free%3A%20%202%2C%20Approved%3A%202%2C%20Max%3A%204%20(1%20waiting%20list%20seats%20included)%20%0A(Printable%20view)%20(CSV%20export)%22%2C%22Public%0A%20View%20event%22%2C%2C%22RSVP%22%2C%22%...tte%20pour%20partager%20un%20Parmentier%20de%20canard%0Anavigation%0ARSVP%20Info%3A%20Free%3A%20%204%2C%20Approved%3A%203%2C%20Max%3A%207%20(1%20waiting%20list%20seats%20included)%20%0A(Printable%20view)%20(CSV%20export)%22%2C%22Public%0A%20View%20event%22%2C%2C%22RSVP%22%2C%22%E2%82%AC25.00%22%2C%22HORATIO%0APort%20des%20Minimes%20%0ALA%20ROCHELLE%20FRANCE%2017000%20FRANCE%22%2C%2212%20December%202024%0A10h00%20-%2017h00%22%2C%227%20November%202024%2013h23%22%2C%2221549%23%22%2C%22P13%20-%20place%2069%22'.

**Comment by liedekef** [comment]
That's very interesting ...
can you check if this changeset fixes it (remember the cache ...): https://github.com/liedekef/events-made-easy/commit/f77fb55f17fbdce757fb6f088dc6c327f8490e64

**Comment by f14m07** [comment]
Super. That works very fine. Thanks a lot for all

**Comment by liedekef** [comment]
well, it was not related to the original reported problem, but still something we got fixed :-)
