### ISSUE TITLE
Custom CSV delimiter setting not working anymore

### ISSUE THREAD

**Issue by EweLoHD** [liedekef/events-made-easy#675]
The setting "CSV delimiter" is not working for me anymore. Replacing `,` with `;` in the settings still exports the bookings of an event seperated with `,`.

Looking at the source code of the `eme_bookings_frontend_csv_report` it seems like the wrong setting is getting fetched. I think that `eme_csv_separator` should be replaced with `eme_csv_delimiter`.
https://github.com/liedekef/events-made-easy/blob/5bf0ef96a3aeaa35ce2a817bb21fdeaa0809a958/eme-rsvp.php#L621

Looking at commit fb262154df1572552dc44abbcc5b964333a9fcbf, it seems like you forgot to replace `eme_csv_separator` in the `get_option()` functions.

**Comment by liedekef** [comment]
confirmed and fixed in dev. Thanks for noticing!
