### ISSUE TITLE
Working with eme_if tags

### ISSUE THREAD

**Issue by TommieNL** [liedekef/events-made-easy#68]
Hello Franky,

I'm probably missing something but I'm trying to work with the `[eme_if tag]` options in the e-mails to the customer. 

For example:

```
[eme_if tag='#_IS_PAID' value='1']De aanmelding voor '#_EVENTNAME' is in afwachting van goedkeuring[/eme_if]
[eme_if tag='#_IS_PAID' value='0']Let op: betaling voor '#_EVENTNAME' is niet geslaagd. Lees de mail voor meer informatie[/eme_if]
```

I've booked the event and did a payment via a Mollie test API key. The booking is marked as ' payed=yes' when I look at the booking at the event. 

I've tried
```
eme_if tag='#ESC_IS_PAID' value='1' 
eme_if tag='#ESC_IS_PAID' eq='1'  
eme_if tag='#_IS_PAID' value='1' 
eme_if tag='#_IS_PAID' eq='1'
``` 

But the result is always the message that the booking isn't payed...

**Comment by TommieNL** [comment]
Ah I think I got it. It should be `eq='no'` :D

**Comment by TommieNL** [comment]
Hmm maybe I've misconfigured something. When I book the event a mail to the contact person is send out, but not to the customer... When I mail the customer from events -> bookings -> send booking related mail it works correctly...

**Comment by liedekef** [comment]
See the warning on the event mail to the respondent:
"When an event is configured to auto-approve bookings after payment and you have selected to send out payment mails and the total amount to pay is not 0, this mail is not sent but the mail concerning a booking being paid is sent when a pending booking is marked as paid."

Also: #_IS_PAID returns either 0 or 1. The placeholder #_PAID returns Yes or No.

**Comment by TommieNL** [comment]
Thanks for the reply! 

Yeah I'm aware of the auto-approve bookings settings. That one is not enabled. 

Somehow my `[eme_if]` isn't correct and therefor it won't send the e-mail...

Is there a way to troubleshoot this?

**Comment by liedekef** [comment]
The Yes/No is translated based on language. Best is to use the #_IS_PAID and compare with 0 or 1.

**Comment by TommieNL** [comment]
> The Yes/No is translated based on language. Best is to use the #_IS_PAID and compare with 0 or 1.

Ok clear.. Changed it to  `[eme_if tag='#_IS_PAID' eq='1']` This seems to be sending the mail again. 

I'm expecting 1 for true/yes and 0 for no/false, is this correct? Somehow `eq='0'` is triggered when the booking is paid...

**Comment by liedekef** [comment]
It depends which mail you're talking about and how your event is configured ...

**Comment by TommieNL** [comment]
> It depends which mail you're talking about and how your event is configured ...

I'd like to inform the customer if a paymend is not completed. 

- So I've activated the -Send Paid RSVP e-mails- option (via tab mails in settings). 
- The setting to automatically approve a booking is disabled

When I register the event 2 mails are send out right away (to contact and customer)
After payment a thrid mail is send to the customer. 
I'd like to include in that third mail the warning if a payment is unsuccessful. Via the [eme_if tag] option. 

After some testing it seems that when a payment was not successful the `[eme_if tag='#_IS_PAID' eq='0']` is not triggered. 
When i send the mail manually from the booking (via the send booking details action) the mail is triggered on  `[eme_if tag='#_IS_PAID' eq='0']`

Hope I make sense ;)
