### ISSUE TITLE
The rsvp_status parameter is not taken into account in the short code [eme_attendees id=#_EVENTID rsvp_status=2]

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#680]
**Describe the bug**
On one page I use the short code [eme_attendees id=#_EVENTID rsvp_status=1 or 2] to show approved and pending bookings. But the list displayed is always the same rsvp_status=1.

**To Reproduce**
1. have an event with pending and approved bookings
2. have a page with shortcode [eme_attendees id=#_EVENTID rsvp_status=1] and the shortcode [eme_attendees id=#_EVENTID rsvp_status=2] and [eme_attendees id=#_EVENTID rsvp_status=0]
3. You will see the same list as it was [eme_attendees id=#_EVENTID rsvp_status=1]

**Expected behavior**
I would have the list of approved bookings and another list with pending bookings.

**Log output**
No php error in logfile
and nothing in the console

**Version info**
PHP version: 8.3
EME version: 2.5.19

**Comment by liedekef** [comment]
I'm guessing you have the option activated that says "Attendees list ignore pending"
And although the comment says it is only for #_ATTENDEES, it is also for #_BOOKINGS and the corresponding shortcodes. Now I know the shortcodes can use the option rsvp_status, so I'm considering this as unwanted behaviour (so: bug) and this fixes it:
https://github.com/liedekef/events-made-easy/commit/1420dc695a1f4b4d7fb9938ea8a4c49e48efdb30

**Comment by f14m07** [comment]
Yes the bug is resolved. Thanks a lot
