### ISSUE TITLE
Create a certificate of attendance

### ISSUE THREAD

**Issue by BENETNATH** [liedekef/events-made-easy#686]
**Describe the feature**
One of the main issue in our meetings is that we need to create PDF attestation to confirm people attendance.
That's painful and takes a lot of time.
It would be great to be able to have the ability to provide a pdf template that would complete an attendance certificate on the fly.
To be sure that the person has really attended the meeting, either the organizer could check the people present during the meeting, or there could be a keyword given during the meeting to validate.

**Comment by liedekef** [comment]
Each person can receive an QR-code for attendance checking, and if you scan that code with enough rights, an attendance record is saved in EME. In the backend, you can then see who was present via the Attendance submenu.

**Comment by BENETNATH** [comment]
We are doing regulatory training meetings, and attendees have to get a certificate of attendance from us, to share with their HR.
so we have to create a PDF.
In addition, there are meeting were we will have online attendance through zoom, so it could be great to just have to check the people who attended, and they would be able to generate their certificate to download it.

**Comment by liedekef** [comment]
The next version will have an extra bulk option to mark a booking as "attendance present" (as if scanning the attendance QR-code).
I still need to think about adding an extra placeholder that you can send to people up-front that will generate a link to a pdf-proof of attendace (based on a pdf template). Or doing it via the backend when you mark the attendance. In either case an extra event setting would be needed to indicate the pdf-template to be used, so work to be done ... here I'm waitin g for a donation :-)

**Comment by BENETNATH** [comment]
Hi,
I'm looking after a way to ease the work of some volunteers in non-profit academic research labs.
sadly, no money involved..

**Comment by liedekef** [comment]
This changeset should do it: https://github.com/liedekef/events-made-easy/commit/198520896319f6a2fec6b1db49c33e487609be79

**Comment by BENETNATH** [comment]
Thanks a lot @liedekef for taking my request in consideration.
Sadly, I gave a try to install it on a fresh WP, I have a "Plugin could not be activated because it triggered a fatal error." when I try to activate the latest code, but latest release works well.

**Comment by liedekef** [comment]
I just fixed a typo error, try the dev-version from github again now

**Comment by BENETNATH** [comment]
Indeed, Activation works now.
Thanks.
I'll now learn how to use this tool and give you a feedback if you'd like

**Comment by liedekef** [comment]
Feedback is always appreciated, but indeed: first learn how to use it.

**Comment by BENETNATH** [comment]
Hi,
I gave a try to play a bit with the system.
When I check multiple attendees of an event and use the function : "Mark person as present (attendance record)"
these people are not added in the page "eme-attendance-reports" as I guess they should be ?

**Comment by liedekef** [comment]
If your event is configured to keep separate attendance records (setting "Select this option if you want an attendance record to be kept everytime the RSVP attendance QRCODE is scanned by an authorized user." ), only then will it be added in the "attendance reports" part.
Now there is an extra column in the booking overview (attendance count) that just keeps count of the times the url is checked while having enough rights to do so. The attendance submenu keeps a more detailed timetrack of that, but only if wanted. This might seem confusing, so I'm thinking about simplifying that a bit and always keep timetrack.
For now the attendance count is your cue.
