### ISSUE TITLE
Difference between Github and the release version

### ISSUE THREAD

**Issue by MichaelWybo** [liedekef/events-made-easy#69]
**Describe the bug**
Difference between released version and the github verion 

File: eme_people.php
Line 3207: 

On github:

`		$sql = $wpdb->prepare( "SELECT $people_table.person_id FROM`
In the released zip or automatic update:

`		$sql = $wpdb->prepare( "SELECT people.person_id`

I presume that will be fixed in the next version but if persons have problems with #_IS_USER_IN_GROUP placeholder that's the reason :)

**Comment by liedekef** [comment]
Indeed, (see the "snippet" discussion. I'll release today
