### ISSUE TITLE
Filter fields are cut (short)

### ISSUE THREAD

**Issue by mltest1** [liedekef/events-made-easy#693]
**Describe the bug**
Fields in the filter form is cut very short

**To Reproduce**
1. Go to https://oppnasinnen.org/medlemmar-grid/
2. See the cut fields

**Version info**
PHP version: 8.2.26
EME version: Latest 

**Additional context**

**Comment by mltest1** [comment]
I worked perfectly before I updated to the latest version of EME.

My short code is: 
[eme_filterform    category= 
6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21 template_id=27]

Template is: 
Välj en konstart:
#_FILTER_CATS{ }
Eller ett namn (söker både i för- & efternamn):
#_FILTER_LOCS{ }
#_SUBMIT{Visa ditt val}[sc name="iconbuttontextsame" text="Rensa urvalet" link="https://oppnasinnen.org/medlemmar-grid"]

So you suggest I exchange #_FILTER_CATS{ } to #_FILTER_CATS and
#_FILTER_LOCS{ } to #_FILTER_LOCS ?

**Comment by mltest1** [comment]
I solved it by adding many space instead, like #_FILTER_CATS{                                          }
That makes it look like before the update.

**Comment by mltest1** [comment]
Many spaces between {}

**Comment by liedekef** [comment]
It is possible some css is interfering here, I'm checking this out locally. Still: is it your intention to leave the initial selection blank (and not "select a category")?

**Comment by liedekef** [comment]
ok, the next version will return the older behavior (but I need to think about it, empty default is what I anticipated on)

**Comment by mltest1** [comment]
Also after selecting an item in the selction field is cut short again

**Comment by liedekef** [comment]
like I said: the next version will fix this, or for now: go in js/eme.js and change the bottom lines from
`    $('.eme_select2').select2({width: 'fit-content'});
`
to
`    $('.eme_select2').select2();
`
