### ISSUE TITLE
Add fields to RSS

### ISSUE THREAD

**Issue by bobbybosler** [liedekef/events-made-easy#697]
Hey Franky!

I just realized today that using the RSS Link shortcode in combination with [Themeco's External API integration](https://theme.co/docs/external-api-integration), that I can create my itineraries in one place and then just pull them where I need them on my other sites!

That being said, however, I am hitting my head on one thing: the limited fields that get sent to the RSS. It would be really nice if you could include a couple more "Open Slots" that we can use to export whatever data we want via RSS. Maybe a "Date" field and a "Location" field that I can format however I want. But it would be _even better_ if there could be a few blank auxiliary fields. 

Hope this makes sense!

**Comment by liedekef** [comment]
The RSS specification is quite strict, so it can't be changed. See https://www.rssboard.org/rss-specification#requiredChannelElements
Why not use the ical-feed? That has more info, has options to change the title, description and location formatting *and* you can apply a filter eme_ical_filter per single entry in the ical list.

**Comment by liedekef** [comment]
o, I see, the tool you use requires XML and you think RSS is good for this. But the RSS feed is meant to be an RSS feed, obeying the RSS standards.
