### ISSUE TITLE
Show all bookings made by a person not working

### ISSUE THREAD

**Issue by TimB111** [liedekef/events-made-easy#698]
**Describe the bug**
Just updated to the latest version of EME. The "Show All Bookings" for a selected person is showing incorrect results.

**To Reproduce**
1. Go to "People".
2. Search for a person.
3. Click on "Show All Bookings".
4. Page shows bookings for lots of other bookings.

**Expected behavior**
Should show bookings for just the one selected person.

**Version info**
PHP version: 8.2
EME version: 2.5.24

**Additional context**
Merry Christmas Franky! 🎅🎄⛄❄️

**Comment by liedekef** [comment]
confirmed, the code for that got removed by mistake :-)
This fixes that again:
https://github.com/liedekef/events-made-easy/commit/88ac35f0a54fba0ec28d9091d485c92ab694832a
