### ISSUE TITLE
Sumup gateway error 403

### ISSUE THREAD

**Issue by dfunnell1** [liedekef/events-made-easy#73]
Hi, 
I am trying to integrate sumup payment gateway into EME, but when i add it to my membership form, i get "SumUp Response error: request_not_allowed403" instead of actually displaying the payment form.
What do i need to do to fix this asap?
![Screenshot 2023-02-18 115314](https://user-images.githubusercontent.com/99143338/219864225-493c84da-c0e9-44ce-ade5-80449fe9a18c.png)

**Comment by liedekef** [comment]
See https://github.com/sumup/sumup-ecom-php-sdk/issues/31 
(and my comment on it)
