### ISSUE TITLE
Cant display CAPTCHA

### ISSUE THREAD

**Issue by sburlot** [liedekef/events-made-easy#77]
**Describe the bug**
I've tried with EME Captcha, Cloudflare Turnstile, nothing appears or is loaded.
EME Captcha works with v 2.3.51, doesnt work with 2.3.53
I havent changed anything on the site, an update broke it

**Screenshots**
One is with V2.5.51, the other with V2.5.53
<img width="532" alt="V2 3 53" src="https://user-images.githubusercontent.com/47066/220418082-a63aa01e-9353-4643-acf0-ed945a5488ca.png">
<img width="511" alt="V2 3 51" src="https://user-images.githubusercontent.com/47066/220418087-3a9367c3-de5e-497f-a012-ff0ac68d0ad3.png">

**Additional context**
WordPress 6.0.3

**Comment by liedekef** [comment]
Confirmed, I released a new version that should fix this.

**Comment by sburlot** [comment]
When do you sleep?
Thanks!
