### ISSUE TITLE
Warning: Undefined array key

### ISSUE THREAD

**Issue by Navegola** [liedekef/events-made-easy#78]
Warning: Undefined array key "event_id" in
eme-events.php on line 2282
eme-events.php on line 2283

Warning: Undefined array key "location_id" in
eme-locations.php on line 1948
eme-locations.php on line 1949

In this shortcode: [eme_events scope=this_week]

**Comment by liedekef** [comment]
Confirmed, this fixes it:
https://github.com/liedekef/events-made-easy/commit/c4c7630dcf4f6a651fa17ca55e0d1529cb524421
