### ISSUE TITLE
Multibooking form shows nothing with several events

### ISSUE THREAD

**Issue by jantoni** [liedekef/events-made-easy#83]
[EME](url) Versión 2.3.14

Shows nothing with more than 1 event.

For example:
[eme_add_multibooking_form id=270 template_id=99 template_id_header=97 template_id_footer=98]

works fine and shows the booking form OK

[https://bkia.es/wp-content/uploads/2023/03/Captura-de-pantalla-2023-03-01-210411.png](https://bkia.es/wp-content/uploads/2023/03/Captura-de-pantalla-2023-03-01-210411.png)

But whith this shortcode:
[eme_add_multibooking_form id=270,271,272,273 template_id=99 template_id_header=97 template_id_footer=98]

shows nothing. Only a white line.

[https://bkia.es/wp-content/uploads/2023/03/Captura-de-pantalla-2023-03-01-210721.png](https://bkia.es/wp-content/uploads/2023/03/Captura-de-pantalla-2023-03-01-210721.png)

The 4 events are identical, they only differ in name of event, date and time.

```
Multibooking form header:
#REQ_LASTNAME
#REQ_FIRSTNAME
#REQ_EMAIL
#REQ_PHONE
<ul>

Multibooking form 
<li>
#_{d/m/Y} #_24HSTARTTIME #_SEATS
</li>

Multibooking form foot:
</ul>
#_SUBMIT
```

Without  templates the issue is identical:
[eme_add_multibooking_form id=270] works OK
[eme_add_multibooking_form id=270,271,272,273] shows nothing

**Comment by jantoni** [comment]
I upgraded to 2.3.56

Same issue

**Comment by liedekef** [comment]
I can't reproduce this here (works fine). Is there a live test-page I can visit?
And: anything in the apache/php logs?

**Comment by jantoni** [comment]
[https://bkia.es/test-eme/](https://bkia.es/test-eme/)

The only shortcode is

[eme_add_multibooking_form id=270,271,272,273 template_id=99 template_id_header=97 template_id_footer=98]

**Comment by jantoni** [comment]
No errors found in the server logs

**Comment by jantoni** [comment]
Mystery solved

Events were in draft mode for testing without being seen by users.

That was the problem

By changing the events to public everything works correctly

Thank you franky
