### ISSUE TITLE
Dynamic fields

### ISSUE THREAD

**Issue by blanch80** [liedekef/events-made-easy#87]
Hi Franky,

Is it possible to show dynamic data based on a value in a users Wordpress profile?

I've got it working well showing dynamic data based on conditions on other values on the booking form, but wondered for example, if a user has to choose a country on registration for the site, the dynamic data functionality could reference that WordPress profile value.

With People in EME being linked to WP User, if a user chooses Country: England on their WordPress profile, could EME then show a specific template after checking that value?

Thanks,
David.

**Comment by liedekef** [comment]
It is currently not possible, but not that difficult to add though. Problem is more that I do not know the field name of any custom (meta) field in the WP profile, so that would be up to you to figure out (and there's a difference with default wp fields and all custom fields, WP is kind of lacking in profiles).
Currently marked as feature request.

**Comment by blanch80** [comment]
Cheers Franky - appreciate you having a look at it. 

Out example could be Role Type, so if a user selects Role Type 1 on their WordPress registration they're shown one template dynamically, then if they select Role Type 2 they'd be shown another.

I'm happy to have a go at figuring out the custom (meta) fields if you're able to start me off? Happy to test it too if you're planning on implementing it.

**Comment by liedekef** [comment]
Currently the dev-version has this change:

Add generic placeholders #_WPUSERDATA{xx} and #_WPUSERMETA{xx}

meaning you can get the value of user data (main wp profile info) and meta (other fields) info.

**Comment by blanch80** [comment]
This is fantastic, thanks Franky - can't wait to test it out.

**Comment by blanch80** [comment]
I'm not that familiar with github, I can see the 2.3.58 release to download but can't see the dev version.

**Comment by liedekef** [comment]
Go to "code" and there click on the green button to download a zip. The url to the dev-zip is always this:
https://github.com/liedekef/events-made-easy/archive/refs/heads/main.zip

**Comment by liedekef** [comment]
I'll close this now. Feel Free to react if not working as expected.

**Comment by blanch80** [comment]
Hi Franky,

Sorry it's taken so long to get back to you. This does pull some detail in but not all.

For example, using the code:

`<table class='eme-rsvp-form'>
    <tr><th scope='row'>First Name*:</th><td>#REQ_FIRSTNAME</td></tr>#_SEATS 
    <tr><th scope='row'>Last Name*:</th><td>#_LASTNAME</td></tr>
    <tr><th scope='row'>E-Mail*:</th><td>#_EMAIL</td></tr>
    <tr><th scope='row'>WPUSERDATA:</th><td>#_WPUSERDATA{role}</td></tr>
    <tr><th scope='row'>WPUSERMETA:</th><td>#_WPUSERMETA{role}</td></tr>
    <tr><th scope='row'>WPUSERDATA:</th><td>#_WPUSERDATA{nickname}</td></tr>
    <tr><th scope='row'>WPUSERMETA:</th><td>#_WPUSERMETA{nickname}</td></tr>
    <tr><th scope='row'>WPUSERDATA:</th><td>#_WPUSERDATA{last_name}</td></tr>
    <tr><th scope='row'>WPUSERMETA:</th><td>#_WPUSERMETA{last_name}</td></tr>
</table>
#_SUBMIT`

This brings in the user nickname or last_name whether WPUSERDATA or WPUSERMETA is used, but neither of them bring in the user role. I've tried using roles but when loading the event after using roles I see the error There has been a critical error on this website and the page doesn't render correctly. Removing 'roles' resolves this problem.

I've also tried pulling in bp_member_type, that doesn't return a value but is a column header when I try exporting user data into a csv.

Hope you can help.

Thanks.

**Comment by liedekef** [comment]
roles is an array, and printing that will probably cause the error. Try this:
https://github.com/liedekef/events-made-easy/commit/ad5305cf135101e45ca8925cd503ec0c351b7dff
