### ISSUE TITLE
plugin disappeared from wordpress

### ISSUE THREAD

**Issue by dfunnell1** [liedekef/events-made-easy#92]
**Describe the bug**

The plugin has been deactivated by wordpress due to an error. 
I now can't find the plugin in my list of installed plugins, nor can i find it by searching wordpress for plugins and i can't even manuall upload the file that i've downloaded from github (latest version).

**Comment by liedekef** [comment]
Reason for wp: https://www.e-dynamics.be/wordpress/forums/topic/security-release/
Concerning your github problem, see the install instructions for existing users:

– Take a database backup to be sure
– Download the zip “events-made-easy.zip” from the latest release on github ( https://github.com/liedekef/events-made-easy/releases )
– Go in the WordPress ‘Plugins’ menu, and click on “Add new”
– Select the zip you downloaded, this will upload the zip and replace the existing installation without losing data
If the file is too big for uploading, try again with “events-made-easy-minimal.zip” (which is a minimum version of the previous release, after which a regular update will present itself).
If still too big, or you need to use FTP/SSH: use your favorite upload tool to upload the contents of the zip file to the /wp-content/plugins/events-made-easy directory (remove the old files first)
– After that, updating the plugin will be as usual in the backend

If you have upload issues, try the minimal-hint above.

**Comment by liedekef** [comment]
If you didn't delete the plugin first, wordpress would've proposed to replace it. But since probably the main plugin file was already deleted by you, wordpress couldn't detect the plugin name/version and thus could only report the problem about the directory existing. Your filemanager action (or doing it via ftp or ssh) was then the only method left indeed.
