### ISSUE TITLE
*Bug* changing variables in mail-template to anwser booked person?

### ISSUE THREAD

**Issue by FoxFoxCode** [liedekef/events-made-easy#96]
**Describe the bug**
I want to use the variables in an e-mail template to give Address, Zip-Code & City back to the booked user.
#REQ_ADDRESS1
#REQ_ZIP
#REQ_CITY

The Problem is, that the variables change automatically and use the data from the linked location to the event.
Ther shouldn't be the data from the location. There should be the data, Address, Zip-Code & City from the booked user.
That isn't working.

Thanks.

**Comment by liedekef** [comment]
See the doc at https://www.e-dynamics.be/wordpress/people-placeholders/ :
 **Below are all the possible placeholders, but to avoid clashing with placeholders from events, bookings, … you can (should) use “#_PERSON” in front of all related placeholders (so #_EMAIL can be #_PERSONEMAIL etc …).**

So, use PERSONADDRESS1, ...

**Comment by FoxFoxCode** [comment]
omg ... sorry ... thanks a lot
